# Code generated by `ubx sdk gen` from datadog_fleet_schedules_v2_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SchedulesV2Response_Data_Attributes_NotificationRule:
    handles: Any = None
    tags: Any = None

@dataclasses.dataclass
class SchedulesV2Response_Data_Attributes_Rule:
    days_of_week: Any = None
    interval: Any = None
    maintenance_window_duration: Any = None
    start_maintenance_window: Any = None
    timezone: Any = None

@dataclasses.dataclass
class SchedulesV2Response_Data_Attributes:
    created_at: Any = None
    created_by: Any = None
    is_default: Any = None
    name: Any = None
    next_run: Any = None
    notification_rule: Any = None
    query: Any = None
    rule: Any = None
    status: Any = None
    updated_at: Any = None
    updated_by: Any = None
    version_to_latest: Any = None

@dataclasses.dataclass
class SchedulesV2Response_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class SchedulesV2Response_Meta_Page:
    # Total number of schedules returned.
    total_count: Any = None

@dataclasses.dataclass
class SchedulesV2Response_Meta:
    # Pagination details for the v2 list of schedules.
    page: Any = None

@dataclasses.dataclass
class SchedulesV2ResponseConfig:
    pass

@dataclasses.dataclass
class SchedulesV2ResponseAttrs:
    # Array of schedules for the organization.
    data: Any = None
    # Metadata for the v2 list of schedules response.
    meta: Any = None

SchedulesV2Response = ubx.DataSourceBinding(
    wire_type="datadog_fleet_schedules_v2_response",
    fields={
    },
)
