# Code generated by `ubx sdk gen` from datadog_notification_channel. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Channel_Data_Attributes_Config:
    address: Any = None
    formats: Any = None
    number: Any = None
    type: Any = None

@dataclasses.dataclass
class Channel_Data_Attributes:
    # Defines the configuration for creating an On-Call notification channel
    config: Any = None

@dataclasses.dataclass
class Channel_Data:
    # Attributes for creating an on-call notification channel.
    attributes: Any = None
    # Indicates that the resource is of type 'notification_channels'.
    type: Any = None

_Channel_Data_Attributes_ConfigFields = {
    "address": ubx.FieldSpec(wire_name="address"),
    "formats": ubx.FieldSpec(wire_name="formats"),
    "number": ubx.FieldSpec(wire_name="number"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_Channel_Data_AttributesFields = {
    "config": ubx.FieldSpec(
        wire_name="config",
        kind="object",
        fields=_Channel_Data_Attributes_ConfigFields,
    ),
}

_Channel_DataFields = {
    "attributes": ubx.FieldSpec(
        wire_name="attributes",
        kind="object",
        fields=_Channel_Data_AttributesFields,
    ),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class ChannelConfig:
    # Data for creating an on-call notification channel
    data: Any = None
    # path parameter, not part of the API's own resource representation
    user_id: Any = None
    # path parameter, not part of the API's own resource representation
    channel_id: Any = None

@dataclasses.dataclass
class ChannelAttrs:
    # Data for creating an on-call notification channel
    data: Any = None
    # path parameter, not part of the API's own resource representation
    user_id: Any = None
    # path parameter, not part of the API's own resource representation
    channel_id: Any = None

Channel = ubx.ResourceBinding(
    wire_type="datadog_notification_channel",
    fields={
        "data": ubx.FieldSpec(
            wire_name="data",
            kind="object",
            fields=_Channel_DataFields,
        ),
        "user_id": ubx.FieldSpec(wire_name="user_id"),
        "channel_id": ubx.FieldSpec(wire_name="channel_id"),
    },
)
