// Code generated by `ubx sdk gen` from datadog_deployment_rule_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RuleResponse_Data_Attributes_Options {
  allowedResources?: string[] | Computed<string[]>;
  duration?: number | Computed<number>;
  excludedResources?: string[] | Computed<string[]>;
  failOnNoData?: boolean | Computed<boolean>;
  failOnNoGroupsFound?: boolean | Computed<boolean>;
  query?: string | Computed<string>;
  warmup?: number | Computed<number>;
}

export interface RuleResponse_Data_Attributes {
  /** Whether this rule is run in dry-run mode. */
  dryRun?: boolean | Computed<boolean>;
  /** The name of the deployment rule. */
  name: string | Computed<string>;
  /** Options for deployment rule response representing either faulty deployment detection or monitor options. */
  options: RuleResponse_Data_Attributes_Options | Computed<RuleResponse_Data_Attributes_Options>;
  /** The type of the deployment rule (faulty_deployment_detection or monitor). */
  type: string | Computed<string>;
}

export interface RuleResponse_Data {
  /** Parameters for creating a deployment rule. */
  attributes: RuleResponse_Data_Attributes | Computed<RuleResponse_Data_Attributes>;
  /** Deployment rule resource type. */
  type: string | Computed<string>;
}

const RuleResponse_Data_Attributes_OptionsFields: FieldMap = {
  allowedResources: "allowed_resources",
  duration: "duration",
  excludedResources: "excluded_resources",
  failOnNoData: "fail_on_no_data",
  failOnNoGroupsFound: "fail_on_no_groups_found",
  query: "query",
  warmup: "warmup",
};

const RuleResponse_Data_AttributesFields: FieldMap = {
  dryRun: "dry_run",
  name: "name",
  options: {
    wireName: "options",
    kind: "object",
    fields: RuleResponse_Data_Attributes_OptionsFields,
  },
  type: "type",
};

const RuleResponse_DataFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: RuleResponse_Data_AttributesFields,
  },
  type: "type",
};

export interface RuleResponseConfig {
  /** Parameters for creating a deployment rule. */
  data?: RuleResponse_Data | Computed<RuleResponse_Data>;
  /** path parameter, not part of the API's own resource representation */
  gateId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  id: string | Computed<string>;
}

export interface RuleResponseAttrs {
  /** Parameters for creating a deployment rule. */
  data: RuleResponse_Data;
  /** path parameter, not part of the API's own resource representation */
  gateId: string;
  /** path parameter, not part of the API's own resource representation */
  id: string;
}

export const RuleResponse: ResourceBinding<RuleResponseConfig, RuleResponseAttrs> = {
  wireType: "datadog_deployment_rule_response",
  fields: {
    data: {
      wireName: "data",
      kind: "object",
      fields: RuleResponse_DataFields,
    },
    gateId: "gate_id",
    id: "id",
  },
};
