// Code generated by `ubx sdk gen` from datadog_incident_responders_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RespondersResponse_Data_Attributes {
  created?: string | Computed<string>;
  externalId?: string | Computed<string>;
  externalSource?: string | Computed<string>;
  isBillable?: boolean | Computed<boolean>;
  lastActive?: string | Computed<string>;
  meta?: Record<string, unknown> | Computed<Record<string, unknown>>;
  modified?: string | Computed<string>;
}

export interface RespondersResponse_Data_Relationships_CreatedBy_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RespondersResponse_Data_Relationships_CreatedBy {
  data?: RespondersResponse_Data_Relationships_CreatedBy_Data | Computed<RespondersResponse_Data_Relationships_CreatedBy_Data>;
}

export interface RespondersResponse_Data_Relationships_RoleAssignments {
  data?: RespondersResponse_Data_Relationships_CreatedBy_Data[] | Computed<RespondersResponse_Data_Relationships_CreatedBy_Data[]>;
}

export interface RespondersResponse_Data_Relationships {
  createdBy?: RespondersResponse_Data_Relationships_CreatedBy | Computed<RespondersResponse_Data_Relationships_CreatedBy>;
  lastModifiedBy?: RespondersResponse_Data_Relationships_CreatedBy | Computed<RespondersResponse_Data_Relationships_CreatedBy>;
  roleAssignments?: RespondersResponse_Data_Relationships_RoleAssignments | Computed<RespondersResponse_Data_Relationships_RoleAssignments>;
  user?: RespondersResponse_Data_Relationships_CreatedBy | Computed<RespondersResponse_Data_Relationships_CreatedBy>;
}

export interface RespondersResponse_Data {
  attributes?: RespondersResponse_Data_Attributes | Computed<RespondersResponse_Data_Attributes>;
  id?: string | Computed<string>;
  relationships?: RespondersResponse_Data_Relationships | Computed<RespondersResponse_Data_Relationships>;
  type?: string | Computed<string>;
}

export interface RespondersResponse_Included_Attributes {
  email?: string | Computed<string>;
  handle?: string | Computed<string>;
  icon?: string | Computed<string>;
  name?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface RespondersResponse_Included {
  attributes?: RespondersResponse_Included_Attributes | Computed<RespondersResponse_Included_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RespondersResponseConfig {
  incidentId: string | Computed<string>;
}

export interface RespondersResponseAttrs {
  /** List of incident responders. */
  data: RespondersResponse_Data[];
  incidentId: string;
  /** Included related resources. */
  included: RespondersResponse_Included[];
}

export const RespondersResponse: DataSourceBinding<RespondersResponseConfig, RespondersResponseAttrs> = {
  wireType: "datadog_incident_responders_response",
  fields: {
    incidentId: "incident_id",
  },
};
