// Code generated by `ubx sdk gen` from datadog_process_summary_list. DO NOT EDIT.
package process

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SummaryList_Data_Attributes struct {
	Cmdline any
	Host any
	Pid any
	Ppid any
	Start any
	Tags any
	Timestamp any
	User any
}

type SummaryList_Data struct {
	Attributes any
	Id any
	Type any
}

type SummaryList_Meta_Page struct {
	// The cursor used to get the next results, if any. To make the next request, use the same parameters with the addition of the `page[cursor]`.
	After any
	// Number of results returned.
	Size any
}

type SummaryList_Meta struct {
	// Paging attributes.
	Page any
}

type SummaryListConfig struct {
	From any
	Search any
	Tags any
	To any
}

type SummaryListAttrs struct {
	// Array of process summary objects.
	Data any
	From any
	// Response metadata object.
	Meta any
	Search any
	Tags any
	To any
}

var SummaryList = ubx.DataSourceBinding{
	WireType: "datadog_process_summary_list",
	Fields: ubx.FieldMap{
		"From": ubx.FieldSpec{WireName: "from"},
		"Search": ubx.FieldSpec{WireName: "search"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"To": ubx.FieldSpec{WireName: "to"},
	},
}
