// Code generated by `ubx sdk gen` from datadog_application_security_policy_list_response. DO NOT EDIT.
package application

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SecurityPolicyListResponse_Data_Attributes_Rules struct {
	Blocking any
	Enabled any
	ExtendedDataCollection any
	Id any
}

type SecurityPolicyListResponse_Data_Attributes_Rulesets struct {
	Blocking any
	Enabled any
	Id any
}

type SecurityPolicyListResponse_Data_Attributes_Scope struct {
	Env any
	Service any
}

type SecurityPolicyListResponse_Data_Attributes struct {
	Description any
	IsDefault any
	Name any
	ProtectionPresets any
	Rules any
	Rulesets any
	Scope any
	Version any
}

type SecurityPolicyListResponse_Data_Meta struct {
	AddedAt any
	AddedBy any
	AddedByName any
	ModifiedAt any
	ModifiedBy any
	ModifiedByName any
}

type SecurityPolicyListResponse_Data struct {
	Attributes any
	Id any
	Meta any
	Type any
}

type SecurityPolicyListResponseConfig struct {
}

type SecurityPolicyListResponseAttrs struct {
	// The WAF policy data.
	Data any
}

var SecurityPolicyListResponse = ubx.DataSourceBinding{
	WireType: "datadog_application_security_policy_list_response",
	Fields: ubx.FieldMap{
	},
}
