# Code generated by `ubx sdk gen` from datadog_slohistory_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Response_Data_Groups_Errors:
    error_message: Any = None
    error_type: Any = None

@dataclasses.dataclass
class Response_Data_Groups:
    error_budget_remaining: Any = None
    errors: Any = None
    group: Any = None
    history: Any = None
    monitor_modified: Any = None
    monitor_type: Any = None
    name: Any = None
    precision: Any = None
    preview: Any = None
    sli_value: Any = None
    span_precision: Any = None
    uptime: Any = None

@dataclasses.dataclass
class Response_Data_Overall:
    # A mapping of threshold `timeframe` to the remaining error budget.
    error_budget_remaining: Any = None
    # An array of error objects returned while querying the history data for the service level objective.
    errors: Any = None
    # For groups in a grouped SLO, this is the group name.
    group: Any = None
    # The state transition history for `monitor` or `time-slice` SLOs. It is represented as an array of pairs. Each pair is an array containing the timestamp of the transition as an integer in Unix epoch format in the first element, and the state as an integer in the second element. An integer value of `0` for state means uptime, `1` means downtime, and `2` means no data. Periods of no data count as uptime in time-slice SLOs, while for monitor SLOs, no data is counted either as uptime or downtime depending on monitor settings. See [SLO documentation](https://docs.datadoghq.com/service_management/service_level_objectives/monitor/#missing-data) for detailed information.
    history: Any = None
    # For `monitor` based SLOs, this is the last modified timestamp in epoch seconds of the monitor.
    monitor_modified: Any = None
    # For `monitor` based SLOs, this describes the type of monitor.
    monitor_type: Any = None
    # For groups in a grouped SLO, this is the group name. For monitors in a multi-monitor SLO, this is the monitor name.
    name: Any = None
    # A mapping of threshold `timeframe` to number of accurate decimals, regardless of the from && to timestamp.
    precision: Any = None
    # For `monitor` based SLOs, when `true` this indicates that a replay is in progress to give an accurate uptime calculation.
    preview: Any = None
    # The current SLI value of the SLO over the history window.
    sli_value: Any = None
    # The amount of decimal places the SLI value is accurate to for the given from `&&` to timestamp.
    span_precision: Any = None
    # Use `sli_value` instead.
    uptime: Any = None

@dataclasses.dataclass
class Response_Data_Series_Denominator_Metadata_Unit:
    family: Any = None
    id: Any = None
    name: Any = None
    plural: Any = None
    scale_factor: Any = None
    short_name: Any = None

@dataclasses.dataclass
class Response_Data_Series_Denominator_Metadata:
    # Query aggregator function.
    aggr: Any = None
    # Query expression.
    expression: Any = None
    # Query metric used.
    metric: Any = None
    # Query index from original combined query.
    query_index: Any = None
    # Query scope.
    scope: Any = None
    # An array of metric units that contains up to two unit objects. For example, bytes represents one unit object and bytes per second represents two unit objects. If a metric query only has one unit object, the second array element is null.
    unit: Any = None

@dataclasses.dataclass
class Response_Data_Series_Denominator:
    # Count of submitted metrics.
    count: Any = None
    # Query metadata.
    metadata: Any = None
    # Total sum of the query.
    sum: Any = None
    # The query values for each metric.
    values: Any = None

@dataclasses.dataclass
class Response_Data_Series:
    # A representation of `metric` based SLO timeseries for the provided queries. This is the same response type from `batch_query` endpoint.
    denominator: Any = None
    # The aggregated query interval for the series data. It's implicit based on the query time window.
    interval: Any = None
    # Optional message if there are specific query issues/warnings.
    message: Any = None
    # A representation of `metric` based SLO timeseries for the provided queries. This is the same response type from `batch_query` endpoint.
    numerator: Any = None
    # The combined numerator and denominator query CSV.
    query: Any = None
    # The series result type. This mimics `batch_query` response type.
    res_type: Any = None
    # The series response version type. This mimics `batch_query` response type.
    resp_version: Any = None
    # An array of query timestamps in EPOCH milliseconds.
    times: Any = None

@dataclasses.dataclass
class Response_Data_Thresholds:
    target: Any = None
    target_display: Any = None
    timeframe: Any = None
    warning: Any = None
    warning_display: Any = None

@dataclasses.dataclass
class Response_Data:
    # The `from` timestamp in epoch seconds.
    from_ts: Any = None
    # For `metric` based SLOs where the query includes a group-by clause, this represents the list of grouping parameters. This is not included in responses for `monitor` based SLOs.
    group_by: Any = None
    # For grouped SLOs, this represents SLI data for specific groups. This is not included in the responses for `metric` based SLOs.
    groups: Any = None
    # For multi-monitor SLOs, this represents SLI data for specific monitors. This is not included in the responses for `metric` based SLOs.
    monitors: Any = None
    # An object that holds an SLI value and its associated data. It can represent an SLO's overall SLI value. This can also represent the SLI value for a specific monitor in multi-monitor SLOs, or a group in grouped SLOs.
    overall: Any = None
    # A `metric` based SLO history response. This is not included in responses for `monitor` based SLOs.
    series: Any = None
    # mapping of string timeframe to the SLO threshold.
    thresholds: Any = None
    # The `to` timestamp in epoch seconds.
    to_ts: Any = None
    # The type of the service level objective.
    type: Any = None
    # A numeric representation of the type of the service level objective (`0` for monitor, `1` for metric). Always included in service level objective responses. Ignored in create/update requests.
    type_id: Any = None

@dataclasses.dataclass
class Response_Errors:
    error: Any = None

@dataclasses.dataclass
class ResponseConfig:
    apply_correction: Any = None
    from_ts: Any = None
    slo_id: Any = None
    target: Any = None
    to_ts: Any = None

@dataclasses.dataclass
class ResponseAttrs:
    apply_correction: Any = None
    # An array of service level objective objects.
    data: Any = None
    # A list of errors while querying the history data for the service level objective.
    errors: Any = None
    from_ts: Any = None
    slo_id: Any = None
    target: Any = None
    to_ts: Any = None

Response = ubx.DataSourceBinding(
    wire_type="datadog_slohistory_response",
    fields={
        "apply_correction": ubx.FieldSpec(wire_name="apply_correction"),
        "from_ts": ubx.FieldSpec(wire_name="from_ts"),
        "slo_id": ubx.FieldSpec(wire_name="slo_id"),
        "target": ubx.FieldSpec(wire_name="target"),
        "to_ts": ubx.FieldSpec(wire_name="to_ts"),
    },
)
