// Code generated by `ubx sdk gen` from datadog_app_key_registration_data. DO NOT EDIT.
package app

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type KeyRegistrationData_Data struct {
	Id any
	Type any
}

type KeyRegistrationData_Meta struct {
	// The total number of app key registrations.
	Total any
	// The total number of app key registrations that match the specified filters.
	TotalFiltered any
}

type KeyRegistrationDataConfig struct {
}

type KeyRegistrationDataAttrs struct {
	// An array of app key registrations.
	Data any
	// The definition of `ListAppKeyRegistrationsResponseMeta` object.
	Meta any
}

var KeyRegistrationData = ubx.DataSourceBinding{
	WireType: "datadog_app_key_registration_data",
	Fields: ubx.FieldMap{
	},
}
