# Code generated by `ubx sdk gen` from datadog_arbitrary_rule_status_response_data. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class RuleStatusResponseData_Data_Attributes:
    processing_status: Any = None

@dataclasses.dataclass
class RuleStatusResponseData_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class RuleStatusResponseDataConfig:
    pass

@dataclasses.dataclass
class RuleStatusResponseDataAttrs:
    # Processing status for a custom allocation rule.
    data: Any = None

RuleStatusResponseData = ubx.DataSourceBinding(
    wire_type="datadog_arbitrary_rule_status_response_data",
    fields={
    },
)
