// Code generated by `ubx sdk gen` from datadog_synthetics_test_parent_suite_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TestParentSuiteData_Data_Attributes {
  childName?: string | Computed<string>;
  childPublicId?: string | Computed<string>;
  monitorId?: number | Computed<number>;
  name?: string | Computed<string>;
  overallState?: number | Computed<number>;
  overallStateModified?: string | Computed<string>;
  publicId?: string | Computed<string>;
}

export interface TestParentSuiteData_Data {
  attributes?: TestParentSuiteData_Data_Attributes | Computed<TestParentSuiteData_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface TestParentSuiteDataConfig {
  publicId: string | Computed<string>;
}

export interface TestParentSuiteDataAttrs {
  /** List of parent suites for the given test. */
  data: TestParentSuiteData_Data[];
  publicId: string;
}

export const TestParentSuiteData: DataSourceBinding<TestParentSuiteDataConfig, TestParentSuiteDataAttrs> = {
  wireType: "datadog_synthetics_test_parent_suite_data",
  fields: {
    publicId: "public_id",
  },
};
