// Code generated by `ubx sdk gen` from datadog_synthetics_test_details_without_steps_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TestDetailsWithoutStepsList_Tests_Config_Assertions {
  code?: string | Computed<string>;
  operator?: string | Computed<string>;
  property?: string | Computed<string>;
  target?: unknown | Computed<unknown>;
  timingsScope?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Config_ConfigVariables {
  example?: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  pattern?: string | Computed<string>;
  secure?: boolean | Computed<boolean>;
  type?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Config_Request_BasicAuth_AddClaims {
  exp?: boolean | Computed<boolean>;
  iat?: boolean | Computed<boolean>;
}

export interface TestDetailsWithoutStepsList_Tests_Config_Request_BasicAuth {
  accessKey?: string | Computed<string>;
  accessTokenUrl?: string | Computed<string>;
  addClaims?: TestDetailsWithoutStepsList_Tests_Config_Request_BasicAuth_AddClaims | Computed<TestDetailsWithoutStepsList_Tests_Config_Request_BasicAuth_AddClaims>;
  algorithm?: string | Computed<string>;
  audience?: string | Computed<string>;
  clientId?: string | Computed<string>;
  clientSecret?: string | Computed<string>;
  domain?: string | Computed<string>;
  expiresIn?: number | Computed<number>;
  header?: string | Computed<string>;
  password?: string | Computed<string>;
  payload?: string | Computed<string>;
  region?: string | Computed<string>;
  resource?: string | Computed<string>;
  scope?: string | Computed<string>;
  secret?: string | Computed<string>;
  secretKey?: string | Computed<string>;
  serviceName?: string | Computed<string>;
  sessionToken?: string | Computed<string>;
  tokenApiAuthentication?: string | Computed<string>;
  tokenPrefix?: string | Computed<string>;
  type?: string | Computed<string>;
  username?: string | Computed<string>;
  workstation?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Config_Request_Certificate_Cert {
  content?: string | Computed<string>;
  filename?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Config_Request_Certificate {
  cert?: TestDetailsWithoutStepsList_Tests_Config_Request_Certificate_Cert | Computed<TestDetailsWithoutStepsList_Tests_Config_Request_Certificate_Cert>;
  key?: TestDetailsWithoutStepsList_Tests_Config_Request_Certificate_Cert | Computed<TestDetailsWithoutStepsList_Tests_Config_Request_Certificate_Cert>;
}

export interface TestDetailsWithoutStepsList_Tests_Config_Request_Files {
  bucketKey?: string | Computed<string>;
  content?: string | Computed<string>;
  encoding?: string | Computed<string>;
  name?: string | Computed<string>;
  originalFileName?: string | Computed<string>;
  size?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Config_Request_Proxy {
  headers?: Record<string, string> | Computed<Record<string, string>>;
  url?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Config_Request {
  allowInsecure?: boolean | Computed<boolean>;
  basicAuth?: TestDetailsWithoutStepsList_Tests_Config_Request_BasicAuth | Computed<TestDetailsWithoutStepsList_Tests_Config_Request_BasicAuth>;
  body?: string | Computed<string>;
  bodyType?: string | Computed<string>;
  callType?: string | Computed<string>;
  certificate?: TestDetailsWithoutStepsList_Tests_Config_Request_Certificate | Computed<TestDetailsWithoutStepsList_Tests_Config_Request_Certificate>;
  certificateDomains?: string[] | Computed<string[]>;
  checkCertificateRevocation?: boolean | Computed<boolean>;
  compressedJsonDescriptor?: string | Computed<string>;
  compressedProtoFile?: string | Computed<string>;
  disableAiaIntermediateFetching?: boolean | Computed<boolean>;
  dnsServer?: string | Computed<string>;
  dnsServerPort?: unknown | Computed<unknown>;
  files?: TestDetailsWithoutStepsList_Tests_Config_Request_Files[] | Computed<TestDetailsWithoutStepsList_Tests_Config_Request_Files[]>;
  followRedirects?: boolean | Computed<boolean>;
  form?: Record<string, string> | Computed<Record<string, string>>;
  headers?: Record<string, string> | Computed<Record<string, string>>;
  host?: string | Computed<string>;
  httpVersion?: string | Computed<string>;
  ignoreCertificateValidation?: boolean | Computed<boolean>;
  isMessageBase64Encoded?: boolean | Computed<boolean>;
  mcpProtocolVersion?: string | Computed<string>;
  message?: string | Computed<string>;
  metadata?: Record<string, string> | Computed<Record<string, string>>;
  method?: string | Computed<string>;
  noSavingResponseBody?: boolean | Computed<boolean>;
  numberOfPackets?: number | Computed<number>;
  persistCookies?: boolean | Computed<boolean>;
  port?: unknown | Computed<unknown>;
  proxy?: TestDetailsWithoutStepsList_Tests_Config_Request_Proxy | Computed<TestDetailsWithoutStepsList_Tests_Config_Request_Proxy>;
  query?: unknown | Computed<unknown>;
  servername?: string | Computed<string>;
  service?: string | Computed<string>;
  shouldTrackHops?: boolean | Computed<boolean>;
  timeout?: number | Computed<number>;
  toolArgs?: Record<string, unknown> | Computed<Record<string, unknown>>;
  toolName?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Config {
  assertions?: TestDetailsWithoutStepsList_Tests_Config_Assertions[] | Computed<TestDetailsWithoutStepsList_Tests_Config_Assertions[]>;
  configVariables?: TestDetailsWithoutStepsList_Tests_Config_ConfigVariables[] | Computed<TestDetailsWithoutStepsList_Tests_Config_ConfigVariables[]>;
  request?: TestDetailsWithoutStepsList_Tests_Config_Request | Computed<TestDetailsWithoutStepsList_Tests_Config_Request>;
  variables?: TestDetailsWithoutStepsList_Tests_Config_ConfigVariables[] | Computed<TestDetailsWithoutStepsList_Tests_Config_ConfigVariables[]>;
}

export interface TestDetailsWithoutStepsList_Tests_Creator {
  email?: string | Computed<string>;
  handle?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Options_Ci {
  executionRule?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Options_MonitorOptions {
  escalationMessage?: string | Computed<string>;
  notificationPresetName?: string | Computed<string>;
  renotifyInterval?: number | Computed<number>;
  renotifyOccurrences?: number | Computed<number>;
}

export interface TestDetailsWithoutStepsList_Tests_Options_Retry {
  count?: number | Computed<number>;
  interval?: number | Computed<number>;
}

export interface TestDetailsWithoutStepsList_Tests_Options_RumSettings {
  applicationId?: string | Computed<string>;
  clientTokenId?: number | Computed<number>;
  isEnabled?: boolean | Computed<boolean>;
}

export interface TestDetailsWithoutStepsList_Tests_Options_Scheduling_Timeframes {
  day?: number | Computed<number>;
  from?: string | Computed<string>;
  to?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Options_Scheduling {
  timeframes?: TestDetailsWithoutStepsList_Tests_Options_Scheduling_Timeframes[] | Computed<TestDetailsWithoutStepsList_Tests_Options_Scheduling_Timeframes[]>;
  timezone?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsList_Tests_Options {
  acceptSelfSigned?: boolean | Computed<boolean>;
  allowInsecure?: boolean | Computed<boolean>;
  blockedRequestPatterns?: string[] | Computed<string[]>;
  captureNetworkPayloads?: boolean | Computed<boolean>;
  checkCertificateRevocation?: boolean | Computed<boolean>;
  ci?: TestDetailsWithoutStepsList_Tests_Options_Ci | Computed<TestDetailsWithoutStepsList_Tests_Options_Ci>;
  deviceIds?: string[] | Computed<string[]>;
  disableAiaIntermediateFetching?: boolean | Computed<boolean>;
  disableCors?: boolean | Computed<boolean>;
  disableCsp?: boolean | Computed<boolean>;
  enableProfiling?: boolean | Computed<boolean>;
  enableSecurityTesting?: boolean | Computed<boolean>;
  followRedirects?: boolean | Computed<boolean>;
  httpVersion?: string | Computed<string>;
  ignoreCertificateValidation?: boolean | Computed<boolean>;
  ignoreServerCertificateError?: boolean | Computed<boolean>;
  initialNavigationTimeout?: number | Computed<number>;
  minFailureDuration?: number | Computed<number>;
  minLocationFailed?: number | Computed<number>;
  monitorName?: string | Computed<string>;
  monitorOptions?: TestDetailsWithoutStepsList_Tests_Options_MonitorOptions | Computed<TestDetailsWithoutStepsList_Tests_Options_MonitorOptions>;
  monitorPriority?: number | Computed<number>;
  noScreenshot?: boolean | Computed<boolean>;
  restrictedRoles?: string[] | Computed<string[]>;
  retry?: TestDetailsWithoutStepsList_Tests_Options_Retry | Computed<TestDetailsWithoutStepsList_Tests_Options_Retry>;
  rumSettings?: TestDetailsWithoutStepsList_Tests_Options_RumSettings | Computed<TestDetailsWithoutStepsList_Tests_Options_RumSettings>;
  scheduling?: TestDetailsWithoutStepsList_Tests_Options_Scheduling | Computed<TestDetailsWithoutStepsList_Tests_Options_Scheduling>;
  tickEvery?: number | Computed<number>;
}

export interface TestDetailsWithoutStepsList_Tests {
  config?: TestDetailsWithoutStepsList_Tests_Config | Computed<TestDetailsWithoutStepsList_Tests_Config>;
  creator?: TestDetailsWithoutStepsList_Tests_Creator | Computed<TestDetailsWithoutStepsList_Tests_Creator>;
  locations?: string[] | Computed<string[]>;
  message?: string | Computed<string>;
  monitorId?: number | Computed<number>;
  name?: string | Computed<string>;
  options?: TestDetailsWithoutStepsList_Tests_Options | Computed<TestDetailsWithoutStepsList_Tests_Options>;
  publicId?: string | Computed<string>;
  status?: string | Computed<string>;
  subtype?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  type?: string | Computed<string>;
}

export interface TestDetailsWithoutStepsListConfig {
  pageNumber?: number | Computed<number>;
  pageSize?: number | Computed<number>;
}

export interface TestDetailsWithoutStepsListAttrs {
  pageNumber: number;
  pageSize: number;
  /** Array of Synthetic tests configuration. */
  tests: TestDetailsWithoutStepsList_Tests[];
}

export const TestDetailsWithoutStepsList: DataSourceBinding<TestDetailsWithoutStepsListConfig, TestDetailsWithoutStepsListAttrs> = {
  wireType: "datadog_synthetics_test_details_without_steps_list",
  fields: {
    pageNumber: "page_number",
    pageSize: "page_size",
  },
};
