// Code generated by `ubx sdk gen` from datadog_user_response. DO NOT EDIT.
package user

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Response_User struct {
	// The access role of the user. Options are **st** (standard user), **adm** (admin user), or **ro** (read-only user).
	AccessRole any
	// The new disabled status of the user.
	Disabled any
	// The new email of the user.
	Email any
	// The user handle, must be a valid email.
	Handle any
	// Gravatar icon associated to the user.
	Icon any
	// The name of the user.
	Name any
	// Whether or not the user logged in Datadog at least once.
	Verified any
}

type ResponseConfig struct {
	// The access role of the user. Options are **st** (standard user), **adm** (admin user), or **ro** (read-only user).
	AccessRole any
	// The new disabled status of the user.
	Disabled any
	// The new email of the user.
	Email any
	// The user handle, must be a valid email.
	Handle any
	// The name of the user.
	Name any
	// path parameter, not part of the API's own resource representation
	UserHandle any
}

type ResponseAttrs struct {
	// The access role of the user. Options are **st** (standard user), **adm** (admin user), or **ro** (read-only user).
	AccessRole any
	// The new disabled status of the user.
	Disabled any
	// The new email of the user.
	Email any
	// The user handle, must be a valid email.
	Handle any
	// Gravatar icon associated to the user.
	Icon any
	// The name of the user.
	Name any
	// Create, edit, and disable users.
	User any
	// Whether or not the user logged in Datadog at least once.
	Verified any
	// path parameter, not part of the API's own resource representation
	UserHandle any
}

var Response = ubx.ResourceBinding{
	WireType: "datadog_user_response",
	Fields: ubx.FieldMap{
		"AccessRole": ubx.FieldSpec{WireName: "access_role"},
		"Disabled":   ubx.FieldSpec{WireName: "disabled"},
		"Email":      ubx.FieldSpec{WireName: "email"},
		"Handle":     ubx.FieldSpec{WireName: "handle"},
		"Name":       ubx.FieldSpec{WireName: "name"},
		"UserHandle": ubx.FieldSpec{WireName: "user_handle"},
	},
}
