// Code generated by `ubx sdk gen` from datadog_team_link_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LinkResponse_Data_Attributes {
  /** The link's label */
  label: string | Computed<string>;
  /** The link's position, used to sort links for the team */
  position?: number | Computed<number>;
  /** ID of the team the link is associated with */
  teamId?: string | Computed<string>;
  /** The URL for the link */
  url: string | Computed<string>;
}

export interface LinkResponse_Data {
  /** Team link attributes */
  attributes: LinkResponse_Data_Attributes | Computed<LinkResponse_Data_Attributes>;
  /** The team link's identifier */
  id?: string | Computed<string>;
  /** Team link type */
  type: string | Computed<string>;
}

const LinkResponse_Data_AttributesFields: FieldMap = {
  label: "label",
  position: "position",
  teamId: "team_id",
  url: "url",
};

const LinkResponse_DataFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: LinkResponse_Data_AttributesFields,
  },
  id: "id",
  type: "type",
};

export interface LinkResponseConfig {
  /** Team link create */
  data: LinkResponse_Data | Computed<LinkResponse_Data>;
  /** path parameter, not part of the API's own resource representation */
  teamId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  linkId: string | Computed<string>;
}

export interface LinkResponseAttrs {
  /** Team link create */
  data: LinkResponse_Data;
  /** path parameter, not part of the API's own resource representation */
  teamId: string;
  /** path parameter, not part of the API's own resource representation */
  linkId: string;
}

export const LinkResponse: ResourceBinding<LinkResponseConfig, LinkResponseAttrs> = {
  wireType: "datadog_team_link_response",
  fields: {
    data: {
      wireName: "data",
      kind: "object",
      fields: LinkResponse_DataFields,
    },
    teamId: "team_id",
    linkId: "link_id",
  },
};
