// Code generated by `ubx sdk gen` from datadog_due_date_rule_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DateRuleResponse_Data_Attributes_Action_DueDaysPerSeverity {
  dueInDays?: number | Computed<number>;
  severity?: string | Computed<string>;
}

export interface DateRuleResponse_Data_Attributes_Action {
  /** A list of severity-to-due-date mappings. Each severity may appear at most once. */
  dueDaysPerSeverity: DateRuleResponse_Data_Attributes_Action_DueDaysPerSeverity[] | Computed<DateRuleResponse_Data_Attributes_Action_DueDaysPerSeverity[]>;
  /** The reference point from which the due date is calculated. When `fix_available` is selected but not applicable to the finding type, `first_seen` is used instead. */
  dueFrom: string | Computed<string>;
  /** An optional description providing more context for the due date assignment. */
  reasonDescription?: string | Computed<string>;
}

export interface DateRuleResponse_Data_Attributes_Rule {
  /** The list of security finding types that the automation rule applies to. */
  findingTypes: string[] | Computed<string[]>;
  /** A search query to further filter the findings matched by this rule. The `@workflow.*` namespace and `@status` fields are not permitted. For a reference of available fields, see the [Security Findings schema documentation](https://docs.datadoghq.com/security/guide/findings-schema/). */
  query?: string | Computed<string>;
}

export interface DateRuleResponse_Data_Attributes {
  /** The action to take when the due date rule matches a finding. */
  action: DateRuleResponse_Data_Attributes_Action | Computed<DateRuleResponse_Data_Attributes_Action>;
  /** Whether the due date rule is enabled. */
  enabled?: boolean | Computed<boolean>;
  /** The name of the due date rule. */
  name: string | Computed<string>;
  /** Defines the scope of findings to which the automation rule applies. */
  rule: DateRuleResponse_Data_Attributes_Rule | Computed<DateRuleResponse_Data_Attributes_Rule>;
}

export interface DateRuleResponse_Data {
  /** Attributes for creating or updating a due date rule. */
  attributes: DateRuleResponse_Data_Attributes | Computed<DateRuleResponse_Data_Attributes>;
  /** The JSON:API type for due date rules. */
  type: string | Computed<string>;
}

const DateRuleResponse_Data_Attributes_Action_DueDaysPerSeverityFields: FieldMap = {
  dueInDays: "due_in_days",
  severity: "severity",
};

const DateRuleResponse_Data_Attributes_ActionFields: FieldMap = {
  dueDaysPerSeverity: {
    wireName: "due_days_per_severity",
    kind: "list",
    fields: DateRuleResponse_Data_Attributes_Action_DueDaysPerSeverityFields,
  },
  dueFrom: "due_from",
  reasonDescription: "reason_description",
};

const DateRuleResponse_Data_Attributes_RuleFields: FieldMap = {
  findingTypes: "finding_types",
  query: "query",
};

const DateRuleResponse_Data_AttributesFields: FieldMap = {
  action: {
    wireName: "action",
    kind: "object",
    fields: DateRuleResponse_Data_Attributes_ActionFields,
  },
  enabled: "enabled",
  name: "name",
  rule: {
    wireName: "rule",
    kind: "object",
    fields: DateRuleResponse_Data_Attributes_RuleFields,
  },
};

const DateRuleResponse_DataFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: DateRuleResponse_Data_AttributesFields,
  },
  type: "type",
};

export interface DateRuleResponseConfig {
  /** The data object for a due date rule create or update request. */
  data: DateRuleResponse_Data | Computed<DateRuleResponse_Data>;
  /** path parameter, not part of the API's own resource representation */
  ruleId: string | Computed<string>;
}

export interface DateRuleResponseAttrs {
  /** The data object for a due date rule create or update request. */
  data: DateRuleResponse_Data;
  /** path parameter, not part of the API's own resource representation */
  ruleId: string;
}

export const DateRuleResponse: ResourceBinding<DateRuleResponseConfig, DateRuleResponseAttrs> = {
  wireType: "datadog_due_date_rule_response",
  fields: {
    data: {
      wireName: "data",
      kind: "object",
      fields: DateRuleResponse_DataFields,
    },
    ruleId: "rule_id",
  },
};
