# Code generated by `ubx sdk gen` from datadog_dorafailure_fetch_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FetchResponse_Data_Attributes:
    # Minimum timestamp for requested events.
    from_: Any = None
    # Maximum number of events in the response.
    limit: Any = None
    # Search query with event platform syntax.
    query: Any = None
    # Sort order (prefixed with `-` for descending).
    sort: Any = None
    # Maximum timestamp for requested events.
    to: Any = None

@dataclasses.dataclass
class FetchResponse_Data:
    # Attributes to get a list of incidents.
    attributes: Any = None
    # The definition of `DORAListFailuresRequestDataType` object.
    type: Any = None

_FetchResponse_Data_AttributesFields = {
    "from_": ubx.FieldSpec(wire_name="from"),
    "limit": ubx.FieldSpec(wire_name="limit"),
    "query": ubx.FieldSpec(wire_name="query"),
    "sort": ubx.FieldSpec(wire_name="sort"),
    "to": ubx.FieldSpec(wire_name="to"),
}

_FetchResponse_DataFields = {
    "attributes": ubx.FieldSpec(
        wire_name="attributes",
        kind="object",
        fields=_FetchResponse_Data_AttributesFields,
    ),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class FetchResponseConfig:
    # The JSON:API data.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    failure_id: Any = None

@dataclasses.dataclass
class FetchResponseAttrs:
    # The JSON:API data.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    failure_id: Any = None

FetchResponse = ubx.ResourceBinding(
    wire_type="datadog_dorafailure_fetch_response",
    fields={
        "data": ubx.FieldSpec(
            wire_name="data",
            kind="object",
            fields=_FetchResponse_DataFields,
        ),
        "failure_id": ubx.FieldSpec(wire_name="failure_id"),
    },
)
