// Code generated by `ubx sdk gen` from datadog_csm_agentless_host_facets_response. DO NOT EDIT.
package csm

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AgentlessHostFacetsResponse_Data_Attributes struct {
	Bounded any
	Bundled any
	BundledAndUsed any
	DefaultValues any
	Description any
	Editable any
	FacetType any
	Groups any
	Name any
	Path any
	Source any
	Type any
	Values any
}

type AgentlessHostFacetsResponse_Data struct {
	Attributes any
	Id any
	Type any
}

type AgentlessHostFacetsResponseConfig struct {
}

type AgentlessHostFacetsResponseAttrs struct {
	// The list of available facets for agentless hosts.
	Data any
}

var AgentlessHostFacetsResponse = ubx.DataSourceBinding{
	WireType: "datadog_csm_agentless_host_facets_response",
	Fields: ubx.FieldMap{
	},
}
