// Code generated by `ubx sdk gen` from datadog_csm_serverless_coverage_analysis_response. DO NOT EDIT.
package csm

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ServerlessCoverageAnalysisResponse_Data_Attributes_CwsCoverage struct {
	// The number of fully configured resources.
	ConfiguredResourcesCount any
	// The coverage percentage.
	Coverage any
	// The number of partially configured resources.
	PartiallyConfiguredResourcesCount any
	// The total number of resources.
	TotalResourcesCount any
}

type ServerlessCoverageAnalysisResponse_Data_Attributes struct {
	// CSM Coverage Analysis.
	CwsCoverage any
	// The ID of your organization.
	OrgId any
	// CSM Coverage Analysis.
	TotalCoverage any
}

type ServerlessCoverageAnalysisResponse_Data struct {
	// CSM Serverless Resources Coverage Analysis attributes.
	Attributes any
	// The ID of your organization.
	Id any
	// The type of the resource. The value should always be `get_serverless_coverage_analysis_response_public_v0`.
	Type any
}

type ServerlessCoverageAnalysisResponseConfig struct {
}

type ServerlessCoverageAnalysisResponseAttrs struct {
	// CSM Serverless Resources Coverage Analysis data.
	Data any
}

var ServerlessCoverageAnalysisResponse = ubx.DataSourceBinding{
	WireType: "datadog_csm_serverless_coverage_analysis_response",
	Fields:   ubx.FieldMap{},
}
