# Code generated by `ubx sdk gen` from datadog_auth_nmappings_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class NmappingsResponse_Data_Attributes:
    attribute_key: Any = None
    attribute_value: Any = None
    created_at: Any = None
    modified_at: Any = None
    saml_assertion_attribute_id: Any = None

@dataclasses.dataclass
class NmappingsResponse_Data_Relationships_Role_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class NmappingsResponse_Data_Relationships_Role:
    data: Any = None

@dataclasses.dataclass
class NmappingsResponse_Data_Relationships:
    role: Any = None
    saml_assertion_attribute: Any = None
    team: Any = None

@dataclasses.dataclass
class NmappingsResponse_Data:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class NmappingsResponse_Included_Attributes:
    attribute_key: Any = None
    attribute_value: Any = None

@dataclasses.dataclass
class NmappingsResponse_Included_Relationships_Permissions:
    data: Any = None

@dataclasses.dataclass
class NmappingsResponse_Included_Relationships:
    permissions: Any = None

@dataclasses.dataclass
class NmappingsResponse_Included:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class NmappingsResponse_Meta_Page:
    # Total count.
    total_count: Any = None
    # Total count of elements matched by the filter.
    total_filtered_count: Any = None

@dataclasses.dataclass
class NmappingsResponse_Meta:
    # Pagination object.
    page: Any = None

@dataclasses.dataclass
class NmappingsResponseConfig:
    filter: Any = None
    # The type of resource being mapped to.
    resource_type: Any = None
    # Sorting options for AuthN Mappings.
    sort: Any = None

@dataclasses.dataclass
class NmappingsResponseAttrs:
    # Array of returned AuthN Mappings.
    data: Any = None
    filter: Any = None
    # Included data in the AuthN Mapping response.
    included: Any = None
    # Object describing meta attributes of response.
    meta: Any = None
    # The type of resource being mapped to.
    resource_type: Any = None
    # Sorting options for AuthN Mappings.
    sort: Any = None

NmappingsResponse = ubx.DataSourceBinding(
    wire_type="datadog_auth_nmappings_response",
    fields={
        "filter": ubx.FieldSpec(wire_name="filter"),
        "resource_type": ubx.FieldSpec(wire_name="resource_type"),
        "sort": ubx.FieldSpec(wire_name="sort"),
    },
)
