// Code generated by `ubx sdk gen` from datadog_seat_user_data_list. DO NOT EDIT.
package seat

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type UserDataList_Data_Attributes struct {
	AssignedAt any
	Email any
	Name any
}

type UserDataList_Data struct {
	Attributes any
	Id any
	Type any
}

type UserDataList_Meta struct {
	// The cursor for the seat users.
	Cursor any
	// The limit for the seat users.
	Limit any
	// The next cursor for the seat users.
	NextCursor any
}

type UserDataListConfig struct {
	ProductCode any
}

type UserDataListAttrs struct {
	// The list of seat users.
	Data any
	// Pagination metadata for the seat users list response.
	Meta any
	ProductCode any
}

var UserDataList = ubx.DataSourceBinding{
	WireType: "datadog_seat_user_data_list",
	Fields: ubx.FieldMap{
		"ProductCode": ubx.FieldSpec{WireName: "product_code"},
	},
}
