# Code generated by `ubx sdk gen` from datadog_application_security_waf_exclusion_filter_resource. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SecurityWafExclusionFilterResource_Data_Attributes_Metadata:
    added_at: Any = None
    added_by: Any = None
    added_by_name: Any = None
    modified_at: Any = None
    modified_by: Any = None
    modified_by_name: Any = None

@dataclasses.dataclass
class SecurityWafExclusionFilterResource_Data_Attributes_RulesTarget_Tags:
    category: Any = None
    type: Any = None

@dataclasses.dataclass
class SecurityWafExclusionFilterResource_Data_Attributes_RulesTarget:
    rule_id: Any = None
    tags: Any = None

@dataclasses.dataclass
class SecurityWafExclusionFilterResource_Data_Attributes_Scope:
    env: Any = None
    service: Any = None

@dataclasses.dataclass
class SecurityWafExclusionFilterResource_Data_Attributes:
    description: Any = None
    enabled: Any = None
    event_query: Any = None
    ip_list: Any = None
    metadata: Any = None
    on_match: Any = None
    parameters: Any = None
    path_glob: Any = None
    rules_target: Any = None
    scope: Any = None
    search_query: Any = None

@dataclasses.dataclass
class SecurityWafExclusionFilterResource_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class SecurityWafExclusionFilterResourceConfig:
    pass

@dataclasses.dataclass
class SecurityWafExclusionFilterResourceAttrs:
    # A list of WAF exclusion filters.
    data: Any = None

SecurityWafExclusionFilterResource = ubx.DataSourceBinding(
    wire_type="datadog_application_security_waf_exclusion_filter_resource",
    fields={
    },
)
