# Code generated by `ubx sdk gen` from datadog_slack_user_binding_data. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class UserBindingData_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class UserBindingDataConfig:
    user_uuid: Any = None

@dataclasses.dataclass
class UserBindingDataAttrs:
    # An array of Slack user bindings.
    data: Any = None
    user_uuid: Any = None

UserBindingData = ubx.DataSourceBinding(
    wire_type="datadog_slack_user_binding_data",
    fields={
        "user_uuid": ubx.FieldSpec(wire_name="user_uuid"),
    },
)
