// Code generated by `ubx sdk gen` from datadog_case_view_response. DO NOT EDIT.
package case_

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ViewResponse_Data_Attributes struct {
	// The name of the view.
	Name any
	// The identifier of a notification rule linked to this view. When set, users subscribed to the view receive alerts for matching cases.
	NpRuleId any
	// The UUID of the project this view belongs to. Views are scoped to a single project.
	ProjectId any
	// The query used to filter cases in this view.
	Query any
}

type ViewResponse_Data struct {
	// Attributes required to create a case view.
	Attributes any
	// JSON:API resource type for case views.
	Type any
}

var ViewResponse_Data_AttributesFields = ubx.FieldMap{
		"Name": ubx.FieldSpec{WireName: "name"},
		"NpRuleId": ubx.FieldSpec{WireName: "np_rule_id"},
		"ProjectId": ubx.FieldSpec{WireName: "project_id"},
		"Query": ubx.FieldSpec{WireName: "query"},
	}

var ViewResponse_DataFields = ubx.FieldMap{
		"Attributes": ubx.FieldSpec{
			WireName: "attributes",
			Kind: "object",
			Fields: ViewResponse_Data_AttributesFields,
		},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

type ViewResponseConfig struct {
	// Data object for creating a case view.
	Data any
	// path parameter, not part of the API's own resource representation
	ViewId any
}

type ViewResponseAttrs struct {
	// Data object for creating a case view.
	Data any
	// path parameter, not part of the API's own resource representation
	ViewId any
}

var ViewResponse = ubx.ResourceBinding{
	WireType: "datadog_case_view_response",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind: "object",
			Fields: ViewResponse_DataFields,
		},
		"ViewId": ubx.FieldSpec{WireName: "view_id"},
	},
}
