// Code generated by `ubx sdk gen` from datadog_awsnamespaces_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Response_Data_Attributes {
  /** AWS CloudWatch namespace. */
  namespaces: string[] | Computed<string[]>;
}

export interface Response_Data {
  /** AWS Namespaces response attributes. */
  attributes?: Response_Data_Attributes | Computed<Response_Data_Attributes>;
  /** The `AWSNamespacesResponseData` `id`. */
  id: string | Computed<string>;
  /** The `AWSNamespacesResponseData` `type`. */
  type: string | Computed<string>;
}

export interface ResponseConfig {
}

export interface ResponseAttrs {
  /** AWS Namespaces response data. */
  data: Response_Data;
}

export const Response: DataSourceBinding<ResponseConfig, ResponseAttrs> = {
  wireType: "datadog_awsnamespaces_response",
  fields: {
  },
};
