# Code generated by `ubx sdk gen` from datadog_model_lab_project_data. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LabProjectData_Data_Attributes_Tags:
    key: Any = None
    value: Any = None

@dataclasses.dataclass
class LabProjectData_Data_Attributes:
    artifact_storage_location: Any = None
    created_at: Any = None
    deleted_at: Any = None
    description: Any = None
    external_url: Any = None
    is_starred: Any = None
    name: Any = None
    owner_id: Any = None
    tags: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class LabProjectData_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class LabProjectData_Links:
    # Link to the first page.
    first: Any = None
    # Link to the last page.
    last: Any = None
    # Link to the next page.
    next: Any = None
    # Link to the previous page.
    prev: Any = None
    # Link to the current page.
    self: Any = None

@dataclasses.dataclass
class LabProjectData_Meta_Page:
    # The first page number.
    first_number: Any = None
    # The last page number.
    last_number: Any = None
    # The next page number.
    next_number: Any = None
    # The current page number.
    number: Any = None
    # The previous page number.
    prev_number: Any = None
    # The number of items per page.
    size: Any = None
    # The total number of items.
    total: Any = None
    # The pagination type.
    type: Any = None

@dataclasses.dataclass
class LabProjectData_Meta:
    # Pagination details for a list response.
    page: Any = None

@dataclasses.dataclass
class LabProjectDataConfig:
    filter: Any = None
    sort: Any = None

@dataclasses.dataclass
class LabProjectDataAttrs:
    # The list of projects.
    data: Any = None
    filter: Any = None
    # Pagination links for navigating list responses.
    links: Any = None
    # Pagination metadata for a list response.
    meta: Any = None
    sort: Any = None

LabProjectData = ubx.DataSourceBinding(
    wire_type="datadog_model_lab_project_data",
    fields={
        "filter": ubx.FieldSpec(wire_name="filter"),
        "sort": ubx.FieldSpec(wire_name="sort"),
    },
)
