# Code generated by `ubx sdk gen` from datadog_model_lab_project_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LabProjectResponse_Data_Attributes_Tags:
    key: Any = None
    value: Any = None

@dataclasses.dataclass
class LabProjectResponse_Data_Attributes:
    # The storage location for project artifacts.
    artifact_storage_location: Any = None
    # The date and time the project was created.
    created_at: Any = None
    # The date and time the project was soft-deleted.
    deleted_at: Any = None
    # A description of the project.
    description: Any = None
    # An optional external URL associated with the project.
    external_url: Any = None
    # Whether the project is starred by the current user.
    is_starred: Any = None
    # The name of the project.
    name: Any = None
    # The UUID of the project owner.
    owner_id: Any = None
    # The list of tags associated with the project.
    tags: Any = None
    # The date and time the project was last updated.
    updated_at: Any = None

@dataclasses.dataclass
class LabProjectResponse_Data:
    # Attributes of a Model Lab project.
    attributes: Any = None
    # The unique identifier of the project.
    id: Any = None
    # The JSON:API type for a Model Lab project resource.
    type: Any = None

@dataclasses.dataclass
class LabProjectResponseConfig:
    project_id: Any = None

@dataclasses.dataclass
class LabProjectResponseAttrs:
    # A Model Lab project JSON:API resource object.
    data: Any = None
    project_id: Any = None

LabProjectResponse = ubx.DataSourceBinding(
    wire_type="datadog_model_lab_project_response",
    fields={
        "project_id": ubx.FieldSpec(wire_name="project_id"),
    },
)
