// Code generated by `ubx sdk gen` from datadog_sast_ruleset_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RulesetData_Data_Attributes_Rules_Arguments {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface RulesetData_Data_Attributes_Rules_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RulesetData_Data_Attributes_Rules_Tests {
  annotationCount?: number | Computed<number>;
  code?: string | Computed<string>;
  filename?: string | Computed<string>;
}

export interface RulesetData_Data_Attributes_Rules {
  arguments?: RulesetData_Data_Attributes_Rules_Arguments[] | Computed<RulesetData_Data_Attributes_Rules_Arguments[]>;
  category?: string | Computed<string>;
  checksum?: string | Computed<string>;
  code?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  cve?: string | Computed<string>;
  cwe?: string | Computed<string>;
  data?: RulesetData_Data_Attributes_Rules_Data | Computed<RulesetData_Data_Attributes_Rules_Data>;
  description?: string | Computed<string>;
  documentationUrl?: string | Computed<string>;
  entityChecked?: string | Computed<string>;
  isPublished?: boolean | Computed<boolean>;
  isTesting?: boolean | Computed<boolean>;
  language?: string | Computed<string>;
  lastUpdatedAt?: string | Computed<string>;
  lastUpdatedBy?: string | Computed<string>;
  name?: string | Computed<string>;
  regex?: string | Computed<string>;
  severity?: string | Computed<string>;
  shortDescription?: string | Computed<string>;
  shouldUseAiFix?: boolean | Computed<boolean>;
  tests?: RulesetData_Data_Attributes_Rules_Tests[] | Computed<RulesetData_Data_Attributes_Rules_Tests[]>;
  treeSitterQuery?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RulesetData_Data_Attributes {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  rules?: RulesetData_Data_Attributes_Rules[] | Computed<RulesetData_Data_Attributes_Rules[]>;
  shortDescription?: string | Computed<string>;
}

export interface RulesetData_Data {
  attributes?: RulesetData_Data_Attributes | Computed<RulesetData_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RulesetDataConfig {
}

export interface RulesetDataAttrs {
  /** The list of SAST rulesets returned in the response. */
  data: RulesetData_Data[];
}

export const RulesetData: DataSourceBinding<RulesetDataConfig, RulesetDataAttrs> = {
  wireType: "datadog_sast_ruleset_data",
  fields: {
  },
};
