// Code generated by `ubx sdk gen` from datadog_google_chat_organization_data_list. DO NOT EDIT.
package google

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ChatOrganizationDataList_Data_Attributes struct {
	DomainId   any
	DomainName any
}

type ChatOrganizationDataList_Data_Relationships_DelegatedUser_Data struct {
	Id   any
	Type any
}

type ChatOrganizationDataList_Data_Relationships_DelegatedUser struct {
	Data any
}

type ChatOrganizationDataList_Data_Relationships struct {
	DelegatedUser any
}

type ChatOrganizationDataList_Data struct {
	Attributes    any
	Id            any
	Relationships any
	Type          any
}

type ChatOrganizationDataListConfig struct {
}

type ChatOrganizationDataListAttrs struct {
	// An array of Google Chat organization bindings.
	Data any
}

var ChatOrganizationDataList = ubx.DataSourceBinding{
	WireType: "datadog_google_chat_organization_data_list",
	Fields:   ubx.FieldMap{},
}
