// Code generated by `ubx sdk gen` from datadog_playlist_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Data_Data_Attributes_CreatedBy {
  handle?: string | Computed<string>;
  icon?: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface Data_Data_Attributes {
  createdAt?: string | Computed<string>;
  createdBy?: Data_Data_Attributes_CreatedBy | Computed<Data_Data_Attributes_CreatedBy>;
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  sessionCount?: number | Computed<number>;
  updatedAt?: string | Computed<string>;
}

export interface Data_Data {
  attributes?: Data_Data_Attributes | Computed<Data_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface DataConfig {
}

export interface DataAttrs {
  /** Array of playlist data objects. */
  data: Data_Data[];
}

export const Data: DataSourceBinding<DataConfig, DataAttrs> = {
  wireType: "datadog_playlist_data",
  fields: {
  },
};
