# Code generated by `ubx sdk gen` from datadog_historical_metrics_configuration_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MetricsConfigurationResponse_Data_Attributes:
    # Timestamp when historical metrics ingestion was enabled for the metric.
    created_at: Any = None

@dataclasses.dataclass
class MetricsConfigurationResponse_Data:
    # Attributes of a historical metrics configuration.
    attributes: Any = None
    # The metric name, used as the resource ID.
    id: Any = None
    # The historical metrics configuration resource type.
    type: Any = None

_MetricsConfigurationResponse_Data_AttributesFields = {
    "created_at": ubx.FieldSpec(wire_name="created_at"),
}

_MetricsConfigurationResponse_DataFields = {
    "attributes": ubx.FieldSpec(
        wire_name="attributes",
        kind="object",
        fields=_MetricsConfigurationResponse_Data_AttributesFields,
    ),
    "id": ubx.FieldSpec(wire_name="id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class MetricsConfigurationResponseConfig:
    # Data object for enabling historical metrics ingestion for a metric.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    metric_name: Any = None

@dataclasses.dataclass
class MetricsConfigurationResponseAttrs:
    # Data object for enabling historical metrics ingestion for a metric.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    metric_name: Any = None

MetricsConfigurationResponse = ubx.ResourceBinding(
    wire_type="datadog_historical_metrics_configuration_response",
    fields={
        "data": ubx.FieldSpec(
            wire_name="data",
            kind="object",
            fields=_MetricsConfigurationResponse_DataFields,
        ),
        "metric_name": ubx.FieldSpec(wire_name="metric_name"),
    },
)
