// Code generated by `ubx sdk gen` from datadog_service_now_user_data_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface NowUserDataList_Data_Attributes {
  email?: string | Computed<string>;
  fullName?: string | Computed<string>;
  instanceId?: string | Computed<string>;
  userName?: string | Computed<string>;
  userSysId?: string | Computed<string>;
}

export interface NowUserDataList_Data {
  attributes?: NowUserDataList_Data_Attributes | Computed<NowUserDataList_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface NowUserDataListConfig {
  instanceId: string | Computed<string>;
}

export interface NowUserDataListAttrs {
  /** Array of ServiceNow user data objects */
  data: NowUserDataList_Data[];
  instanceId: string;
}

export const NowUserDataList: DataSourceBinding<NowUserDataListConfig, NowUserDataListAttrs> = {
  wireType: "datadog_service_now_user_data_list",
  fields: {
    instanceId: "instance_id",
  },
};
