// Code generated by `ubx sdk gen` from datadog_org_authorized_client_data_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AuthorizedClientDataList_Data_Attributes {
  disabled?: boolean | Computed<boolean>;
  lastExercised?: string | Computed<string>;
  userCount?: number | Computed<number>;
}

export interface AuthorizedClientDataList_Data_Relationships_Oauth2Client_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AuthorizedClientDataList_Data_Relationships_Oauth2Client {
  data?: AuthorizedClientDataList_Data_Relationships_Oauth2Client_Data | Computed<AuthorizedClientDataList_Data_Relationships_Oauth2Client_Data>;
}

export interface AuthorizedClientDataList_Data_Relationships_UserAuthorizedClients_Links {
  related?: string | Computed<string>;
}

export interface AuthorizedClientDataList_Data_Relationships_UserAuthorizedClients {
  data?: AuthorizedClientDataList_Data_Relationships_Oauth2Client_Data[] | Computed<AuthorizedClientDataList_Data_Relationships_Oauth2Client_Data[]>;
  links?: AuthorizedClientDataList_Data_Relationships_UserAuthorizedClients_Links | Computed<AuthorizedClientDataList_Data_Relationships_UserAuthorizedClients_Links>;
}

export interface AuthorizedClientDataList_Data_Relationships {
  oauth2Client?: AuthorizedClientDataList_Data_Relationships_Oauth2Client | Computed<AuthorizedClientDataList_Data_Relationships_Oauth2Client>;
  userAuthorizedClients?: AuthorizedClientDataList_Data_Relationships_UserAuthorizedClients | Computed<AuthorizedClientDataList_Data_Relationships_UserAuthorizedClients>;
}

export interface AuthorizedClientDataList_Data {
  attributes?: AuthorizedClientDataList_Data_Attributes | Computed<AuthorizedClientDataList_Data_Attributes>;
  id?: string | Computed<string>;
  relationships?: AuthorizedClientDataList_Data_Relationships | Computed<AuthorizedClientDataList_Data_Relationships>;
  type?: string | Computed<string>;
}

export interface AuthorizedClientDataList_Meta_Page {
  /** Total count. */
  totalCount?: number | Computed<number>;
  /** Total count of elements matched by the filter. */
  totalFilteredCount?: number | Computed<number>;
}

export interface AuthorizedClientDataList_Meta {
  /** Pagination object. */
  page?: AuthorizedClientDataList_Meta_Page | Computed<AuthorizedClientDataList_Meta_Page>;
}

export interface AuthorizedClientDataListConfig {
  filter?: string | Computed<string>;
  include?: string | Computed<string>;
  sort?: string | Computed<string>;
}

export interface AuthorizedClientDataListAttrs {
  /** List of org authorized client data objects. */
  data: AuthorizedClientDataList_Data[];
  filter: string;
  include: string;
  /** Object describing meta attributes of response. */
  meta: AuthorizedClientDataList_Meta;
  sort: string;
}

export const AuthorizedClientDataList: DataSourceBinding<AuthorizedClientDataListConfig, AuthorizedClientDataListAttrs> = {
  wireType: "datadog_org_authorized_client_data_list",
  fields: {
    filter: "filter",
    include: "include",
    sort: "sort",
  },
};
