// Code generated by `ubx sdk gen` from datadog_org_group_membership_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface GroupMembershipData_Data_Attributes {
  createdAt?: string | Computed<string>;
  modifiedAt?: string | Computed<string>;
  orgName?: string | Computed<string>;
  orgSite?: string | Computed<string>;
  orgUuid?: string | Computed<string>;
}

export interface GroupMembershipData_Data_Relationships_OrgGroup_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface GroupMembershipData_Data_Relationships_OrgGroup {
  data?: GroupMembershipData_Data_Relationships_OrgGroup_Data | Computed<GroupMembershipData_Data_Relationships_OrgGroup_Data>;
}

export interface GroupMembershipData_Data_Relationships {
  orgGroup?: GroupMembershipData_Data_Relationships_OrgGroup | Computed<GroupMembershipData_Data_Relationships_OrgGroup>;
}

export interface GroupMembershipData_Data {
  attributes?: GroupMembershipData_Data_Attributes | Computed<GroupMembershipData_Data_Attributes>;
  id?: string | Computed<string>;
  relationships?: GroupMembershipData_Data_Relationships | Computed<GroupMembershipData_Data_Relationships>;
  type?: string | Computed<string>;
}

export interface GroupMembershipData_Links {
  /** Link to the first page. */
  first?: string | Computed<string>;
  /** Link to the last page. */
  last?: string | Computed<string>;
  /** Link to the next page. */
  next?: string | Computed<string>;
  /** Link to the previous page. */
  prev?: string | Computed<string>;
  /** Link to the current page. */
  self?: string | Computed<string>;
}

export interface GroupMembershipData_Meta_Page {
  /** First page number. */
  firstNumber?: number | Computed<number>;
  /** Last page number. */
  lastNumber?: number | Computed<number>;
  /** Next page number. */
  nextNumber?: number | Computed<number>;
  /** Page number. */
  number?: number | Computed<number>;
  /** Previous page number. */
  prevNumber?: number | Computed<number>;
  /** Page size. */
  size?: number | Computed<number>;
  /** Total number of results. */
  total?: number | Computed<number>;
  /** Pagination type. */
  type?: string | Computed<string>;
}

export interface GroupMembershipData_Meta {
  /** Page-based pagination details for org group list responses. */
  page?: GroupMembershipData_Meta_Page | Computed<GroupMembershipData_Meta_Page>;
}

export interface GroupMembershipDataConfig {
  /** Field to sort memberships by. */
  sort?: string | Computed<string>;
}

export interface GroupMembershipDataAttrs {
  /** An array of org group memberships. */
  data: GroupMembershipData_Data[];
  /** Pagination links for navigating between pages of an org group list response. */
  links: GroupMembershipData_Links;
  /** Pagination metadata for org group list responses. */
  meta: GroupMembershipData_Meta;
  /** Field to sort memberships by. */
  sort: string;
}

export const GroupMembershipData: DataSourceBinding<GroupMembershipDataConfig, GroupMembershipDataAttrs> = {
  wireType: "datadog_org_group_membership_data",
  fields: {
    sort: "sort",
  },
};
