// Code generated by `ubx sdk gen` from datadog_usage_rum_sessions_response. DO NOT EDIT.
package usage

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RumSessionsResponse_Usage struct {
	Hour any
	OrgName any
	PublicId any
	ReplaySessionCount any
	SessionCount any
	SessionCountAndroid any
	SessionCountFlutter any
	SessionCountIos any
	SessionCountReactnative any
}

type RumSessionsResponseConfig struct {
	EndHr any
	StartHr any
	Type any
}

type RumSessionsResponseAttrs struct {
	EndHr any
	StartHr any
	Type any
	// Get hourly usage for RUM sessions.
	Usage any
}

var RumSessionsResponse = ubx.DataSourceBinding{
	WireType: "datadog_usage_rum_sessions_response",
	Fields: ubx.FieldMap{
		"EndHr": ubx.FieldSpec{WireName: "end_hr"},
		"StartHr": ubx.FieldSpec{WireName: "start_hr"},
		"Type": ubx.FieldSpec{WireName: "type"},
	},
}
