# Code generated by `ubx sdk gen` from datadog_ociconfigs_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Response_Data_Attributes:
    account_id: Any = None
    created_at: Any = None
    error_messages: Any = None
    status: Any = None
    status_updated_at: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class Response_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class ResponseConfig:
    pass

@dataclasses.dataclass
class ResponseAttrs:
    # An OCI config.
    data: Any = None

Response = ubx.DataSourceBinding(
    wire_type="datadog_ociconfigs_response",
    fields={
    },
)
