// Code generated by `ubx sdk gen` from datadog_dem_recommended_test_data_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RecommendedTestDataList_Data_Attributes {
  config?: Record<string, unknown> | Computed<Record<string, unknown>>;
  createdAt?: string | Computed<string>;
  name?: string | Computed<string>;
  resultId?: string | Computed<string>;
  sessionId?: string | Computed<string>;
  source?: string | Computed<string>;
  type?: string | Computed<string>;
  variantId?: string | Computed<string>;
}

export interface RecommendedTestDataList_Data {
  attributes?: RecommendedTestDataList_Data_Attributes | Computed<RecommendedTestDataList_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RecommendedTestDataListConfig {
  journeyId: string | Computed<string>;
}

export interface RecommendedTestDataListAttrs {
  /** Recommended synthetic tests for a DEM journey. */
  data: RecommendedTestDataList_Data[];
  journeyId: string;
}

export const RecommendedTestDataList: DataSourceBinding<RecommendedTestDataListConfig, RecommendedTestDataListAttrs> = {
  wireType: "datadog_dem_recommended_test_data_list",
  fields: {
    journeyId: "journey_id",
  },
};
