# Code generated by `ubx sdk gen` from datadog_commitments_savings_timeseries_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SavingsTimeseriesResponse_ActualCost_Unit:
    # The unit family (for example, percentage or money).
    family: Any = None
    # The unit identifier.
    id: Any = None
    # The unit name (for example, percent or dollar).
    name: Any = None
    # The plural form of the unit name.
    plural: Any = None
    # The scale factor for the unit.
    scale_factor: Any = None
    # The abbreviated unit name (for example, % or $).
    short_name: Any = None

@dataclasses.dataclass
class SavingsTimeseriesResponse_ActualCost:
    # Timeseries data as a map of series names to their corresponding value arrays.
    series: Any = None
    # Unix timestamps in seconds for the timeseries data points.
    times: Any = None
    # Unit metadata for a numeric metric.
    unit: Any = None

@dataclasses.dataclass
class SavingsTimeseriesResponseConfig:
    end: Any = None
    filter_by: Any = None
    product: Any = None
    # Cloud provider for commitment programs.
    provider: Any = None
    start: Any = None

@dataclasses.dataclass
class SavingsTimeseriesResponseAttrs:
    # A timeseries metric containing timestamps, series values, and optional unit metadata.
    actual_cost: Any = None
    # A timeseries metric containing timestamps, series values, and optional unit metadata.
    effective_savings_rate: Any = None
    end: Any = None
    filter_by: Any = None
    # A timeseries metric containing timestamps, series values, and optional unit metadata.
    on_demand_equivalent_cost: Any = None
    product: Any = None
    # Cloud provider for commitment programs.
    provider: Any = None
    # A timeseries metric containing timestamps, series values, and optional unit metadata.
    realized_savings: Any = None
    start: Any = None

SavingsTimeseriesResponse = ubx.DataSourceBinding(
    wire_type="datadog_commitments_savings_timeseries_response",
    fields={
        "end": ubx.FieldSpec(wire_name="end"),
        "filter_by": ubx.FieldSpec(wire_name="filter_by"),
        "product": ubx.FieldSpec(wire_name="product"),
        "provider": ubx.FieldSpec(wire_name="provider"),
        "start": ubx.FieldSpec(wire_name="start"),
    },
)
