// Code generated by `ubx sdk gen` from datadog_single_aggregated_dns_response_data_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AggregatedDnsResponseDataList_Data_Attributes_GroupBys {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface AggregatedDnsResponseDataList_Data_Attributes_Metrics {
  key?: string | Computed<string>;
  value?: number | Computed<number>;
}

export interface AggregatedDnsResponseDataList_Data_Attributes {
  groupBys?: AggregatedDnsResponseDataList_Data_Attributes_GroupBys[] | Computed<AggregatedDnsResponseDataList_Data_Attributes_GroupBys[]>;
  metrics?: AggregatedDnsResponseDataList_Data_Attributes_Metrics[] | Computed<AggregatedDnsResponseDataList_Data_Attributes_Metrics[]>;
}

export interface AggregatedDnsResponseDataList_Data {
  attributes?: AggregatedDnsResponseDataList_Data_Attributes | Computed<AggregatedDnsResponseDataList_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AggregatedDnsResponseDataListConfig {
  from?: number | Computed<number>;
  groupBy?: string | Computed<string>;
  limit?: number | Computed<number>;
  query?: string | Computed<string>;
  tags?: string | Computed<string>;
  to?: number | Computed<number>;
}

export interface AggregatedDnsResponseDataListAttrs {
  /** Array of aggregated DNS objects. */
  data: AggregatedDnsResponseDataList_Data[];
  from: number;
  groupBy: string;
  limit: number;
  query: string;
  tags: string;
  to: number;
}

export const AggregatedDnsResponseDataList: DataSourceBinding<AggregatedDnsResponseDataListConfig, AggregatedDnsResponseDataListAttrs> = {
  wireType: "datadog_single_aggregated_dns_response_data_list",
  fields: {
    from: "from",
    groupBy: "group_by",
    limit: "limit",
    query: "query",
    tags: "tags",
    to: "to",
  },
};
