// Code generated by `ubx sdk gen` from datadog_default_rulesets_per_language_response. DO NOT EDIT.
package default_

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RulesetsPerLanguageResponse_Data_Attributes struct {
	// The list of default ruleset names for the specified programming language.
	Rulesets any
}

type RulesetsPerLanguageResponse_Data struct {
	// The attributes of the default rulesets per language response, containing the list of default ruleset names.
	Attributes any
	// The language identifier used as the resource identifier.
	Id any
	// Default rulesets per language resource type.
	Type any
}

type RulesetsPerLanguageResponseConfig struct {
	Language any
}

type RulesetsPerLanguageResponseAttrs struct {
	// The primary data object in the default rulesets per language response.
	Data     any
	Language any
}

var RulesetsPerLanguageResponse = ubx.DataSourceBinding{
	WireType: "datadog_default_rulesets_per_language_response",
	Fields: ubx.FieldMap{
		"Language": ubx.FieldSpec{WireName: "language"},
	},
}
