// Code generated by `ubx sdk gen` from datadog_monitor_group_search_response. DO NOT EDIT.
package monitor

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GroupSearchResponse_Counts_Status struct {
	Count any
	Name any
}

type GroupSearchResponse_Counts struct {
	// Search facets.
	Status any
	// Search facets.
	Type any
}

type GroupSearchResponse_Groups struct {
	Group any
	GroupTags any
	LastNodataTs any
	LastTriggeredTs any
	MonitorId any
	MonitorName any
	Status any
}

type GroupSearchResponse_Metadata struct {
	// The page to start paginating from.
	Page any
	// The number of pages.
	PageCount any
	// The number of monitors to return per page.
	PerPage any
	// The total number of monitors.
	TotalCount any
}

type GroupSearchResponseConfig struct {
	Page any
	PerPage any
	Query any
	Sort any
}

type GroupSearchResponseAttrs struct {
	// The counts of monitor groups per different criteria.
	Counts any
	// The list of found monitor groups.
	Groups any
	// Metadata about the response.
	Metadata any
	Page any
	PerPage any
	Query any
	Sort any
}

var GroupSearchResponse = ubx.DataSourceBinding{
	WireType: "datadog_monitor_group_search_response",
	Fields: ubx.FieldMap{
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
		"Query": ubx.FieldSpec{WireName: "query"},
		"Sort": ubx.FieldSpec{WireName: "sort"},
	},
}
