// Code generated by `ubx sdk gen` from datadog_get_action_connection_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ActionConnectionResponse_Data_Attributes_Integration_Credentials {
  accountId?: string | Computed<string>;
  externalId?: string | Computed<string>;
  principalId?: string | Computed<string>;
  role?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ActionConnectionResponse_Data_Attributes_Integration {
  baseUrl?: string | Computed<string>;
  credentials?: ActionConnectionResponse_Data_Attributes_Integration_Credentials | Computed<ActionConnectionResponse_Data_Attributes_Integration_Credentials>;
  type?: string | Computed<string>;
}

export interface ActionConnectionResponse_Data_Attributes {
  /** The definition of `ActionConnectionIntegration` object. */
  integration: ActionConnectionResponse_Data_Attributes_Integration | Computed<ActionConnectionResponse_Data_Attributes_Integration>;
  /** Name of the connection */
  name: string | Computed<string>;
  /** Tags associated with the connection. Each tag must follow the `key:value` format. The `default` tag key is reserved. */
  tags?: string[] | Computed<string[]>;
}

export interface ActionConnectionResponse_Data {
  /** The definition of `ActionConnectionAttributes` object. */
  attributes: ActionConnectionResponse_Data_Attributes | Computed<ActionConnectionResponse_Data_Attributes>;
  /** The connection identifier */
  id?: string | Computed<string>;
  /** The definition of `ActionConnectionDataType` object. */
  type: string | Computed<string>;
}

const ActionConnectionResponse_Data_Attributes_Integration_CredentialsFields: FieldMap = {
  accountId: "account_id",
  externalId: "external_id",
  principalId: "principal_id",
  role: "role",
  type: "type",
};

const ActionConnectionResponse_Data_Attributes_IntegrationFields: FieldMap = {
  baseUrl: "base_url",
  credentials: {
    wireName: "credentials",
    kind: "object",
    fields: ActionConnectionResponse_Data_Attributes_Integration_CredentialsFields,
  },
  type: "type",
};

const ActionConnectionResponse_Data_AttributesFields: FieldMap = {
  integration: {
    wireName: "integration",
    kind: "object",
    fields: ActionConnectionResponse_Data_Attributes_IntegrationFields,
  },
  name: "name",
  tags: "tags",
};

const ActionConnectionResponse_DataFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: ActionConnectionResponse_Data_AttributesFields,
  },
  id: "id",
  type: "type",
};

export interface ActionConnectionResponseConfig {
  /** Data related to the connection. */
  data: ActionConnectionResponse_Data | Computed<ActionConnectionResponse_Data>;
  /** path parameter, not part of the API's own resource representation */
  connectionId: string | Computed<string>;
}

export interface ActionConnectionResponseAttrs {
  /** Data related to the connection. */
  data: ActionConnectionResponse_Data;
  /** path parameter, not part of the API's own resource representation */
  connectionId: string;
}

export const ActionConnectionResponse: ResourceBinding<ActionConnectionResponseConfig, ActionConnectionResponseAttrs> = {
  wireType: "datadog_get_action_connection_response",
  fields: {
    data: {
      wireName: "data",
      kind: "object",
      fields: ActionConnectionResponse_DataFields,
    },
    connectionId: "connection_id",
  },
};
