# Code generated by `ubx sdk gen` from datadog_incident_notification_template_array. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class NotificationTemplateArray_Data_Attributes:
    category: Any = None
    content: Any = None
    created: Any = None
    modified: Any = None
    name: Any = None
    subject: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Data_Relationships_CreatedByUser_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Data_Relationships_CreatedByUser:
    data: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Data_Relationships:
    created_by_user: Any = None
    incident_type: Any = None
    last_modified_by_user: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Data:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Included_Attributes:
    created_at: Any = None
    disabled: Any = None
    email: Any = None
    handle: Any = None
    icon: Any = None
    last_login_time: Any = None
    mfa_enabled: Any = None
    modified_at: Any = None
    name: Any = None
    service_account: Any = None
    status: Any = None
    title: Any = None
    uuid: Any = None
    verified: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Included_Relationships_OtherOrgs:
    data: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Included_Relationships:
    org: Any = None
    other_orgs: Any = None
    other_users: Any = None
    roles: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Included:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Meta_Page:
    # Total number of notification templates.
    total_count: Any = None
    # Total number of notification templates matching the filter.
    total_filtered_count: Any = None

@dataclasses.dataclass
class NotificationTemplateArray_Meta:
    # Pagination metadata.
    page: Any = None

@dataclasses.dataclass
class NotificationTemplateArrayConfig:
    include: Any = None

@dataclasses.dataclass
class NotificationTemplateArrayAttrs:
    # The `NotificationTemplateArray` `data`.
    data: Any = None
    include: Any = None
    # Related objects that are included in the response.
    included: Any = None
    # Response metadata.
    meta: Any = None

NotificationTemplateArray = ubx.DataSourceBinding(
    wire_type="datadog_incident_notification_template_array",
    fields={
        "include": ubx.FieldSpec(wire_name="include"),
    },
)
