# Code generated by `ubx sdk gen` from datadog_incident_org_settings_data_response_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OrgSettingsDataResponseList_Data_Attributes:
    created: Any = None
    modified: Any = None
    settings: Any = None

@dataclasses.dataclass
class OrgSettingsDataResponseList_Data_Relationships_IncidentType_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class OrgSettingsDataResponseList_Data_Relationships_IncidentType:
    data: Any = None

@dataclasses.dataclass
class OrgSettingsDataResponseList_Data_Relationships:
    incident_type: Any = None

@dataclasses.dataclass
class OrgSettingsDataResponseList_Data:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class OrgSettingsDataResponseListConfig:
    include: Any = None
    include_deleted: Any = None

@dataclasses.dataclass
class OrgSettingsDataResponseListAttrs:
    # List of incident org settings resources.
    data: Any = None
    include: Any = None
    include_deleted: Any = None

OrgSettingsDataResponseList = ubx.DataSourceBinding(
    wire_type="datadog_incident_org_settings_data_response_list",
    fields={
        "include": ubx.FieldSpec(wire_name="include"),
        "include_deleted": ubx.FieldSpec(wire_name="include_deleted"),
    },
)
