# Code generated by `ubx sdk gen` from datadog_incident_responders_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class RespondersResponse_Data_Attributes:
    created: Any = None
    external_id: Any = None
    external_source: Any = None
    is_billable: Any = None
    last_active: Any = None
    meta: Any = None
    modified: Any = None

@dataclasses.dataclass
class RespondersResponse_Data_Relationships_CreatedBy_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class RespondersResponse_Data_Relationships_CreatedBy:
    data: Any = None

@dataclasses.dataclass
class RespondersResponse_Data_Relationships_RoleAssignments:
    data: Any = None

@dataclasses.dataclass
class RespondersResponse_Data_Relationships:
    created_by: Any = None
    last_modified_by: Any = None
    role_assignments: Any = None
    user: Any = None

@dataclasses.dataclass
class RespondersResponse_Data:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class RespondersResponse_Included_Attributes:
    email: Any = None
    handle: Any = None
    icon: Any = None
    name: Any = None
    uuid: Any = None

@dataclasses.dataclass
class RespondersResponse_Included:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class RespondersResponseConfig:
    incident_id: Any = None

@dataclasses.dataclass
class RespondersResponseAttrs:
    # List of incident responders.
    data: Any = None
    incident_id: Any = None
    # Included related resources.
    included: Any = None

RespondersResponse = ubx.DataSourceBinding(
    wire_type="datadog_incident_responders_response",
    fields={
        "incident_id": ubx.FieldSpec(wire_name="incident_id"),
    },
)
