// Code generated by `ubx sdk gen` from datadog_jira_account_data_list. DO NOT EDIT.
package jira

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AccountDataList_Data_Attributes struct {
	ConsumerKey any
	InstanceUrl any
	LastWebhookTimestamp any
}

type AccountDataList_Data struct {
	Attributes any
	Id any
	Type any
}

type AccountDataList_Meta struct {
	// Public key for the Jira integration
	PublicKey any
}

type AccountDataListConfig struct {
}

type AccountDataListAttrs struct {
	// Array of Jira account data objects
	Data any
	// Metadata for Jira accounts response
	Meta any
}

var AccountDataList = ubx.DataSourceBinding{
	WireType: "datadog_jira_account_data_list",
	Fields: ubx.FieldMap{
	},
}
