# Code generated by `ubx sdk gen` from datadog_organization_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Response_Billing:
    # The type of billing. Only `parent_billing` is supported.
    type: Any = None

@dataclasses.dataclass
class Response_Org_Settings_Saml:
    # Whether or not SAML is enabled for this organization.
    enabled: Any = None

@dataclasses.dataclass
class Response_Org_Settings_SamlAutocreateUsersDomains:
    # List of domains where the SAML automated user creation is enabled.
    domains: Any = None
    # Whether or not the automated user creation based on SAML domain is enabled.
    enabled: Any = None

@dataclasses.dataclass
class Response_Org_Settings:
    # Whether or not the organization users can share widgets outside of Datadog.
    private_widget_share: Any = None
    # Set the boolean property enabled to enable or disable single sign on with SAML. See the SAML documentation for more information about all SAML settings.
    saml: Any = None
    # The access role of the user. Options are **st** (standard user), **adm** (admin user), or **ro** (read-only user).
    saml_autocreate_access_role: Any = None
    # Has two properties, `enabled` (boolean) and `domains`, which is a list of domains without the @ symbol.
    saml_autocreate_users_domains: Any = None
    # Whether or not SAML can be enabled for this organization.
    saml_can_be_enabled: Any = None
    # Identity provider endpoint for SAML authentication.
    saml_idp_endpoint: Any = None
    # Has one property enabled (boolean).
    saml_idp_initiated_login: Any = None
    # Whether or not a SAML identity provider metadata file was provided to the Datadog organization.
    saml_idp_metadata_uploaded: Any = None
    # URL for SAML logging.
    saml_login_url: Any = None
    # Has one property enabled (boolean).
    saml_strict_mode: Any = None

@dataclasses.dataclass
class Response_Org:
    # A JSON array of billing type.
    billing: Any = None
    # Date of the organization creation.
    created: Any = None
    # Description of the organization.
    description: Any = None
    # The name of the child organization, limited to 32 characters.
    name: Any = None
    # The `public_id` of the organization you are operating within.
    public_id: Any = None
    # A JSON array of settings.
    settings: Any = None
    # Subscription definition.
    subscription: Any = None
    # Only available for MSP customers. Allows child organizations to be created on a trial plan.
    trial: Any = None

_Response_BillingFields = {
    "type": ubx.FieldSpec(wire_name="type"),
}

_Response_Org_Settings_SamlFields = {
    "enabled": ubx.FieldSpec(wire_name="enabled"),
}

_Response_Org_Settings_SamlAutocreateUsersDomainsFields = {
    "domains": ubx.FieldSpec(wire_name="domains"),
    "enabled": ubx.FieldSpec(wire_name="enabled"),
}

_Response_Org_SettingsFields = {
    "private_widget_share": ubx.FieldSpec(wire_name="private_widget_share"),
    "saml": ubx.FieldSpec(
        wire_name="saml",
        kind="object",
        fields=_Response_Org_Settings_SamlFields,
    ),
    "saml_autocreate_access_role": ubx.FieldSpec(wire_name="saml_autocreate_access_role"),
    "saml_autocreate_users_domains": ubx.FieldSpec(
        wire_name="saml_autocreate_users_domains",
        kind="object",
        fields=_Response_Org_Settings_SamlAutocreateUsersDomainsFields,
    ),
    "saml_can_be_enabled": ubx.FieldSpec(wire_name="saml_can_be_enabled"),
    "saml_idp_endpoint": ubx.FieldSpec(wire_name="saml_idp_endpoint"),
    "saml_idp_initiated_login": ubx.FieldSpec(
        wire_name="saml_idp_initiated_login",
        kind="object",
        fields=_Response_Org_Settings_SamlFields,
    ),
    "saml_idp_metadata_uploaded": ubx.FieldSpec(wire_name="saml_idp_metadata_uploaded"),
    "saml_login_url": ubx.FieldSpec(wire_name="saml_login_url"),
    "saml_strict_mode": ubx.FieldSpec(
        wire_name="saml_strict_mode",
        kind="object",
        fields=_Response_Org_Settings_SamlFields,
    ),
}

@dataclasses.dataclass
class ResponseConfig:
    # A JSON array of billing type.
    billing: Any = None
    # Description of the organization.
    description: Any = None
    # The name of the child organization, limited to 32 characters.
    name: Any = None
    # The `public_id` of the organization you are operating within.
    public_id: Any = None
    # A JSON array of settings.
    settings: Any = None
    # Subscription definition.
    subscription: Any = None
    # Only available for MSP customers. Allows child organizations to be created on a trial plan.
    trial: Any = None

@dataclasses.dataclass
class ResponseAttrs:
    # A JSON array of billing type.
    billing: Any = None
    # Date of the organization creation.
    created: Any = None
    # Description of the organization.
    description: Any = None
    # The name of the child organization, limited to 32 characters.
    name: Any = None
    # Create, edit, and manage organizations.
    org: Any = None
    # The `public_id` of the organization you are operating within.
    public_id: Any = None
    # A JSON array of settings.
    settings: Any = None
    # Subscription definition.
    subscription: Any = None
    # Only available for MSP customers. Allows child organizations to be created on a trial plan.
    trial: Any = None

Response = ubx.ResourceBinding(
    wire_type="datadog_organization_response",
    fields={
        "billing": ubx.FieldSpec(
            wire_name="billing",
            kind="object",
            fields=_Response_BillingFields,
        ),
        "description": ubx.FieldSpec(wire_name="description"),
        "name": ubx.FieldSpec(wire_name="name"),
        "public_id": ubx.FieldSpec(wire_name="public_id"),
        "settings": ubx.FieldSpec(
            wire_name="settings",
            kind="object",
            fields=_Response_Org_SettingsFields,
        ),
        "subscription": ubx.FieldSpec(
            wire_name="subscription",
            kind="object",
            fields=_Response_BillingFields,
        ),
        "trial": ubx.FieldSpec(wire_name="trial"),
    },
)
