// Code generated by `ubx sdk gen` from datadog_fleet_schedule_v2_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ScheduleV2Response_Data_Attributes_NotificationRule {
  /** Notification handles (for example, Slack channels or PagerDuty integrations). */
  handles?: string[] | Computed<string[]>;
  /** Tags associated with the notification rule. */
  tags?: string[] | Computed<string[]>;
}

export interface ScheduleV2Response_Data_Attributes_Rule {
  /** Days of the week when the schedule triggers. Valid values are "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun". */
  daysOfWeek?: string[] | Computed<string[]>;
  /** Interval between schedule runs in weeks. 1 means the schedule runs every week on the specified days. Higher values repeat every N weeks. */
  interval?: number | Computed<number>;
  /** Duration of the maintenance window in minutes. */
  maintenanceWindowDuration?: number | Computed<number>;
  /** Start time of the maintenance window in 24-hour clock format (HHMM). Deployments are triggered at this time on the specified days. */
  startMaintenanceWindow?: string | Computed<string>;
  /** Timezone in IANA Time Zone Database format. */
  timezone?: string | Computed<string>;
}

export interface ScheduleV2Response_Data_Attributes {
  /** RFC3339 timestamp when the schedule was created. */
  createdAt?: string | Computed<string>;
  /** User handle of the person who created the schedule. */
  createdBy?: string | Computed<string>;
  /** Whether this is the default schedule for the organization. */
  isDefault?: boolean | Computed<boolean>;
  /** Human-readable name for the schedule. */
  name?: string | Computed<string>;
  /** RFC3339 timestamp of the next scheduled maintenance window start time. Absent when the next run time cannot be computed. */
  nextRun?: string | Computed<string>;
  /** Notification configuration attached to a schedule. Included when available. If the notification rule cannot be retrieved, this field is omitted and the schedule is still returned. If the notification rule is retrieved but its handles cannot be resolved, it is still included with an empty `handles` array. */
  notificationRule?: ScheduleV2Response_Data_Attributes_NotificationRule | Computed<ScheduleV2Response_Data_Attributes_NotificationRule>;
  /** Query used to filter and select target hosts for scheduled deployments. */
  query?: string | Computed<string>;
  /** Defines the recurrence pattern for the schedule. */
  rule?: ScheduleV2Response_Data_Attributes_Rule | Computed<ScheduleV2Response_Data_Attributes_Rule>;
  /** The status of the schedule. - `active`: The schedule is active and will create deployments according to its recurrence rule. - `inactive`: The schedule is inactive and will not create any deployments. */
  status?: string | Computed<string>;
  /** RFC3339 timestamp when the schedule was last updated. */
  updatedAt?: string | Computed<string>;
  /** User handle of the person who last updated the schedule. */
  updatedBy?: string | Computed<string>;
  /** Number of major versions behind the latest to target for upgrades. - 0: Always upgrade to the latest version. - 1: Upgrade to latest minus 1 major version. - 2: Upgrade to latest minus 2 major versions. */
  versionToLatest?: number | Computed<number>;
}

export interface ScheduleV2Response_Data {
  /** Attributes of a fleet schedule in the v2 API response. */
  attributes: ScheduleV2Response_Data_Attributes | Computed<ScheduleV2Response_Data_Attributes>;
  /** Unique identifier for the schedule. */
  id: string | Computed<string>;
  /** The type of schedule resource. */
  type: string | Computed<string>;
}

export interface ScheduleV2ResponseConfig {
  id: string | Computed<string>;
}

export interface ScheduleV2ResponseAttrs {
  /** A fleet upgrade schedule resource in the v2 API response. */
  data: ScheduleV2Response_Data;
  id: string;
}

export const ScheduleV2Response: DataSourceBinding<ScheduleV2ResponseConfig, ScheduleV2ResponseAttrs> = {
  wireType: "datadog_fleet_schedule_v2_response",
  fields: {
    id: "id",
  },
};
