// Code generated by `ubx sdk gen` from datadog_maintenance_window_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface WindowList_Data_Attributes {
  createdBy?: string | Computed<string>;
  endAt?: string | Computed<string>;
  name?: string | Computed<string>;
  query?: string | Computed<string>;
  startAt?: string | Computed<string>;
  updatedBy?: string | Computed<string>;
}

export interface WindowList_Data {
  attributes?: WindowList_Data_Attributes | Computed<WindowList_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface WindowListConfig {
}

export interface WindowListAttrs {
  /** List of maintenance windows. */
  data: WindowList_Data[];
}

export const WindowList: DataSourceBinding<WindowListConfig, WindowListAttrs> = {
  wireType: "datadog_maintenance_window_list",
  fields: {
  },
};
