# Code generated by `ubx sdk gen` from datadog_monitor_group_search_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GroupSearchResponse_Counts_Status:
    count: Any = None
    name: Any = None

@dataclasses.dataclass
class GroupSearchResponse_Counts:
    # Search facets.
    status: Any = None
    # Search facets.
    type: Any = None

@dataclasses.dataclass
class GroupSearchResponse_Groups:
    group: Any = None
    group_tags: Any = None
    last_nodata_ts: Any = None
    last_triggered_ts: Any = None
    monitor_id: Any = None
    monitor_name: Any = None
    status: Any = None

@dataclasses.dataclass
class GroupSearchResponse_Metadata:
    # The page to start paginating from.
    page: Any = None
    # The number of pages.
    page_count: Any = None
    # The number of monitors to return per page.
    per_page: Any = None
    # The total number of monitors.
    total_count: Any = None

@dataclasses.dataclass
class GroupSearchResponseConfig:
    page: Any = None
    per_page: Any = None
    query: Any = None
    sort: Any = None

@dataclasses.dataclass
class GroupSearchResponseAttrs:
    # The counts of monitor groups per different criteria.
    counts: Any = None
    # The list of found monitor groups.
    groups: Any = None
    # Metadata about the response.
    metadata: Any = None
    page: Any = None
    per_page: Any = None
    query: Any = None
    sort: Any = None

GroupSearchResponse = ubx.DataSourceBinding(
    wire_type="datadog_monitor_group_search_response",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "query": ubx.FieldSpec(wire_name="query"),
        "sort": ubx.FieldSpec(wire_name="sort"),
    },
)
