// Code generated by `ubx sdk gen` from datadog_synthetics_mobile_test. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MobileTest_Config_Variables {
  example?: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  pattern?: string | Computed<string>;
  secure?: boolean | Computed<boolean>;
  type?: string | Computed<string>;
}

export interface MobileTest_Config {
  /** Initial application arguments for a mobile test. */
  initialApplicationArguments?: Record<string, string> | Computed<Record<string, string>>;
  /** Array of variables used for the test steps. */
  variables?: MobileTest_Config_Variables[] | Computed<MobileTest_Config_Variables[]>;
}

export interface MobileTest_Options_Bindings {
  principals?: string[] | Computed<string[]>;
  relation?: string | Computed<string>;
}

export interface MobileTest_Options_Ci {
  /** Execution rule for a Synthetic test. */
  executionRule: string | Computed<string>;
}

export interface MobileTest_Options_MobileApplication {
  /** Application ID of the mobile application. */
  applicationId: string | Computed<string>;
  /** Reference ID of the mobile application. */
  referenceId: string | Computed<string>;
  /** Reference type for the mobile application for a mobile synthetics test. */
  referenceType: string | Computed<string>;
}

export interface MobileTest_Options_MonitorOptions {
  /** Message to include in the escalation notification. */
  escalationMessage?: string | Computed<string>;
  /** The name of the preset for the notification for the monitor. */
  notificationPresetName?: string | Computed<string>;
  /** Time interval before renotifying if the test is still failing (in minutes). */
  renotifyInterval?: number | Computed<number>;
  /** The number of times to renotify if the test is still failing. */
  renotifyOccurrences?: number | Computed<number>;
}

export interface MobileTest_Options_Retry {
  /** Number of times a test needs to be retried before marking a location as failed. Defaults to 0. */
  count?: number | Computed<number>;
  /** Time interval between retries (in milliseconds). Defaults to 300ms. */
  interval?: number | Computed<number>;
}

export interface MobileTest_Options_Scheduling_Timeframes {
  day?: number | Computed<number>;
  from?: string | Computed<string>;
  to?: string | Computed<string>;
}

export interface MobileTest_Options_Scheduling {
  /** Array containing objects describing the scheduling pattern to apply to each day. */
  timeframes: MobileTest_Options_Scheduling_Timeframes[] | Computed<MobileTest_Options_Scheduling_Timeframes[]>;
  /** Timezone in which the timeframe is based. */
  timezone: string | Computed<string>;
}

export interface MobileTest_Options {
  /** A boolean to set if an application crash would mark the test as failed. */
  allowApplicationCrash?: boolean | Computed<boolean>;
  /** Array of bindings used for the mobile test. */
  bindings?: MobileTest_Options_Bindings[] | Computed<MobileTest_Options_Bindings[]>;
  /** CI/CD options for a Synthetic test. */
  ci?: MobileTest_Options_Ci | Computed<MobileTest_Options_Ci>;
  /** The default timeout for steps in the test (in seconds). */
  defaultStepTimeout?: number | Computed<number>;
  /** For mobile test, array with the different device IDs used to run the test. */
  deviceIds: string[] | Computed<string[]>;
  /** A boolean to disable auto accepting alerts. */
  disableAutoAcceptAlert?: boolean | Computed<boolean>;
  /** Minimum amount of time in failure required to trigger an alert. */
  minFailureDuration?: number | Computed<number>;
  /** Mobile application for mobile synthetics test. */
  mobileApplication: MobileTest_Options_MobileApplication | Computed<MobileTest_Options_MobileApplication>;
  /** The monitor name is used for the alert title as well as for all monitor dashboard widgets and SLOs. */
  monitorName?: string | Computed<string>;
  /** Object containing the options for a Synthetic test as a monitor (for example, renotification). */
  monitorOptions?: MobileTest_Options_MonitorOptions | Computed<MobileTest_Options_MonitorOptions>;
  /** Integer from 1 (high) to 5 (low) indicating alert severity. */
  monitorPriority?: number | Computed<number>;
  /** A boolean set to not take a screenshot for the step. */
  noScreenshot?: boolean | Computed<boolean>;
  /** A list of role identifiers that can be pulled from the Roles API, for restricting read and write access. This field is deprecated. Use the restriction policies API to manage permissions. */
  restrictedRoles?: string[] | Computed<string[]>;
  /** Object describing the retry strategy to apply to a Synthetic test. */
  retry?: MobileTest_Options_Retry | Computed<MobileTest_Options_Retry>;
  /** Object containing timeframes and timezone used for advanced scheduling. */
  scheduling?: MobileTest_Options_Scheduling | Computed<MobileTest_Options_Scheduling>;
  /** The frequency at which to run the Synthetic test (in seconds). */
  tickEvery: number | Computed<number>;
  /** The level of verbosity for the mobile test. This field can not be set by a user. */
  verbosity?: number | Computed<number>;
}

export interface MobileTest_Steps_Params_Element_RelativePosition {
  x?: number | Computed<number>;
  y?: number | Computed<number>;
}

export interface MobileTest_Steps_Params_Element_UserLocator_Values {
  type?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface MobileTest_Steps_Params_Element_UserLocator {
  failTestOnCannotLocate?: boolean | Computed<boolean>;
  values?: MobileTest_Steps_Params_Element_UserLocator_Values[] | Computed<MobileTest_Steps_Params_Element_UserLocator_Values[]>;
}

export interface MobileTest_Steps_Params_Element {
  context?: string | Computed<string>;
  contextType?: string | Computed<string>;
  elementDescription?: string | Computed<string>;
  multiLocator?: unknown | Computed<unknown>;
  relativePosition?: MobileTest_Steps_Params_Element_RelativePosition | Computed<MobileTest_Steps_Params_Element_RelativePosition>;
  textContent?: string | Computed<string>;
  userLocator?: MobileTest_Steps_Params_Element_UserLocator | Computed<MobileTest_Steps_Params_Element_UserLocator>;
  viewName?: string | Computed<string>;
}

export interface MobileTest_Steps_Params_Variable {
  example?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface MobileTest_Steps_Params {
  check?: string | Computed<string>;
  delay?: number | Computed<number>;
  direction?: string | Computed<string>;
  element?: MobileTest_Steps_Params_Element | Computed<MobileTest_Steps_Params_Element>;
  enabled?: boolean | Computed<boolean>;
  maxScrolls?: number | Computed<number>;
  positions?: MobileTest_Steps_Params_Element_RelativePosition[] | Computed<MobileTest_Steps_Params_Element_RelativePosition[]>;
  subtestPublicId?: string | Computed<string>;
  value?: unknown | Computed<unknown>;
  variable?: MobileTest_Steps_Params_Variable | Computed<MobileTest_Steps_Params_Variable>;
  withEnter?: boolean | Computed<boolean>;
  x?: number | Computed<number>;
  y?: number | Computed<number>;
}

export interface MobileTest_Steps {
  allowFailure?: boolean | Computed<boolean>;
  hasNewStepElement?: boolean | Computed<boolean>;
  isCritical?: boolean | Computed<boolean>;
  name?: string | Computed<string>;
  noScreenshot?: boolean | Computed<boolean>;
  params?: MobileTest_Steps_Params | Computed<MobileTest_Steps_Params>;
  publicId?: string | Computed<string>;
  timeout?: number | Computed<number>;
  type?: string | Computed<string>;
}

const MobileTest_Config_VariablesFields: FieldMap = {
  example: "example",
  id: "id",
  name: "name",
  pattern: "pattern",
  secure: "secure",
  type: "type",
};

const MobileTest_ConfigFields: FieldMap = {
  initialApplicationArguments: "initial_application_arguments",
  variables: {
    wireName: "variables",
    kind: "list",
    fields: MobileTest_Config_VariablesFields,
  },
};

const MobileTest_Options_BindingsFields: FieldMap = {
  principals: "principals",
  relation: "relation",
};

const MobileTest_Options_CiFields: FieldMap = {
  executionRule: "execution_rule",
};

const MobileTest_Options_MobileApplicationFields: FieldMap = {
  applicationId: "application_id",
  referenceId: "reference_id",
  referenceType: "reference_type",
};

const MobileTest_Options_MonitorOptionsFields: FieldMap = {
  escalationMessage: "escalation_message",
  notificationPresetName: "notification_preset_name",
  renotifyInterval: "renotify_interval",
  renotifyOccurrences: "renotify_occurrences",
};

const MobileTest_Options_RetryFields: FieldMap = {
  count: "count",
  interval: "interval",
};

const MobileTest_Options_Scheduling_TimeframesFields: FieldMap = {
  day: "day",
  from: "from",
  to: "to",
};

const MobileTest_Options_SchedulingFields: FieldMap = {
  timeframes: {
    wireName: "timeframes",
    kind: "list",
    fields: MobileTest_Options_Scheduling_TimeframesFields,
  },
  timezone: "timezone",
};

const MobileTest_OptionsFields: FieldMap = {
  allowApplicationCrash: "allow_application_crash",
  bindings: {
    wireName: "bindings",
    kind: "list",
    fields: MobileTest_Options_BindingsFields,
  },
  ci: {
    wireName: "ci",
    kind: "object",
    fields: MobileTest_Options_CiFields,
  },
  defaultStepTimeout: "default_step_timeout",
  deviceIds: "device_ids",
  disableAutoAcceptAlert: "disable_auto_accept_alert",
  minFailureDuration: "min_failure_duration",
  mobileApplication: {
    wireName: "mobile_application",
    kind: "object",
    fields: MobileTest_Options_MobileApplicationFields,
  },
  monitorName: "monitor_name",
  monitorOptions: {
    wireName: "monitor_options",
    kind: "object",
    fields: MobileTest_Options_MonitorOptionsFields,
  },
  monitorPriority: "monitor_priority",
  noScreenshot: "no_screenshot",
  restrictedRoles: "restricted_roles",
  retry: {
    wireName: "retry",
    kind: "object",
    fields: MobileTest_Options_RetryFields,
  },
  scheduling: {
    wireName: "scheduling",
    kind: "object",
    fields: MobileTest_Options_SchedulingFields,
  },
  tickEvery: "tick_every",
  verbosity: "verbosity",
};

const MobileTest_Steps_Params_Element_RelativePositionFields: FieldMap = {
  x: "x",
  y: "y",
};

const MobileTest_Steps_Params_Element_UserLocator_ValuesFields: FieldMap = {
  type: "type",
  value: "value",
};

const MobileTest_Steps_Params_Element_UserLocatorFields: FieldMap = {
  failTestOnCannotLocate: "fail_test_on_cannot_locate",
  values: {
    wireName: "values",
    kind: "list",
    fields: MobileTest_Steps_Params_Element_UserLocator_ValuesFields,
  },
};

const MobileTest_Steps_Params_ElementFields: FieldMap = {
  context: "context",
  contextType: "context_type",
  elementDescription: "element_description",
  multiLocator: "multi_locator",
  relativePosition: {
    wireName: "relative_position",
    kind: "object",
    fields: MobileTest_Steps_Params_Element_RelativePositionFields,
  },
  textContent: "text_content",
  userLocator: {
    wireName: "user_locator",
    kind: "object",
    fields: MobileTest_Steps_Params_Element_UserLocatorFields,
  },
  viewName: "view_name",
};

const MobileTest_Steps_Params_VariableFields: FieldMap = {
  example: "example",
  name: "name",
};

const MobileTest_Steps_ParamsFields: FieldMap = {
  check: "check",
  delay: "delay",
  direction: "direction",
  element: {
    wireName: "element",
    kind: "object",
    fields: MobileTest_Steps_Params_ElementFields,
  },
  enabled: "enabled",
  maxScrolls: "max_scrolls",
  positions: {
    wireName: "positions",
    kind: "list",
    fields: MobileTest_Steps_Params_Element_RelativePositionFields,
  },
  subtestPublicId: "subtest_public_id",
  value: "value",
  variable: {
    wireName: "variable",
    kind: "object",
    fields: MobileTest_Steps_Params_VariableFields,
  },
  withEnter: "with_enter",
  x: "x",
  y: "y",
};

const MobileTest_StepsFields: FieldMap = {
  allowFailure: "allow_failure",
  hasNewStepElement: "has_new_step_element",
  isCritical: "is_critical",
  name: "name",
  noScreenshot: "no_screenshot",
  params: {
    wireName: "params",
    kind: "object",
    fields: MobileTest_Steps_ParamsFields,
  },
  publicId: "public_id",
  timeout: "timeout",
  type: "type",
};

export interface MobileTestConfig {
  /** Configuration object for a Synthetic mobile test. */
  config: MobileTest_Config | Computed<MobileTest_Config>;
  /** Array with the different device IDs used to run the test. */
  deviceIds?: string[] | Computed<string[]>;
  /** Notification message associated with the test. */
  message: string | Computed<string>;
  /** Name of the test. */
  name: string | Computed<string>;
  /** Object describing the extra options for a Synthetic test. */
  options: MobileTest_Options | Computed<MobileTest_Options>;
  /** Define whether you want to start (`live`) or pause (`paused`) a Synthetic test. */
  status?: string | Computed<string>;
  /** Array of steps for the test. */
  steps?: MobileTest_Steps[] | Computed<MobileTest_Steps[]>;
  /** Array of tags attached to the test. */
  tags?: string[] | Computed<string[]>;
  /** Type of the Synthetic test, `mobile`. */
  type: string | Computed<string>;
}

export interface MobileTestAttrs {
  /** Configuration object for a Synthetic mobile test. */
  config: MobileTest_Config;
  /** Array with the different device IDs used to run the test. */
  deviceIds: string[];
  /** Notification message associated with the test. */
  message: string;
  /** The associated monitor ID. */
  monitorId: number;
  /** Name of the test. */
  name: string;
  /** Object describing the extra options for a Synthetic test. */
  options: MobileTest_Options;
  /** The public ID of the test. */
  publicId: string;
  /** Define whether you want to start (`live`) or pause (`paused`) a Synthetic test. */
  status: string;
  /** Array of steps for the test. */
  steps: MobileTest_Steps[];
  /** Array of tags attached to the test. */
  tags: string[];
  /** Type of the Synthetic test, `mobile`. */
  type: string;
}

export const MobileTest: ResourceBinding<MobileTestConfig, MobileTestAttrs> = {
  wireType: "datadog_synthetics_mobile_test",
  fields: {
    config: {
      wireName: "config",
      kind: "object",
      fields: MobileTest_ConfigFields,
    },
    deviceIds: "device_ids",
    message: "message",
    name: "name",
    options: {
      wireName: "options",
      kind: "object",
      fields: MobileTest_OptionsFields,
    },
    status: "status",
    steps: {
      wireName: "steps",
      kind: "list",
      fields: MobileTest_StepsFields,
    },
    tags: "tags",
    type: "type",
  },
};
