// Code generated by `ubx sdk gen` from datadog_list_feature_flags_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface FeatureFlagsResponse_Data_Attributes_FeatureFlagEnvironments {
  defaultAllocationKey?: string | Computed<string>;
  defaultVariantId?: string | Computed<string>;
  environmentId?: string | Computed<string>;
  environmentName?: string | Computed<string>;
  environmentQueries?: string[] | Computed<string[]>;
  isProduction?: boolean | Computed<boolean>;
  overrideAllocationKey?: string | Computed<string>;
  overrideVariantId?: string | Computed<string>;
  pendingSuggestionId?: string | Computed<string>;
  requireFeatureFlagApproval?: boolean | Computed<boolean>;
  status?: string | Computed<string>;
}

export interface FeatureFlagsResponse_Data_Attributes_Variants {
  createdAt?: string | Computed<string>;
  id?: string | Computed<string>;
  key?: string | Computed<string>;
  name?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface FeatureFlagsResponse_Data_Attributes {
  archivedAt?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  description?: string | Computed<string>;
  distributionChannel?: string | Computed<string>;
  featureFlagEnvironments?: FeatureFlagsResponse_Data_Attributes_FeatureFlagEnvironments[] | Computed<FeatureFlagsResponse_Data_Attributes_FeatureFlagEnvironments[]>;
  jsonSchema?: string | Computed<string>;
  key?: string | Computed<string>;
  lastUpdatedBy?: string | Computed<string>;
  name?: string | Computed<string>;
  requireApproval?: boolean | Computed<boolean>;
  stalenessStatus?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  updatedAt?: string | Computed<string>;
  valueType?: string | Computed<string>;
  variants?: FeatureFlagsResponse_Data_Attributes_Variants[] | Computed<FeatureFlagsResponse_Data_Attributes_Variants[]>;
}

export interface FeatureFlagsResponse_Data {
  attributes?: FeatureFlagsResponse_Data_Attributes | Computed<FeatureFlagsResponse_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface FeatureFlagsResponse_Meta_Page {
  /** Total number of items. */
  totalCount?: number | Computed<number>;
  /** Total number of items matching the filter. */
  totalFilteredCount?: number | Computed<number>;
}

export interface FeatureFlagsResponse_Meta {
  /** Pagination metadata for feature flags list responses. */
  page?: FeatureFlagsResponse_Meta_Page | Computed<FeatureFlagsResponse_Meta_Page>;
}

export interface FeatureFlagsResponseConfig {
  isArchived?: boolean | Computed<boolean>;
  key?: string | Computed<string>;
  limit?: number | Computed<number>;
  offset?: number | Computed<number>;
}

export interface FeatureFlagsResponseAttrs {
  /** List of feature flags. */
  data: FeatureFlagsResponse_Data[];
  isArchived: boolean;
  key: string;
  limit: number;
  /** Pagination metadata for feature flags. */
  meta: FeatureFlagsResponse_Meta;
  offset: number;
}

export const FeatureFlagsResponse: DataSourceBinding<FeatureFlagsResponseConfig, FeatureFlagsResponseAttrs> = {
  wireType: "datadog_list_feature_flags_response",
  fields: {
    isArchived: "is_archived",
    key: "key",
    limit: "limit",
    offset: "offset",
  },
};
