// Code generated by `ubx sdk gen` from datadog_list_rows_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RowsResponse_Data_Attributes {
  values?: unknown | Computed<unknown>;
}

export interface RowsResponse_Data {
  attributes?: RowsResponse_Data_Attributes | Computed<RowsResponse_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RowsResponse_Links {
  /** Link to the first page of results. */
  first: string | Computed<string>;
  /** Link to the next page of results. Only present when more rows are available. */
  next?: string | Computed<string>;
  /** Link to the current page of results. */
  self: string | Computed<string>;
}

export interface RowsResponse_Meta_Page {
  /** Opaque token to pass as the `page[continuation_token]` query parameter to fetch the next page of results. Only present when more rows are available. */
  nextContinuationToken?: string | Computed<string>;
}

export interface RowsResponse_Meta {
  /** Contains the continuation token for navigating to the next page of rows. */
  page?: RowsResponse_Meta_Page | Computed<RowsResponse_Meta_Page>;
}

export interface RowsResponseConfig {
  id: string | Computed<string>;
}

export interface RowsResponseAttrs {
  /** The rows. */
  data: RowsResponse_Data[];
  id: string;
  /** Pagination links for the list rows response. */
  links: RowsResponse_Links;
  /** Contains pagination details, including the continuation token for fetching additional rows. */
  meta: RowsResponse_Meta;
}

export const RowsResponse: DataSourceBinding<RowsResponseConfig, RowsResponseAttrs> = {
  wireType: "datadog_list_rows_response",
  fields: {
    id: "id",
  },
};
