// Code generated by `ubx sdk gen` from datadog_list_shared_dashboards_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface SharedDashboardsResponse_Data_Attributes_Invitees {
  accessExpiration?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  email?: string | Computed<string>;
}

export interface SharedDashboardsResponse_Data_Attributes_SelectableTemplateVars {
  allowAnyValue?: boolean | Computed<boolean>;
  defaultValues?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  prefix?: string | Computed<string>;
  type?: string | Computed<string>;
  visibleTags?: string[] | Computed<string[]>;
}

export interface SharedDashboardsResponse_Data_Attributes_ViewingPreferences {
  highDensity?: boolean | Computed<boolean>;
  theme?: string | Computed<string>;
}

export interface SharedDashboardsResponse_Data_Attributes {
  createdAt?: string | Computed<string>;
  embeddableDomains?: string[] | Computed<string[]>;
  expiration?: string | Computed<string>;
  globalTime?: Record<string, unknown> | Computed<Record<string, unknown>>;
  globalTimeSelectable?: boolean | Computed<boolean>;
  invitees?: SharedDashboardsResponse_Data_Attributes_Invitees[] | Computed<SharedDashboardsResponse_Data_Attributes_Invitees[]>;
  lastAccessed?: string | Computed<string>;
  selectableTemplateVars?: SharedDashboardsResponse_Data_Attributes_SelectableTemplateVars[] | Computed<SharedDashboardsResponse_Data_Attributes_SelectableTemplateVars[]>;
  shareType?: string | Computed<string>;
  sharerDisabled?: boolean | Computed<boolean>;
  status?: string | Computed<string>;
  title?: string | Computed<string>;
  token?: string | Computed<string>;
  url?: string | Computed<string>;
  viewingPreferences?: SharedDashboardsResponse_Data_Attributes_ViewingPreferences | Computed<SharedDashboardsResponse_Data_Attributes_ViewingPreferences>;
}

export interface SharedDashboardsResponse_Data_Relationships_Dashboard_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface SharedDashboardsResponse_Data_Relationships_Dashboard {
  data?: SharedDashboardsResponse_Data_Relationships_Dashboard_Data | Computed<SharedDashboardsResponse_Data_Relationships_Dashboard_Data>;
}

export interface SharedDashboardsResponse_Data_Relationships {
  dashboard?: SharedDashboardsResponse_Data_Relationships_Dashboard | Computed<SharedDashboardsResponse_Data_Relationships_Dashboard>;
  sharer?: SharedDashboardsResponse_Data_Relationships_Dashboard | Computed<SharedDashboardsResponse_Data_Relationships_Dashboard>;
}

export interface SharedDashboardsResponse_Data {
  attributes?: SharedDashboardsResponse_Data_Attributes | Computed<SharedDashboardsResponse_Data_Attributes>;
  id?: string | Computed<string>;
  relationships?: SharedDashboardsResponse_Data_Relationships | Computed<SharedDashboardsResponse_Data_Relationships>;
  type?: string | Computed<string>;
}

export interface SharedDashboardsResponse_Included_Attributes {
  title?: string | Computed<string>;
}

export interface SharedDashboardsResponse_Included {
  attributes?: SharedDashboardsResponse_Included_Attributes | Computed<SharedDashboardsResponse_Included_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface SharedDashboardsResponseConfig {
  dashboardId: string | Computed<string>;
}

export interface SharedDashboardsResponseAttrs {
  dashboardId: string;
  /** Shared dashboards for the dashboard. */
  data: SharedDashboardsResponse_Data[];
  /** Users and dashboards related to the shared dashboards. */
  included: SharedDashboardsResponse_Included[];
}

export const SharedDashboardsResponse: DataSourceBinding<SharedDashboardsResponseConfig, SharedDashboardsResponseAttrs> = {
  wireType: "datadog_list_shared_dashboards_response",
  fields: {
    dashboardId: "dashboard_id",
  },
};
