// Code generated by `ubx sdk gen` from datadog_custom_costs_file_list_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CostsFileListResponse_Data_Attributes_ChargePeriod {
  end?: number | Computed<number>;
  start?: number | Computed<number>;
}

export interface CostsFileListResponse_Data_Attributes_UploadedBy {
  email?: string | Computed<string>;
  icon?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface CostsFileListResponse_Data_Attributes {
  billedCost?: number | Computed<number>;
  billingCurrency?: string | Computed<string>;
  chargePeriod?: CostsFileListResponse_Data_Attributes_ChargePeriod | Computed<CostsFileListResponse_Data_Attributes_ChargePeriod>;
  name?: string | Computed<string>;
  providerNames?: string[] | Computed<string[]>;
  status?: string | Computed<string>;
  uploadedAt?: number | Computed<number>;
  uploadedBy?: CostsFileListResponse_Data_Attributes_UploadedBy | Computed<CostsFileListResponse_Data_Attributes_UploadedBy>;
}

export interface CostsFileListResponse_Data {
  attributes?: CostsFileListResponse_Data_Attributes | Computed<CostsFileListResponse_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface CostsFileListResponse_Meta {
  /** Number of Custom Costs files per status. */
  countByStatus?: Record<string, number> | Computed<Record<string, number>>;
  /** List of available providers. */
  providers?: string[] | Computed<string[]>;
  /** Number of Custom Costs files returned by the List Custom Costs endpoint */
  totalFilteredCount?: number | Computed<number>;
  /** Version of Custom Costs file */
  version?: string | Computed<string>;
}

export interface CostsFileListResponseConfig {
  sort?: string | Computed<string>;
}

export interface CostsFileListResponseAttrs {
  /** List of Custom Costs files. */
  data: CostsFileListResponse_Data[];
  /** Meta for the response from the List Custom Costs endpoints. */
  meta: CostsFileListResponse_Meta;
  sort: string;
}

export const CostsFileListResponse: DataSourceBinding<CostsFileListResponseConfig, CostsFileListResponseAttrs> = {
  wireType: "datadog_custom_costs_file_list_response",
  fields: {
    sort: "sort",
  },
};
