// Code generated by `ubx sdk gen` from datadog_custom_ruleset_list_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes_Arguments {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes_Tests {
  annotationCount?: number | Computed<number>;
  code?: string | Computed<string>;
  filename?: string | Computed<string>;
}

export interface RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes {
  arguments?: RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes_Arguments[] | Computed<RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes_Arguments[]>;
  category?: string | Computed<string>;
  checksum?: string | Computed<string>;
  code?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  creationMessage?: string | Computed<string>;
  cve?: string | Computed<string>;
  cwe?: string | Computed<string>;
  description?: string | Computed<string>;
  documentationUrl?: string | Computed<string>;
  isPublished?: boolean | Computed<boolean>;
  isTesting?: boolean | Computed<boolean>;
  language?: string | Computed<string>;
  severity?: string | Computed<string>;
  shortDescription?: string | Computed<string>;
  shouldUseAiFix?: boolean | Computed<boolean>;
  tags?: string[] | Computed<string[]>;
  tests?: RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes_Tests[] | Computed<RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes_Tests[]>;
  treeSitterQuery?: string | Computed<string>;
}

export interface RulesetListResponse_Data_Attributes_Rules_LastRevision {
  attributes?: RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes | Computed<RulesetListResponse_Data_Attributes_Rules_LastRevision_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RulesetListResponse_Data_Attributes_Rules {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  lastRevision?: RulesetListResponse_Data_Attributes_Rules_LastRevision | Computed<RulesetListResponse_Data_Attributes_Rules_LastRevision>;
  name?: string | Computed<string>;
}

export interface RulesetListResponse_Data_Attributes {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  rules?: RulesetListResponse_Data_Attributes_Rules[] | Computed<RulesetListResponse_Data_Attributes_Rules[]>;
  shortDescription?: string | Computed<string>;
}

export interface RulesetListResponse_Data {
  attributes?: RulesetListResponse_Data_Attributes | Computed<RulesetListResponse_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RulesetListResponseConfig {
}

export interface RulesetListResponseAttrs {
  /** The list of custom rulesets. */
  data: RulesetListResponse_Data[];
}

export const RulesetListResponse: DataSourceBinding<RulesetListResponseConfig, RulesetListResponseAttrs> = {
  wireType: "datadog_custom_ruleset_list_response",
  fields: {
  },
};
