// Code generated by `ubx sdk gen` from datadog_logs_index. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Index_DailyLimitReset {
  /** String in `HH:00` format representing the time of day the daily limit should be reset. The hours must be between 00 and 23 (inclusive). */
  resetTime?: string | Computed<string>;
  /** String in `(-|+)HH:00` format representing the UTC offset to apply to the given reset time. The hours must be between -12 and +14 (inclusive). */
  resetUtcOffset?: string | Computed<string>;
}

export interface Index_ExclusionFilters_Filter {
  query?: string | Computed<string>;
  sampleAttribute?: string | Computed<string>;
  sampleRate?: number | Computed<number>;
}

export interface Index_ExclusionFilters {
  filter?: Index_ExclusionFilters_Filter | Computed<Index_ExclusionFilters_Filter>;
  isEnabled?: boolean | Computed<boolean>;
  name?: string | Computed<string>;
}

export interface Index_Filter {
  /** The filter query. */
  query?: string | Computed<string>;
}

const Index_DailyLimitResetFields: FieldMap = {
  resetTime: "reset_time",
  resetUtcOffset: "reset_utc_offset",
};

const Index_ExclusionFilters_FilterFields: FieldMap = {
  query: "query",
  sampleAttribute: "sample_attribute",
  sampleRate: "sample_rate",
};

const Index_ExclusionFiltersFields: FieldMap = {
  filter: {
    wireName: "filter",
    kind: "object",
    fields: Index_ExclusionFilters_FilterFields,
  },
  isEnabled: "is_enabled",
  name: "name",
};

const Index_FilterFields: FieldMap = {
  query: "query",
};

export interface IndexConfig {
  /** The number of log events you can send in this index per day before you are rate-limited. */
  dailyLimit?: number | Computed<number>;
  /** Object containing options to override the default daily limit reset time. */
  dailyLimitReset?: Index_DailyLimitReset | Computed<Index_DailyLimitReset>;
  /** A percentage threshold of the daily quota at which a Datadog warning event is generated. */
  dailyLimitWarningThresholdPercentage?: number | Computed<number>;
  /** An array of exclusion objects. The logs are tested against the query of each filter, following the order of the array. Only the first matching active exclusion matters, others (if any) are ignored. */
  exclusionFilters?: Index_ExclusionFilters[] | Computed<Index_ExclusionFilters[]>;
  /** Filter for logs. */
  filter: Index_Filter | Computed<Index_Filter>;
  /** The name of the index. */
  name: string | Computed<string>;
  /** The total number of days logs are stored in Standard and Flex Tier before being deleted from the index. If Standard Tier is enabled on this index, logs are first retained in Standard Tier for the number of days specified through `num_retention_days`, and then stored in Flex Tier until the number of days specified in `num_flex_logs_retention_days` is reached. The available values depend on retention plans specified in your organization's contract/subscriptions. */
  numFlexLogsRetentionDays?: number | Computed<number>;
  /** The number of days logs are stored in Standard Tier before aging into the Flex Tier or being deleted from the index. The available values depend on retention plans specified in your organization's contract/subscriptions. */
  numRetentionDays?: number | Computed<number>;
  /** A list of tags associated with the index. Tags must be in `key:value` format. */
  tags?: string[] | Computed<string[]>;
}

export interface IndexAttrs {
  /** The number of log events you can send in this index per day before you are rate-limited. */
  dailyLimit: number;
  /** Object containing options to override the default daily limit reset time. */
  dailyLimitReset: Index_DailyLimitReset;
  /** A percentage threshold of the daily quota at which a Datadog warning event is generated. */
  dailyLimitWarningThresholdPercentage: number;
  /** An array of exclusion objects. The logs are tested against the query of each filter, following the order of the array. Only the first matching active exclusion matters, others (if any) are ignored. */
  exclusionFilters: Index_ExclusionFilters[];
  /** Filter for logs. */
  filter: Index_Filter;
  /** A boolean stating if the index is rate limited, meaning more logs than the daily limit have been sent. Rate limit is reset every-day at 2pm UTC. */
  isRateLimited: boolean;
  /** The name of the index. */
  name: string;
  /** The total number of days logs are stored in Standard and Flex Tier before being deleted from the index. If Standard Tier is enabled on this index, logs are first retained in Standard Tier for the number of days specified through `num_retention_days`, and then stored in Flex Tier until the number of days specified in `num_flex_logs_retention_days` is reached. The available values depend on retention plans specified in your organization's contract/subscriptions. */
  numFlexLogsRetentionDays: number;
  /** The number of days logs are stored in Standard Tier before aging into the Flex Tier or being deleted from the index. The available values depend on retention plans specified in your organization's contract/subscriptions. */
  numRetentionDays: number;
  /** A list of tags associated with the index. Tags must be in `key:value` format. */
  tags: string[];
}

export const Index: ResourceBinding<IndexConfig, IndexAttrs> = {
  wireType: "datadog_logs_index",
  fields: {
    dailyLimit: "daily_limit",
    dailyLimitReset: {
      wireName: "daily_limit_reset",
      kind: "object",
      fields: Index_DailyLimitResetFields,
    },
    dailyLimitWarningThresholdPercentage: "daily_limit_warning_threshold_percentage",
    exclusionFilters: {
      wireName: "exclusion_filters",
      kind: "list",
      fields: Index_ExclusionFiltersFields,
    },
    filter: {
      wireName: "filter",
      kind: "object",
      fields: Index_FilterFields,
    },
    name: "name",
    numFlexLogsRetentionDays: "num_flex_logs_retention_days",
    numRetentionDays: "num_retention_days",
    tags: "tags",
  },
};
