// Code generated by `ubx sdk gen` from datadog_restriction_query_without_relationships. DO NOT EDIT.
package restriction

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type QueryWithoutRelationships_Data_Attributes struct {
	CreatedAt         any
	LastModifierEmail any
	LastModifierName  any
	ModifiedAt        any
	RestrictionQuery  any
	RoleCount         any
	UserCount         any
}

type QueryWithoutRelationships_Data struct {
	Attributes any
	Id         any
	Type       any
}

type QueryWithoutRelationshipsConfig struct {
}

type QueryWithoutRelationshipsAttrs struct {
	// Array of returned restriction queries.
	Data any
}

var QueryWithoutRelationships = ubx.DataSourceBinding{
	WireType: "datadog_restriction_query_without_relationships",
	Fields:   ubx.FieldMap{},
}
