# Code generated by `ubx sdk gen` from datadog_web_integration_account_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class IntegrationAccountResponse_Data_Attributes:
    # A human-readable name for the account. Must be unique among accounts of the same integration.
    name: Any = None
    # Integration-specific secrets. The shape of this object varies by integration. Secrets are write-only and never returned by the API.
    secrets: Any = None
    # Integration-specific settings. The shape of this object varies by integration.
    settings: Any = None

@dataclasses.dataclass
class IntegrationAccountResponse_Data:
    # Attributes object for creating a web integration account.
    attributes: Any = None
    # The unique identifier of the web integration account.
    id: Any = None
    # Account resource type.
    type: Any = None

_IntegrationAccountResponse_Data_AttributesFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "secrets": ubx.FieldSpec(wire_name="secrets"),
    "settings": ubx.FieldSpec(wire_name="settings"),
}

_IntegrationAccountResponse_DataFields = {
    "attributes": ubx.FieldSpec(
        wire_name="attributes",
        kind="object",
        fields=_IntegrationAccountResponse_Data_AttributesFields,
    ),
    "id": ubx.FieldSpec(wire_name="id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class IntegrationAccountResponseConfig:
    # Data object for creating a web integration account.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    integration_name: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None

@dataclasses.dataclass
class IntegrationAccountResponseAttrs:
    # Data object for creating a web integration account.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    integration_name: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None

IntegrationAccountResponse = ubx.ResourceBinding(
    wire_type="datadog_web_integration_account_response",
    fields={
        "data": ubx.FieldSpec(
            wire_name="data",
            kind="object",
            fields=_IntegrationAccountResponse_DataFields,
        ),
        "integration_name": ubx.FieldSpec(wire_name="integration_name"),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
