// Code generated by `ubx sdk gen` from datadog_tag_indexing_rule_exemption_response. DO NOT EDIT.
package tag

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IndexingRuleExemptionResponse_Data_Attributes struct {
	// Timestamp when the exemption was created.
	CreatedAt any
	// Handle of the user who created the exemption.
	CreatedByHandle any
	// Discriminates between an explicit exemption (`exemption`) and a pre-existing legacy tag configuration acting as an implicit exclusion (`legacy_tag_configuration`).
	Kind any
	// The reason the metric is exempt from tag indexing rules.
	Reason any
}

type IndexingRuleExemptionResponse_Data struct {
	// Attributes of a tag indexing rule exemption.
	Attributes any
	// The metric name, used as the resource ID.
	Id any
	// The tag indexing rule exemption resource type.
	Type any
}

type IndexingRuleExemptionResponseConfig struct {
	MetricName any
}

type IndexingRuleExemptionResponseAttrs struct {
	// A tag indexing rule exemption resource object.
	Data any
	MetricName any
}

var IndexingRuleExemptionResponse = ubx.DataSourceBinding{
	WireType: "datadog_tag_indexing_rule_exemption_response",
	Fields: ubx.FieldMap{
		"MetricName": ubx.FieldSpec{WireName: "metric_name"},
	},
}
