// Code generated by `ubx sdk gen` from datadog_tag_indexing_rules_response. DO NOT EDIT.
package tag

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IndexingRulesResponse_Data_Attributes_Options_Data_DynamicTags struct {
	ExcludeNotQueriedWindowSeconds any
	ExcludeNotUsedInAssets any
	QueriedTagsWindowSeconds any
	RelatedAssetTags any
}

type IndexingRulesResponse_Data_Attributes_Options_Data_MetricMatch struct {
	IsQueried any
	NotQueried any
	NotUsedInAssets any
	QueriedWindowSeconds any
	UsedInAssets any
}

type IndexingRulesResponse_Data_Attributes_Options_Data struct {
	DynamicTags any
	ManagePreexistingMetrics any
	MetricMatch any
	OverridePreviousRules any
}

type IndexingRulesResponse_Data_Attributes_Options struct {
	Data any
	Version any
}

type IndexingRulesResponse_Data_Attributes struct {
	CreatedAt any
	CreatedByHandle any
	ExcludeTagsMode any
	IgnoredMetricNameMatches any
	MetricNameMatches any
	ModifiedAt any
	ModifiedByHandle any
	Name any
	Options any
	RuleOrder any
	Tags any
}

type IndexingRulesResponse_Data struct {
	Attributes any
	Id any
	Type any
}

type IndexingRulesResponse_Links struct {
	// Link to the first page.
	First any
	// Link to the last page.
	Last any
	// Link to the next page.
	Next any
	// Link to previous page.
	Prev any
	// Link to current page.
	Self any
}

type IndexingRulesResponse_Meta struct {
	// Total number of tag indexing rules in the org.
	Total any
}

type IndexingRulesResponseConfig struct {
	Search any
}

type IndexingRulesResponseAttrs struct {
	// Array of tag indexing rule objects.
	Data any
	// Pagination links. Only present if pagination query parameters were provided.
	Links any
	// Pagination metadata for a list of tag indexing rules.
	Meta any
	Search any
}

var IndexingRulesResponse = ubx.DataSourceBinding{
	WireType: "datadog_tag_indexing_rules_response",
	Fields: ubx.FieldMap{
		"Search": ubx.FieldSpec{WireName: "search"},
	},
}
