# Code generated by `ubx sdk gen` from datadog_ruleset_resp_array. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class RespArray_Data_Attributes_Created:
    nanos: Any = None
    seconds: Any = None

@dataclasses.dataclass
class RespArray_Data_Attributes_Rules_Mapping:
    destination_key: Any = None
    if_not_exists: Any = None
    if_tag_exists: Any = None
    source_keys: Any = None

@dataclasses.dataclass
class RespArray_Data_Attributes_Rules_Query_Addition:
    key: Any = None
    value: Any = None

@dataclasses.dataclass
class RespArray_Data_Attributes_Rules_Query:
    addition: Any = None
    case_insensitivity: Any = None
    if_not_exists: Any = None
    if_tag_exists: Any = None
    query: Any = None

@dataclasses.dataclass
class RespArray_Data_Attributes_Rules_ReferenceTable_FieldPairs:
    input_column: Any = None
    output_key: Any = None

@dataclasses.dataclass
class RespArray_Data_Attributes_Rules_ReferenceTable:
    case_insensitivity: Any = None
    field_pairs: Any = None
    if_not_exists: Any = None
    if_tag_exists: Any = None
    source_keys: Any = None
    table_name: Any = None

@dataclasses.dataclass
class RespArray_Data_Attributes_Rules:
    enabled: Any = None
    mapping: Any = None
    metadata: Any = None
    name: Any = None
    query: Any = None
    reference_table: Any = None

@dataclasses.dataclass
class RespArray_Data_Attributes:
    created: Any = None
    enabled: Any = None
    last_modified_user_uuid: Any = None
    modified: Any = None
    name: Any = None
    position: Any = None
    processing_status: Any = None
    rules: Any = None
    version: Any = None

@dataclasses.dataclass
class RespArray_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class RespArrayConfig:
    pass

@dataclasses.dataclass
class RespArrayAttrs:
    # The `RulesetRespArray` `data`.
    data: Any = None

RespArray = ubx.DataSourceBinding(
    wire_type="datadog_ruleset_resp_array",
    fields={
    },
)
