// Code generated by `ubx sdk gen` from datadog_get_blueprint_response. DO NOT EDIT.
package get

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type BlueprintResponse_Data_Attributes struct {
	// The timestamp when the blueprint was created.
	CreatedAt any
	// The app definition type.
	Definition any
	// A description of what the blueprint does.
	Description any
	// Embedded datastore blueprints.
	EmbeddedDatastoreBlueprints any
	// Embedded native actions.
	EmbeddedNativeActions any
	// Embedded workflow blueprints.
	EmbeddedWorkflowBlueprints any
	// The integration ID associated with the blueprint.
	IntegrationId any
	// Mocked outputs for testing the blueprint.
	MockedOutputs any
	// The human-readable name of the blueprint.
	Name any
	// The unique slug identifier of the blueprint.
	Slug any
	// Tags associated with the blueprint.
	Tags any
	// The background style of the blueprint tile.
	TileBackground any
	// The fully qualified name of the action used as the tile icon.
	TileIconActionFqn any
	// The timestamp when the blueprint was last updated.
	UpdatedAt any
}

type BlueprintResponse_Data struct {
	// The attributes of a blueprint resource.
	Attributes any
	// The ID of the blueprint.
	Id any
	// The resource type for a blueprint.
	Type any
}

type BlueprintResponseConfig struct {
	BlueprintId any
}

type BlueprintResponseAttrs struct {
	BlueprintId any
	// A blueprint resource.
	Data any
}

var BlueprintResponse = ubx.DataSourceBinding{
	WireType: "datadog_get_blueprint_response",
	Fields: ubx.FieldMap{
		"BlueprintId": ubx.FieldSpec{WireName: "blueprint_id"},
	},
}
