// Code generated by `ubx sdk gen` from datadog_get_finding_response. DO NOT EDIT.
package get

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FindingResponse_Data_Attributes_Mute struct {
	// Additional information about the reason why this finding is muted or unmuted.
	Description any
	// The expiration date of the mute or unmute action (Unix ms).
	ExpirationDate any
	// Whether this finding is muted or unmuted.
	Muted any
	// The reason why this finding is muted or unmuted.
	Reason any
	// The start of the mute period.
	StartDate any
	// The ID of the user who muted or unmuted this finding.
	Uuid any
}

type FindingResponse_Data_Attributes_Rule struct {
	// The ID of the rule that triggered this finding.
	Id any
	// The name of the rule that triggered this finding.
	Name any
}

type FindingResponse_Data_Attributes struct {
	// The evaluation of the finding.
	Evaluation any
	// The date on which the evaluation for this finding changed (Unix ms).
	EvaluationChangedAt any
	// The remediation message for this finding.
	Message any
	// Information about the mute status of this finding.
	Mute any
	// The resource name of this finding.
	Resource any
	// The resource configuration for this finding.
	ResourceConfiguration any
	// The date on which the resource was discovered (Unix ms).
	ResourceDiscoveryDate any
	// The resource type of this finding.
	ResourceType any
	// The rule that triggered this finding.
	Rule any
	// The status of the finding.
	Status any
	// The tags associated with this finding.
	Tags any
}

type FindingResponse_Data struct {
	// The JSON:API attributes of the detailed finding.
	Attributes any
	// The unique ID for this finding.
	Id any
	// The JSON:API type for findings that have the message and resource configuration.
	Type any
}

type FindingResponseConfig struct {
	FindingId         any
	SnapshotTimestamp any
}

type FindingResponseAttrs struct {
	// A single finding with with message and resource configuration.
	Data              any
	FindingId         any
	SnapshotTimestamp any
}

var FindingResponse = ubx.DataSourceBinding{
	WireType: "datadog_get_finding_response",
	Fields: ubx.FieldMap{
		"FindingId":         ubx.FieldSpec{WireName: "finding_id"},
		"SnapshotTimestamp": ubx.FieldSpec{WireName: "snapshot_timestamp"},
	},
}
