// Code generated by `ubx sdk gen` from datadog_case_view_list. DO NOT EDIT.
package case_

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ViewList_Data_Attributes struct {
	CreatedAt  any
	ModifiedAt any
	Name       any
	NpRuleId   any
	Query      any
}

type ViewList_Data_Relationships_CreatedBy_Data struct {
	Id   any
	Type any
}

type ViewList_Data_Relationships_CreatedBy struct {
	Data any
}

type ViewList_Data_Relationships struct {
	CreatedBy  any
	ModifiedBy any
	Project    any
}

type ViewList_Data struct {
	Attributes    any
	Id            any
	Relationships any
	Type          any
}

type ViewListConfig struct {
	ProjectId any
}

type ViewListAttrs struct {
	// A list of case views.
	Data      any
	ProjectId any
}

var ViewList = ubx.DataSourceBinding{
	WireType: "datadog_case_view_list",
	Fields: ubx.FieldMap{
		"ProjectId": ubx.FieldSpec{WireName: "project_id"},
	},
}
