// Code generated by `ubx sdk gen` from datadog_shift_included_list. DO NOT EDIT.
package shift

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IncludedList_Data_Attributes struct {
	// The end time of the shift.
	End any
	// The start time of the shift.
	Start any
}

type IncludedList_Data_Relationships_User_Data struct {
	// Specifies the unique identifier of the user.
	Id any
	// Indicates that the related resource is of type 'users'.
	Type any
}

type IncludedList_Data_Relationships_User struct {
	// Represents a reference to the user assigned to this shift, containing the user's ID and resource type.
	Data any
}

type IncludedList_Data_Relationships struct {
	// Defines the relationship between a shift and the user who is working that shift.
	User any
}

type IncludedList_Data struct {
	// Attributes for an on-call shift.
	Attributes any
	// The `ShiftData` `id`.
	Id any
	// Relationships for an on-call shift.
	Relationships any
	// Indicates that the resource is of type 'shifts'.
	Type any
}

type IncludedList_Included_Attributes struct {
	Email any
	Name any
	Status any
}

type IncludedList_Included struct {
	Attributes any
	Id any
	Type any
}

type IncludedListConfig struct {
	Include any
	ScheduleId any
}

type IncludedListAttrs struct {
	// Data for an on-call shift.
	Data any
	Include any
	// The `Shift` `included`.
	Included any
	ScheduleId any
}

var IncludedList = ubx.DataSourceBinding{
	WireType: "datadog_shift_included_list",
	Fields: ubx.FieldMap{
		"Include": ubx.FieldSpec{WireName: "include"},
		"ScheduleId": ubx.FieldSpec{WireName: "schedule_id"},
	},
}
