// Code generated by `ubx sdk gen` from datadog_ociconfigs_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Response_Data_Attributes {
  accountId?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  errorMessages?: string[] | Computed<string[]>;
  status?: string | Computed<string>;
  statusUpdatedAt?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface Response_Data {
  attributes?: Response_Data_Attributes | Computed<Response_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ResponseConfig {
}

export interface ResponseAttrs {
  /** An OCI config. */
  data: Response_Data[];
}

export const Response: DataSourceBinding<ResponseConfig, ResponseAttrs> = {
  wireType: "datadog_ociconfigs_response",
  fields: {
  },
};
