// Code generated by `ubx sdk gen` from datadog_ai_custom_rule_revision_response_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CustomRuleRevisionResponseData_Data_Attributes {
  category?: string | Computed<string>;
  checksum?: string | Computed<string>;
  content?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  cwe?: string | Computed<string>;
  description?: string | Computed<string>;
  directories?: string[] | Computed<string[]>;
  executionMode?: string | Computed<string>;
  globs?: string[] | Computed<string[]>;
  isDefault?: boolean | Computed<boolean>;
  isPublished?: boolean | Computed<boolean>;
  isTesting?: boolean | Computed<boolean>;
  severity?: string | Computed<string>;
  shortDescription?: string | Computed<string>;
  versionId?: number | Computed<number>;
}

export interface CustomRuleRevisionResponseData_Data {
  attributes?: CustomRuleRevisionResponseData_Data_Attributes | Computed<CustomRuleRevisionResponseData_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface CustomRuleRevisionResponseDataConfig {
  ruleName: string | Computed<string>;
  rulesetName: string | Computed<string>;
}

export interface CustomRuleRevisionResponseDataAttrs {
  /** The list of AI custom rule revisions. */
  data: CustomRuleRevisionResponseData_Data[];
  ruleName: string;
  rulesetName: string;
}

export const CustomRuleRevisionResponseData: DataSourceBinding<CustomRuleRevisionResponseDataConfig, CustomRuleRevisionResponseDataAttrs> = {
  wireType: "datadog_ai_custom_rule_revision_response_data",
  fields: {
    ruleName: "rule_name",
    rulesetName: "ruleset_name",
  },
};
