// Code generated by `ubx sdk gen` from datadog_host_tags. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface TagsConfig {
  /** Your host name. */
  host?: string | Computed<string>;
  /** A list of tags associated with a host. */
  tags?: string[] | Computed<string[]>;
  /** path parameter, not part of the API's own resource representation */
  hostName: string | Computed<string>;
}

export interface TagsAttrs {
  /** Your host name. */
  host: string;
  /** A list of tags associated with a host. */
  tags: string[];
  /** path parameter, not part of the API's own resource representation */
  hostName: string;
}

export const Tags: ResourceBinding<TagsConfig, TagsAttrs> = {
  wireType: "datadog_host_tags",
  fields: {
    host: "host",
    tags: "tags",
    hostName: "host_name",
  },
};
