# Code generated by `ubx sdk gen` from datadog_confluent_resources_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ResourcesResponse_Data_Attributes:
    enable_custom_metrics: Any = None
    id: Any = None
    resource_type: Any = None
    tags: Any = None

@dataclasses.dataclass
class ResourcesResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class ResourcesResponseConfig:
    account_id: Any = None

@dataclasses.dataclass
class ResourcesResponseAttrs:
    account_id: Any = None
    # The JSON:API data attribute.
    data: Any = None

ResourcesResponse = ubx.DataSourceBinding(
    wire_type="datadog_confluent_resources_response",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
