// Code generated by `ubx sdk gen` from datadog_dashboard_list. DO NOT EDIT.
package dashboard

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type List_DashboardLists_Author struct {
	Email any
	Handle any
	Name any
}

type List_DashboardLists struct {
	Author any
	Created any
	DashboardCount any
	Id any
	IsFavorite any
	Modified any
	Name any
	Type any
}

type ListConfig struct {
}

type ListAttrs struct {
	// List of all your dashboard lists.
	DashboardLists any
}

var List = ubx.DataSourceBinding{
	WireType: "datadog_dashboard_list",
	Fields: ubx.FieldMap{
	},
}
