// Code generated by `ubx sdk gen` from datadog_on_call_notification_rule. DO NOT EDIT.
package on

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type CallNotificationRule_Data_Attributes_ChannelSettings struct {
	Method any
	Type   any
}

type CallNotificationRule_Data_Attributes struct {
	// Specifies the category a notification rule will apply to
	Category any
	// Defines the configuration for a channel associated with a notification rule
	ChannelSettings any
	// The number of minutes that will elapse before this rule is evaluated. 0 indicates immediate evaluation
	DelayMinutes any
}

type CallNotificationRule_Data_Relationships_Channel_Data struct {
	// ID of the notification channel
	Id any
	// Indicates that the resource is of type 'notification_channels'.
	Type any
}

type CallNotificationRule_Data_Relationships_Channel struct {
	// Channel relationship data for creating a notification rule
	Data any
}

type CallNotificationRule_Data_Relationships struct {
	// Relationship object for creating a notification rule
	Channel any
}

type CallNotificationRule_Data struct {
	// Attributes for creating or modifying an on-call notification rule.
	Attributes any
	// Unique identifier for the rule
	Id any
	// Relationship object for creating a notification rule
	Relationships any
	// Indicates that the resource is of type 'notification_rules'.
	Type any
}

type CallNotificationRule_Included_Attributes_Config struct {
	Address         any
	ApplicationName any
	DeviceName      any
	Formats         any
	FormattedNumber any
	Number          any
	Region          any
	SmsSubscribedAt any
	Type            any
	Verified        any
}

type CallNotificationRule_Included_Attributes struct {
	Active any
	Config any
}

type CallNotificationRule_Included struct {
	Attributes any
	Id         any
	Type       any
}

var CallNotificationRule_Data_Attributes_ChannelSettingsFields = ubx.FieldMap{
	"Method": ubx.FieldSpec{WireName: "method"},
	"Type":   ubx.FieldSpec{WireName: "type"},
}

var CallNotificationRule_Data_AttributesFields = ubx.FieldMap{
	"Category": ubx.FieldSpec{WireName: "category"},
	"ChannelSettings": ubx.FieldSpec{
		WireName: "channel_settings",
		Kind:     "object",
		Fields:   CallNotificationRule_Data_Attributes_ChannelSettingsFields,
	},
	"DelayMinutes": ubx.FieldSpec{WireName: "delay_minutes"},
}

var CallNotificationRule_Data_Relationships_Channel_DataFields = ubx.FieldMap{
	"Id":   ubx.FieldSpec{WireName: "id"},
	"Type": ubx.FieldSpec{WireName: "type"},
}

var CallNotificationRule_Data_Relationships_ChannelFields = ubx.FieldMap{
	"Data": ubx.FieldSpec{
		WireName: "data",
		Kind:     "object",
		Fields:   CallNotificationRule_Data_Relationships_Channel_DataFields,
	},
}

var CallNotificationRule_Data_RelationshipsFields = ubx.FieldMap{
	"Channel": ubx.FieldSpec{
		WireName: "channel",
		Kind:     "object",
		Fields:   CallNotificationRule_Data_Relationships_ChannelFields,
	},
}

var CallNotificationRule_DataFields = ubx.FieldMap{
	"Attributes": ubx.FieldSpec{
		WireName: "attributes",
		Kind:     "object",
		Fields:   CallNotificationRule_Data_AttributesFields,
	},
	"Id": ubx.FieldSpec{WireName: "id"},
	"Relationships": ubx.FieldSpec{
		WireName: "relationships",
		Kind:     "object",
		Fields:   CallNotificationRule_Data_RelationshipsFields,
	},
	"Type": ubx.FieldSpec{WireName: "type"},
}

type CallNotificationRuleConfig struct {
	// Data for creating an on-call notification rule
	Data any
	// path parameter, not part of the API's own resource representation
	UserId any
	// path parameter, not part of the API's own resource representation
	RuleId any
}

type CallNotificationRuleAttrs struct {
	// Data for creating an on-call notification rule
	Data     any
	Included any
	// path parameter, not part of the API's own resource representation
	UserId any
	// path parameter, not part of the API's own resource representation
	RuleId any
}

var CallNotificationRule = ubx.ResourceBinding{
	WireType: "datadog_on_call_notification_rule",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind:     "object",
			Fields:   CallNotificationRule_DataFields,
		},
		"UserId": ubx.FieldSpec{WireName: "user_id"},
		"RuleId": ubx.FieldSpec{WireName: "rule_id"},
	},
}
