// Code generated by `ubx sdk gen` from datadog_control_notification_settings_response. DO NOT EDIT.
package control

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type NotificationSettingsResponse_Data_Attributes_EventSettings_Targets struct {
	Handle any
	Type   any
}

type NotificationSettingsResponse_Data_Attributes_EventSettings struct {
	Enabled   any
	EventType any
	Targets   any
}

type NotificationSettingsResponse_Data_Attributes struct {
	// The notification settings for each supported event type on the control.
	EventSettings any
}

type NotificationSettingsResponse_Data struct {
	// The attributes of a governance control's notification settings.
	Attributes any
	// The detection type the notification settings apply to.
	Id any
	// Control notification settings resource type.
	Type any
}

type NotificationSettingsResponseConfig struct {
	DetectionType any
}

type NotificationSettingsResponseAttrs struct {
	// A control notification settings resource.
	Data          any
	DetectionType any
}

var NotificationSettingsResponse = ubx.DataSourceBinding{
	WireType: "datadog_control_notification_settings_response",
	Fields: ubx.FieldMap{
		"DetectionType": ubx.FieldSpec{WireName: "detection_type"},
	},
}
