# Code generated by `ubx sdk gen` from datadog_sast_rulesets_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class RulesetsResponse_Data_Attributes_Rules_Arguments:
    description: Any = None
    name: Any = None

@dataclasses.dataclass
class RulesetsResponse_Data_Attributes_Rules_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class RulesetsResponse_Data_Attributes_Rules_Tests:
    annotation_count: Any = None
    code: Any = None
    filename: Any = None

@dataclasses.dataclass
class RulesetsResponse_Data_Attributes_Rules:
    arguments: Any = None
    category: Any = None
    checksum: Any = None
    code: Any = None
    created_at: Any = None
    created_by: Any = None
    cve: Any = None
    cwe: Any = None
    data: Any = None
    description: Any = None
    documentation_url: Any = None
    entity_checked: Any = None
    is_published: Any = None
    is_testing: Any = None
    language: Any = None
    last_updated_at: Any = None
    last_updated_by: Any = None
    name: Any = None
    regex: Any = None
    severity: Any = None
    short_description: Any = None
    should_use_ai_fix: Any = None
    tests: Any = None
    tree_sitter_query: Any = None
    type: Any = None

@dataclasses.dataclass
class RulesetsResponse_Data_Attributes:
    description: Any = None
    name: Any = None
    rules: Any = None
    short_description: Any = None

@dataclasses.dataclass
class RulesetsResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class RulesetsResponseConfig:
    pass

@dataclasses.dataclass
class RulesetsResponseAttrs:
    # The list of SAST rulesets returned in the response.
    data: Any = None

RulesetsResponse = ubx.DataSourceBinding(
    wire_type="datadog_sast_rulesets_response",
    fields={
    },
)
