// Code generated by `ubx sdk gen` from datadog_notebook_response. DO NOT EDIT.
package notebook

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Response_Data_Attributes_Author struct {
	// Creation time of the user.
	CreatedAt any
	// Whether the user is disabled.
	Disabled any
	// Email of the user.
	Email any
	// Handle of the user.
	Handle any
	// URL of the user's icon.
	Icon any
	// Name of the user.
	Name any
	// Status of the user.
	Status any
	// Title of the user.
	Title any
	// Whether the user is verified.
	Verified any
}

type Response_Data_Attributes_Cells_Attributes_Definition struct {
	Text any
	Type any
}

type Response_Data_Attributes_Cells_Attributes_SplitBy struct {
	Keys any
	Tags any
}

type Response_Data_Attributes_Cells_Attributes_Time struct {
	End      any
	Live     any
	LiveSpan any
	Start    any
}

type Response_Data_Attributes_Cells_Attributes struct {
	Definition any
	GraphSize  any
	SplitBy    any
	Time       any
}

type Response_Data_Attributes_Cells struct {
	Attributes any
	Type       any
}

type Response_Data_Attributes_Metadata struct {
	// Whether or not the notebook is a template.
	IsTemplate any
	// Whether or not the notebook takes snapshot image backups of the notebook's fixed-time graphs.
	TakeSnapshots any
	// Metadata type of the notebook.
	Type any
}

type Response_Data_Attributes_TemplateVariables_AvailableValuesQuery_GroupBy struct {
	Facet any
}

type Response_Data_Attributes_TemplateVariables_AvailableValuesQuery_Search struct {
	Query any
}

type Response_Data_Attributes_TemplateVariables_AvailableValuesQuery struct {
	DataSource any
	GroupBy    any
	Query      any
	Search     any
}

type Response_Data_Attributes_TemplateVariables struct {
	AvailableValues      any
	AvailableValuesQuery any
	DataSourceMappings   any
	Default              any
	Defaults             any
	Name                 any
	Placement            any
	Prefix               any
	Type                 any
}

type Response_Data_Attributes struct {
	// Attributes of user object returned by the API.
	Author any
	// List of cells to display in the notebook.
	Cells any
	// UTC time stamp for when the notebook was created.
	Created any
	// Metadata associated with the notebook.
	Metadata any
	// UTC time stamp for when the notebook was last modified.
	Modified any
	// The name of the notebook.
	Name any
	// Publication status of the notebook. For now, always "published".
	Status any
	// List of template variables for this notebook.
	TemplateVariables any
	// Notebook global timeframe.
	Time any
}

type Response_Data struct {
	// The data attributes of a notebook.
	Attributes any
	// Unique notebook ID, assigned when you create the notebook.
	Id any
	// Type of the Notebook resource.
	Type any
}

var Response_Data_Attributes_AuthorFields = ubx.FieldMap{
	"CreatedAt": ubx.FieldSpec{WireName: "created_at"},
	"Disabled":  ubx.FieldSpec{WireName: "disabled"},
	"Email":     ubx.FieldSpec{WireName: "email"},
	"Handle":    ubx.FieldSpec{WireName: "handle"},
	"Icon":      ubx.FieldSpec{WireName: "icon"},
	"Name":      ubx.FieldSpec{WireName: "name"},
	"Status":    ubx.FieldSpec{WireName: "status"},
	"Title":     ubx.FieldSpec{WireName: "title"},
	"Verified":  ubx.FieldSpec{WireName: "verified"},
}

var Response_Data_Attributes_Cells_Attributes_DefinitionFields = ubx.FieldMap{
	"Text": ubx.FieldSpec{WireName: "text"},
	"Type": ubx.FieldSpec{WireName: "type"},
}

var Response_Data_Attributes_Cells_Attributes_SplitByFields = ubx.FieldMap{
	"Keys": ubx.FieldSpec{WireName: "keys"},
	"Tags": ubx.FieldSpec{WireName: "tags"},
}

var Response_Data_Attributes_Cells_Attributes_TimeFields = ubx.FieldMap{
	"End":      ubx.FieldSpec{WireName: "end"},
	"Live":     ubx.FieldSpec{WireName: "live"},
	"LiveSpan": ubx.FieldSpec{WireName: "live_span"},
	"Start":    ubx.FieldSpec{WireName: "start"},
}

var Response_Data_Attributes_Cells_AttributesFields = ubx.FieldMap{
	"Definition": ubx.FieldSpec{
		WireName: "definition",
		Kind:     "object",
		Fields:   Response_Data_Attributes_Cells_Attributes_DefinitionFields,
	},
	"GraphSize": ubx.FieldSpec{WireName: "graph_size"},
	"SplitBy": ubx.FieldSpec{
		WireName: "split_by",
		Kind:     "object",
		Fields:   Response_Data_Attributes_Cells_Attributes_SplitByFields,
	},
	"Time": ubx.FieldSpec{
		WireName: "time",
		Kind:     "object",
		Fields:   Response_Data_Attributes_Cells_Attributes_TimeFields,
	},
}

var Response_Data_Attributes_CellsFields = ubx.FieldMap{
	"Attributes": ubx.FieldSpec{
		WireName: "attributes",
		Kind:     "object",
		Fields:   Response_Data_Attributes_Cells_AttributesFields,
	},
	"Type": ubx.FieldSpec{WireName: "type"},
}

var Response_Data_Attributes_MetadataFields = ubx.FieldMap{
	"IsTemplate":    ubx.FieldSpec{WireName: "is_template"},
	"TakeSnapshots": ubx.FieldSpec{WireName: "take_snapshots"},
	"Type":          ubx.FieldSpec{WireName: "type"},
}

var Response_Data_Attributes_TemplateVariables_AvailableValuesQuery_GroupByFields = ubx.FieldMap{
	"Facet": ubx.FieldSpec{WireName: "facet"},
}

var Response_Data_Attributes_TemplateVariables_AvailableValuesQuery_SearchFields = ubx.FieldMap{
	"Query": ubx.FieldSpec{WireName: "query"},
}

var Response_Data_Attributes_TemplateVariables_AvailableValuesQueryFields = ubx.FieldMap{
	"DataSource": ubx.FieldSpec{WireName: "data_source"},
	"GroupBy": ubx.FieldSpec{
		WireName: "group_by",
		Kind:     "list",
		Fields:   Response_Data_Attributes_TemplateVariables_AvailableValuesQuery_GroupByFields,
	},
	"Query": ubx.FieldSpec{WireName: "query"},
	"Search": ubx.FieldSpec{
		WireName: "search",
		Kind:     "object",
		Fields:   Response_Data_Attributes_TemplateVariables_AvailableValuesQuery_SearchFields,
	},
}

var Response_Data_Attributes_TemplateVariablesFields = ubx.FieldMap{
	"AvailableValues": ubx.FieldSpec{WireName: "available_values"},
	"AvailableValuesQuery": ubx.FieldSpec{
		WireName: "available_values_query",
		Kind:     "object",
		Fields:   Response_Data_Attributes_TemplateVariables_AvailableValuesQueryFields,
	},
	"DataSourceMappings": ubx.FieldSpec{WireName: "data_source_mappings"},
	"Default":            ubx.FieldSpec{WireName: "default"},
	"Defaults":           ubx.FieldSpec{WireName: "defaults"},
	"Name":               ubx.FieldSpec{WireName: "name"},
	"Placement":          ubx.FieldSpec{WireName: "placement"},
	"Prefix":             ubx.FieldSpec{WireName: "prefix"},
	"Type":               ubx.FieldSpec{WireName: "type"},
}

var Response_Data_AttributesFields = ubx.FieldMap{
	"Author": ubx.FieldSpec{
		WireName: "author",
		Kind:     "object",
		Fields:   Response_Data_Attributes_AuthorFields,
	},
	"Cells": ubx.FieldSpec{
		WireName: "cells",
		Kind:     "list",
		Fields:   Response_Data_Attributes_CellsFields,
	},
	"Created": ubx.FieldSpec{WireName: "created"},
	"Metadata": ubx.FieldSpec{
		WireName: "metadata",
		Kind:     "object",
		Fields:   Response_Data_Attributes_MetadataFields,
	},
	"Modified": ubx.FieldSpec{WireName: "modified"},
	"Name":     ubx.FieldSpec{WireName: "name"},
	"Status":   ubx.FieldSpec{WireName: "status"},
	"TemplateVariables": ubx.FieldSpec{
		WireName: "template_variables",
		Kind:     "list",
		Fields:   Response_Data_Attributes_TemplateVariablesFields,
	},
	"Time": ubx.FieldSpec{
		WireName: "time",
		Kind:     "object",
		Fields:   Response_Data_Attributes_Cells_Attributes_TimeFields,
	},
}

var Response_DataFields = ubx.FieldMap{
	"Attributes": ubx.FieldSpec{
		WireName: "attributes",
		Kind:     "object",
		Fields:   Response_Data_AttributesFields,
	},
	"Id":   ubx.FieldSpec{WireName: "id"},
	"Type": ubx.FieldSpec{WireName: "type"},
}

type ResponseConfig struct {
	// The data for a notebook create request.
	Data any
	// path parameter, not part of the API's own resource representation
	NotebookId any
}

type ResponseAttrs struct {
	// The data for a notebook create request.
	Data any
	// path parameter, not part of the API's own resource representation
	NotebookId any
}

var Response = ubx.ResourceBinding{
	WireType: "datadog_notebook_response",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind:     "object",
			Fields:   Response_DataFields,
		},
		"NotebookId": ubx.FieldSpec{WireName: "notebook_id"},
	},
}
