// Code generated by `ubx sdk gen` from datadog_service_now_template_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface NowTemplateResponse_Data_Attributes {
  /** The ID of the assignment group */
  assignmentGroupId?: string | Computed<string>;
  /** The ID of the business service */
  businessServiceId?: string | Computed<string>;
  /** Custom field mappings for the template */
  fieldsMapping?: Record<string, string> | Computed<Record<string, string>>;
  /** The handle name of the template */
  handleName: string | Computed<string>;
  /** The ID of the ServiceNow instance */
  instanceId: string | Computed<string>;
  /** The name of the destination ServiceNow table */
  servicenowTablename: string | Computed<string>;
  /** The ID of the user */
  userId?: string | Computed<string>;
}

export interface NowTemplateResponse_Data {
  /** Attributes for creating a ServiceNow template */
  attributes: NowTemplateResponse_Data_Attributes | Computed<NowTemplateResponse_Data_Attributes>;
  /** Unique identifier for the ServiceNow template */
  id?: string | Computed<string>;
  /** Type identifier for ServiceNow template resources */
  type: string | Computed<string>;
}

const NowTemplateResponse_Data_AttributesFields: FieldMap = {
  assignmentGroupId: "assignment_group_id",
  businessServiceId: "business_service_id",
  fieldsMapping: "fields_mapping",
  handleName: "handle_name",
  instanceId: "instance_id",
  servicenowTablename: "servicenow_tablename",
  userId: "user_id",
};

const NowTemplateResponse_DataFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: NowTemplateResponse_Data_AttributesFields,
  },
  id: "id",
  type: "type",
};

export interface NowTemplateResponseConfig {
  /** Data object for creating a ServiceNow template */
  data: NowTemplateResponse_Data | Computed<NowTemplateResponse_Data>;
  /** path parameter, not part of the API's own resource representation */
  templateId: string | Computed<string>;
}

export interface NowTemplateResponseAttrs {
  /** Data object for creating a ServiceNow template */
  data: NowTemplateResponse_Data;
  /** path parameter, not part of the API's own resource representation */
  templateId: string;
}

export const NowTemplateResponse: ResourceBinding<NowTemplateResponseConfig, NowTemplateResponseAttrs> = {
  wireType: "datadog_service_now_template_response",
  fields: {
    data: {
      wireName: "data",
      kind: "object",
      fields: NowTemplateResponse_DataFields,
    },
    templateId: "template_id",
  },
};
