// Code generated by `ubx sdk gen` from datadog_model_lab_run_artifacts_response. DO NOT EDIT.
package model

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type LabRunArtifactsResponse_Data_Attributes_Files struct {
	FileSize any
	IsDir    any
	Path     any
}

type LabRunArtifactsResponse_Data_Attributes struct {
	// The list of artifact files and directories.
	Files any
	// The path of the run's artifacts relative to the project's artifact root.
	PathInProject any
}

type LabRunArtifactsResponse_Data struct {
	// Artifact listing for a Model Lab run.
	Attributes any
	// The unique identifier of the artifacts resource.
	Id any
	// The JSON:API type for a run artifacts resource.
	Type any
}

type LabRunArtifactsResponseConfig struct {
	Path  any
	RunId any
}

type LabRunArtifactsResponseAttrs struct {
	// A run artifacts JSON:API resource object.
	Data  any
	Path  any
	RunId any
}

var LabRunArtifactsResponse = ubx.DataSourceBinding{
	WireType: "datadog_model_lab_run_artifacts_response",
	Fields: ubx.FieldMap{
		"Path":  ubx.FieldSpec{WireName: "path"},
		"RunId": ubx.FieldSpec{WireName: "run_id"},
	},
}
