// Code generated by `ubx sdk gen` from datadog_governance_control_detection_data_list. DO NOT EDIT.
package governance

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ControlDetectionDataList_Data_Attributes struct {
	AssignedTeam     any
	AssignedTo       any
	AssignmentSource any
	ControlId        any
	CreatedAt        any
	DetectionType    any
	DisplayName      any
	ExceptionAt      any
	ExceptionBy      any
	Metadata         any
	MitigateAfter    any
	MitigatedAt      any
	Priority         any
	ResourceId       any
	ResourceType     any
	State            any
}

type ControlDetectionDataList_Data struct {
	Attributes any
	Id         any
	Type       any
}

type ControlDetectionDataListConfig struct {
	DetectionType any
	Sort          any
}

type ControlDetectionDataListAttrs struct {
	// An array of governance control detection resources.
	Data          any
	DetectionType any
	Sort          any
}

var ControlDetectionDataList = ubx.DataSourceBinding{
	WireType: "datadog_governance_control_detection_data_list",
	Fields: ubx.FieldMap{
		"DetectionType": ubx.FieldSpec{WireName: "detection_type"},
		"Sort":          ubx.FieldSpec{WireName: "sort"},
	},
}
