# Code generated by `ubx sdk gen` from datadog_org_config_get_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ConfigGetResponse_Data_Attributes:
    # The description of an Org Config.
    description: Any = None
    # The timestamp of the last Org Config update (if any).
    modified_at: Any = None
    # The machine-friendly name of an Org Config.
    name: Any = None
    # The value of an Org Config.
    value: Any = None
    # The type of an Org Config value.
    value_type: Any = None

@dataclasses.dataclass
class ConfigGetResponse_Data:
    # Readable attributes of an Org Config.
    attributes: Any = None
    # A unique identifier for an Org Config.
    id: Any = None
    # Data type of an Org Config.
    type: Any = None

@dataclasses.dataclass
class ConfigGetResponseConfig:
    org_config_name: Any = None

@dataclasses.dataclass
class ConfigGetResponseAttrs:
    # A single Org Config.
    data: Any = None
    org_config_name: Any = None

ConfigGetResponse = ubx.DataSourceBinding(
    wire_type="datadog_org_config_get_response",
    fields={
        "org_config_name": ubx.FieldSpec(wire_name="org_config_name"),
    },
)
