// Code generated by `ubx sdk gen` from datadog_microsoft_teams_tenant_based_handle_info_response_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TeamsTenantBasedHandleInfoResponseData_Data_Attributes {
  channelId?: string | Computed<string>;
  channelName?: string | Computed<string>;
  name?: string | Computed<string>;
  teamId?: string | Computed<string>;
  teamName?: string | Computed<string>;
  tenantId?: string | Computed<string>;
  tenantName?: string | Computed<string>;
}

export interface TeamsTenantBasedHandleInfoResponseData_Data {
  attributes?: TeamsTenantBasedHandleInfoResponseData_Data_Attributes | Computed<TeamsTenantBasedHandleInfoResponseData_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface TeamsTenantBasedHandleInfoResponseDataConfig {
  name?: string | Computed<string>;
  tenantId?: string | Computed<string>;
}

export interface TeamsTenantBasedHandleInfoResponseDataAttrs {
  /** An array of tenant-based handles. */
  data: TeamsTenantBasedHandleInfoResponseData_Data[];
  name: string;
  tenantId: string;
}

export const TeamsTenantBasedHandleInfoResponseData: DataSourceBinding<TeamsTenantBasedHandleInfoResponseDataConfig, TeamsTenantBasedHandleInfoResponseDataAttrs> = {
  wireType: "datadog_microsoft_teams_tenant_based_handle_info_response_data",
  fields: {
    name: "name",
    tenantId: "tenant_id",
  },
};
