// Code generated by `ubx sdk gen` from datadog_microsoft_teams_workflows_webhook_handle_response_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TeamsWorkflowsWebhookHandleResponseData_Data_Attributes {
  name?: string | Computed<string>;
}

export interface TeamsWorkflowsWebhookHandleResponseData_Data {
  attributes?: TeamsWorkflowsWebhookHandleResponseData_Data_Attributes | Computed<TeamsWorkflowsWebhookHandleResponseData_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface TeamsWorkflowsWebhookHandleResponseDataConfig {
  name?: string | Computed<string>;
}

export interface TeamsWorkflowsWebhookHandleResponseDataAttrs {
  /** An array of Workflows webhook handles. */
  data: TeamsWorkflowsWebhookHandleResponseData_Data[];
  name: string;
}

export const TeamsWorkflowsWebhookHandleResponseData: DataSourceBinding<TeamsWorkflowsWebhookHandleResponseDataConfig, TeamsWorkflowsWebhookHandleResponseDataAttrs> = {
  wireType: "datadog_microsoft_teams_workflows_webhook_handle_response_data",
  fields: {
    name: "name",
  },
};
