# Code generated by `ubx sdk gen` from datadog_metric_volumes_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VolumesResponse_Data_Attributes:
    distinct_volume: Any = None

@dataclasses.dataclass
class VolumesResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class VolumesResponseConfig:
    metric_name: Any = None

@dataclasses.dataclass
class VolumesResponseAttrs:
    # Possible response objects for a metric's volume.
    data: Any = None
    metric_name: Any = None

VolumesResponse = ubx.DataSourceBinding(
    wire_type="datadog_metric_volumes_response",
    fields={
        "metric_name": ubx.FieldSpec(wire_name="metric_name"),
    },
)
