# Code generated by `ubx sdk gen` from datadog_slack_integration_channel. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class IntegrationChannel_Display:
    # Show the main body of the alert event.
    message: Any = None
    # Show interactive buttons to mute the alerting monitor.
    mute_buttons: Any = None
    # Show the list of @-handles in the alert event.
    notified: Any = None
    # Show the alert event's snapshot image.
    snapshot: Any = None
    # Show the scopes on which the monitor alerted.
    tags: Any = None

_IntegrationChannel_DisplayFields = {
    "message": ubx.FieldSpec(wire_name="message"),
    "mute_buttons": ubx.FieldSpec(wire_name="mute_buttons"),
    "notified": ubx.FieldSpec(wire_name="notified"),
    "snapshot": ubx.FieldSpec(wire_name="snapshot"),
    "tags": ubx.FieldSpec(wire_name="tags"),
}

@dataclasses.dataclass
class IntegrationChannelConfig:
    # Configuration options for what is shown in an alert event message.
    display: Any = None
    # Your channel name.
    name: Any = None
    # path parameter, not part of the API's own resource representation
    account_name: Any = None
    # path parameter, not part of the API's own resource representation
    channel_name: Any = None

@dataclasses.dataclass
class IntegrationChannelAttrs:
    # Configuration options for what is shown in an alert event message.
    display: Any = None
    # Your channel name.
    name: Any = None
    # path parameter, not part of the API's own resource representation
    account_name: Any = None
    # path parameter, not part of the API's own resource representation
    channel_name: Any = None

IntegrationChannel = ubx.ResourceBinding(
    wire_type="datadog_slack_integration_channel",
    fields={
        "display": ubx.FieldSpec(
            wire_name="display",
            kind="object",
            fields=_IntegrationChannel_DisplayFields,
        ),
        "name": ubx.FieldSpec(wire_name="name"),
        "account_name": ubx.FieldSpec(wire_name="account_name"),
        "channel_name": ubx.FieldSpec(wire_name="channel_name"),
    },
)
