// Code generated by `ubx sdk gen` from datadog_asset_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface List_Data_Attributes_OperatingSystem {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  version?: string | Computed<string>;
}

export interface List_Data_Attributes_Risks {
  hasAccessToSensitiveData?: boolean | Computed<boolean>;
  hasPrivilegedAccess?: boolean | Computed<boolean>;
  inProduction?: boolean | Computed<boolean>;
  isPubliclyAccessible?: boolean | Computed<boolean>;
  underAttack?: boolean | Computed<boolean>;
}

export interface List_Data_Attributes_Version {
  first?: string | Computed<string>;
  last?: string | Computed<string>;
}

export interface List_Data_Attributes {
  arch?: string | Computed<string>;
  environments?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  operatingSystem?: List_Data_Attributes_OperatingSystem | Computed<List_Data_Attributes_OperatingSystem>;
  risks?: List_Data_Attributes_Risks | Computed<List_Data_Attributes_Risks>;
  teams?: string[] | Computed<string[]>;
  type?: string | Computed<string>;
  version?: List_Data_Attributes_Version | Computed<List_Data_Attributes_Version>;
}

export interface List_Data {
  attributes?: List_Data_Attributes | Computed<List_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface List_Links {
  /** First page link. */
  first: string | Computed<string>;
  /** Last page link. */
  last: string | Computed<string>;
  /** Next page link. */
  next?: string | Computed<string>;
  /** Previous page link. */
  previous?: string | Computed<string>;
  /** Request link. */
  self: string | Computed<string>;
}

export interface List_Meta {
  /** Number of entities included in the response. */
  count: number | Computed<number>;
  /** The token that identifies the request. */
  token: string | Computed<string>;
  /** Total number of entities across all pages. */
  total: number | Computed<number>;
}

export interface ListConfig {
}

export interface ListAttrs {
  /** List of vulnerable assets. */
  data: List_Data[];
  /** The JSON:API links related to pagination. */
  links: List_Links;
  /** The metadata related to this request. */
  meta: List_Meta;
}

export const List: DataSourceBinding<ListConfig, ListAttrs> = {
  wireType: "datadog_asset_list",
  fields: {
  },
};
