// Code generated by `ubx sdk gen` from datadog_downtime. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DowntimeConfig {
  currentOnly?: boolean | Computed<boolean>;
  withCreator?: boolean | Computed<boolean>;
}

export interface DowntimeAttrs {
  currentOnly: boolean;
  withCreator: boolean;
}

export const Downtime: DataSourceBinding<DowntimeConfig, DowntimeAttrs> = {
  wireType: "datadog_downtime",
  fields: {
    currentOnly: "current_only",
    withCreator: "with_creator",
  },
};
