// Code generated by `ubx sdk gen` from datadog_awsevent_bridge_account_configuration. DO NOT EDIT.
package awsevent

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type BridgeAccountConfiguration_Accounts_EventHubs struct {
	Name any
	Region any
}

type BridgeAccountConfiguration_Accounts struct {
	AccountId any
	EventHubs any
	Tags any
}

type BridgeAccountConfigurationConfig struct {
}

type BridgeAccountConfigurationAttrs struct {
	// List of accounts with their event sources.
	Accounts any
	// True if the EventBridge sub-integration is enabled for your organization.
	IsInstalled any
}

var BridgeAccountConfiguration = ubx.DataSourceBinding{
	WireType: "datadog_awsevent_bridge_account_configuration",
	Fields: ubx.FieldMap{
	},
}
