// Code generated by `ubx sdk gen` from datadog_teams_ownership_rules_response. DO NOT EDIT.
package teams

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OwnershipRulesResponse_Data_Attributes_Teams struct {
	MappingId any
	TeamHandle any
}

type OwnershipRulesResponse_Data_Attributes struct {
	ApplicationId any
	MatchType any
	Service any
	Teams any
	ViewName any
}

type OwnershipRulesResponse_Data struct {
	Attributes any
	Id any
	Type any
}

type OwnershipRulesResponseConfig struct {
}

type OwnershipRulesResponseAttrs struct {
	// A list of teams ownership rules.
	Data any
}

var OwnershipRulesResponse = ubx.DataSourceBinding{
	WireType: "datadog_teams_ownership_rules_response",
	Fields: ubx.FieldMap{
	},
}
