// Code generated by `ubx sdk gen` from datadog_awscloud_auth_persona_mapping_data_response_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AuthPersonaMappingDataResponseList_Data_Attributes {
  accountIdentifier?: string | Computed<string>;
  accountUuid?: string | Computed<string>;
  arnPattern?: string | Computed<string>;
}

export interface AuthPersonaMappingDataResponseList_Data {
  attributes?: AuthPersonaMappingDataResponseList_Data_Attributes | Computed<AuthPersonaMappingDataResponseList_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AuthPersonaMappingDataResponseListConfig {
}

export interface AuthPersonaMappingDataResponseListAttrs {
  /** List of AWS cloud authentication persona mappings */
  data: AuthPersonaMappingDataResponseList_Data[];
}

export const AuthPersonaMappingDataResponseList: DataSourceBinding<AuthPersonaMappingDataResponseListConfig, AuthPersonaMappingDataResponseListAttrs> = {
  wireType: "datadog_awscloud_auth_persona_mapping_data_response_list",
  fields: {
  },
};
