// Code generated by `ubx sdk gen` from datadog_team_connection. DO NOT EDIT.
package team

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Connection_Data_Attributes struct {
	ManagedBy any
	Source any
}

type Connection_Data_Relationships_ConnectedTeam_Data struct {
	Id any
	Type any
}

type Connection_Data_Relationships_ConnectedTeam struct {
	Data any
}

type Connection_Data_Relationships struct {
	ConnectedTeam any
	Team any
}

type Connection_Data struct {
	Attributes any
	Id any
	Relationships any
	Type any
}

type Connection_Meta_Page struct {
	// The first page number.
	FirstNumber any
	// The last page number.
	LastNumber any
	// The next page number.
	NextNumber any
	// The current page number.
	Number any
	// The previous page number.
	PrevNumber any
	// The page size.
	Size any
	// Total connections matching request.
	Total any
	// Pagination type.
	Type any
}

type Connection_Meta struct {
	// Page-based pagination metadata.
	Page any
}

type ConnectionConfig struct {
}

type ConnectionAttrs struct {
	// Array of team connections.
	Data any
	// Connections response metadata.
	Meta any
}

var Connection = ubx.DataSourceBinding{
	WireType: "datadog_team_connection",
	Fields: ubx.FieldMap{
	},
}
