# Code generated by `ubx sdk gen` from datadog_slocorrection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Slocorrection_Data_Attributes_Creator:
    email: Any = None
    handle: Any = None
    name: Any = None

@dataclasses.dataclass
class Slocorrection_Data_Attributes:
    category: Any = None
    created_at: Any = None
    creator: Any = None
    description: Any = None
    duration: Any = None
    end: Any = None
    modified_at: Any = None
    modifier: Any = None
    rrule: Any = None
    slo_id: Any = None
    slo_query: Any = None
    start: Any = None
    timezone: Any = None

@dataclasses.dataclass
class Slocorrection_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class Slocorrection_Meta_Page:
    # Total count.
    total_count: Any = None
    # Total count of elements matched by the filter.
    total_filtered_count: Any = None

@dataclasses.dataclass
class Slocorrection_Meta:
    # Pagination object.
    page: Any = None

@dataclasses.dataclass
class SlocorrectionConfig:
    limit: Any = None
    offset: Any = None

@dataclasses.dataclass
class SlocorrectionAttrs:
    # The list of SLO corrections objects.
    data: Any = None
    limit: Any = None
    # Object describing meta attributes of response.
    meta: Any = None
    offset: Any = None

Slocorrection = ubx.DataSourceBinding(
    wire_type="datadog_slocorrection",
    fields={
        "limit": ubx.FieldSpec(wire_name="limit"),
        "offset": ubx.FieldSpec(wire_name="offset"),
    },
)
