# Code generated by `ubx sdk gen` from datadog_cloud_workload_security_agent_policy_data. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class WorkloadSecurityAgentPolicyData_Data_Attributes_Updater:
    handle: Any = None
    name: Any = None

@dataclasses.dataclass
class WorkloadSecurityAgentPolicyData_Data_Attributes_Versions:
    date: Any = None
    name: Any = None

@dataclasses.dataclass
class WorkloadSecurityAgentPolicyData_Data_Attributes:
    blocking_rules_count: Any = None
    datadog_managed: Any = None
    description: Any = None
    disabled_rules_count: Any = None
    enabled: Any = None
    host_tags: Any = None
    host_tags_lists: Any = None
    monitoring_rules_count: Any = None
    name: Any = None
    pinned: Any = None
    policy_type: Any = None
    policy_version: Any = None
    priority: Any = None
    rule_count: Any = None
    update_date: Any = None
    updated_at: Any = None
    updater: Any = None
    versions: Any = None

@dataclasses.dataclass
class WorkloadSecurityAgentPolicyData_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class WorkloadSecurityAgentPolicyDataConfig:
    pass

@dataclasses.dataclass
class WorkloadSecurityAgentPolicyDataAttrs:
    # A list of Agent policy objects
    data: Any = None

WorkloadSecurityAgentPolicyData = ubx.DataSourceBinding(
    wire_type="datadog_cloud_workload_security_agent_policy_data",
    fields={
    },
)
