// Code generated by `ubx sdk gen` from datadog_custom_rule_revisions_response. DO NOT EDIT.
package custom

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RuleRevisionsResponse_Data_Attributes_Arguments struct {
	Description any
	Name any
}

type RuleRevisionsResponse_Data_Attributes_Tests struct {
	AnnotationCount any
	Code any
	Filename any
}

type RuleRevisionsResponse_Data_Attributes struct {
	Arguments any
	Category any
	Checksum any
	Code any
	CreatedAt any
	CreatedBy any
	CreationMessage any
	Cve any
	Cwe any
	Description any
	DocumentationUrl any
	IsPublished any
	IsTesting any
	Language any
	Severity any
	ShortDescription any
	ShouldUseAiFix any
	Tags any
	Tests any
	TreeSitterQuery any
}

type RuleRevisionsResponse_Data struct {
	Attributes any
	Id any
	Type any
}

type RuleRevisionsResponseConfig struct {
	RuleName any
	RulesetName any
}

type RuleRevisionsResponseAttrs struct {
	// List of custom rule revisions.
	Data any
	RuleName any
	RulesetName any
}

var RuleRevisionsResponse = ubx.DataSourceBinding{
	WireType: "datadog_custom_rule_revisions_response",
	Fields: ubx.FieldMap{
		"RuleName": ubx.FieldSpec{WireName: "rule_name"},
		"RulesetName": ubx.FieldSpec{WireName: "ruleset_name"},
	},
}
