// Code generated by `ubx sdk gen` from datadog_outcomes_response. DO NOT EDIT.
package outcomes

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Response_Data_Attributes struct {
	CreatedAt any
	ModifiedAt any
	Remarks any
	ServiceName any
	State any
}

type Response_Data_Relationships_Rule_Data struct {
	Id any
	Type any
}

type Response_Data_Relationships_Rule struct {
	Data any
}

type Response_Data_Relationships struct {
	Rule any
}

type Response_Data struct {
	Attributes any
	Id any
	Relationships any
	Type any
}

type Response_Included_Attributes struct {
	Name any
	ScorecardName any
}

type Response_Included struct {
	Attributes any
	Id any
	Type any
}

type Response_Links struct {
	// Link for the next set of results.
	Next any
}

type ResponseConfig struct {
	Include any
}

type ResponseAttrs struct {
	// List of rule outcomes.
	Data any
	Include any
	// Array of rule details.
	Included any
	// Links attributes.
	Links any
}

var Response = ubx.DataSourceBinding{
	WireType: "datadog_outcomes_response",
	Fields: ubx.FieldMap{
		"Include": ubx.FieldSpec{WireName: "include"},
	},
}
