// Code generated by `ubx sdk gen` from datadog_access_token_list_item. DO NOT EDIT.
package access

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TokenListItem_Data_Attributes struct {
	CreatedAt     any
	ExpiresAt     any
	LastUsedAt    any
	ModifiedAt    any
	Name          any
	PublicPortion any
	Scopes        any
}

type TokenListItem_Data_Relationships_OwnedBy_Data struct {
	Id   any
	Type any
}

type TokenListItem_Data_Relationships_OwnedBy struct {
	Data any
}

type TokenListItem_Data_Relationships struct {
	OwnedBy any
}

type TokenListItem_Data struct {
	Attributes    any
	Id            any
	Relationships any
	Type          any
}

type TokenListItem_Meta_Page struct {
	// Total filtered access token count.
	TotalFilteredCount any
}

type TokenListItem_Meta struct {
	// Pagination information.
	Page any
}

type TokenListItemConfig struct {
	Filter any
	// Sorting options
	Sort any
}

type TokenListItemAttrs struct {
	// Array of access tokens. Includes both personal and service access tokens.
	Data   any
	Filter any
	// Additional information related to the access token response.
	Meta any
	// Sorting options
	Sort any
}

var TokenListItem = ubx.DataSourceBinding{
	WireType: "datadog_access_token_list_item",
	Fields: ubx.FieldMap{
		"Filter": ubx.FieldSpec{WireName: "filter"},
		"Sort":   ubx.FieldSpec{WireName: "sort"},
	},
}
