# Code generated by `ubx sdk gen` from datadog_microsoft_teams_tenant_based_handles_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TeamsTenantBasedHandlesResponse_Data_Attributes:
    channel_id: Any = None
    channel_name: Any = None
    name: Any = None
    team_id: Any = None
    team_name: Any = None
    tenant_id: Any = None
    tenant_name: Any = None

@dataclasses.dataclass
class TeamsTenantBasedHandlesResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class TeamsTenantBasedHandlesResponseConfig:
    name: Any = None
    tenant_id: Any = None

@dataclasses.dataclass
class TeamsTenantBasedHandlesResponseAttrs:
    # An array of tenant-based handles.
    data: Any = None
    name: Any = None
    tenant_id: Any = None

TeamsTenantBasedHandlesResponse = ubx.DataSourceBinding(
    wire_type="datadog_microsoft_teams_tenant_based_handles_response",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
        "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
    },
)
