// Code generated by `ubx sdk gen` from datadog_security_monitoring_rule_convert_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface MonitoringRuleConvertResponseConfig {
  ruleId: string | Computed<string>;
}

export interface MonitoringRuleConvertResponseAttrs {
  ruleId: string;
  /** Terraform string as a result of converting the rule from JSON. */
  terraformContent: string;
}

export const MonitoringRuleConvertResponse: DataSourceBinding<MonitoringRuleConvertResponseConfig, MonitoringRuleConvertResponseAttrs> = {
  wireType: "datadog_security_monitoring_rule_convert_response",
  fields: {
    ruleId: "rule_id",
  },
};
