# Code generated by `ubx sdk gen` from datadog_webhooks_auth_methods_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AuthMethodsResponse_Data_Attributes:
    protocol: Any = None

@dataclasses.dataclass
class AuthMethodsResponse_Data_Relationships_Oauth2ClientCredentials_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class AuthMethodsResponse_Data_Relationships_Oauth2ClientCredentials:
    data: Any = None

@dataclasses.dataclass
class AuthMethodsResponse_Data_Relationships:
    oauth2_client_credentials: Any = None

@dataclasses.dataclass
class AuthMethodsResponse_Data:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class AuthMethodsResponse_Included_Attributes:
    access_token_url: Any = None
    audience: Any = None
    client_id: Any = None
    name: Any = None
    protocol: Any = None
    scope: Any = None

@dataclasses.dataclass
class AuthMethodsResponse_Included:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class AuthMethodsResponseConfig:
    # Authentication protocol used by the auth method.
    include: Any = None

@dataclasses.dataclass
class AuthMethodsResponseAttrs:
    # An array of webhooks auth methods.
    data: Any = None
    # Authentication protocol used by the auth method.
    include: Any = None
    # Resources related to the auth methods, included when requested via the `include` query parameter.
    included: Any = None

AuthMethodsResponse = ubx.DataSourceBinding(
    wire_type="datadog_webhooks_auth_methods_response",
    fields={
        "include": ubx.FieldSpec(wire_name="include"),
    },
)
