// Code generated by `ubx sdk gen` from datadog_case. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Case_Data_Attributes_CustomAttributes {
  isMulti?: boolean | Computed<boolean>;
  type?: string | Computed<string>;
  value?: unknown | Computed<unknown>;
}

export interface Case_Data_Attributes_JiraIssue_Result {
  issueId?: string | Computed<string>;
  issueKey?: string | Computed<string>;
  issueUrl?: string | Computed<string>;
  projectKey?: string | Computed<string>;
}

export interface Case_Data_Attributes_JiraIssue {
  result?: Case_Data_Attributes_JiraIssue_Result | Computed<Case_Data_Attributes_JiraIssue_Result>;
  status?: string | Computed<string>;
}

export interface Case_Data_Attributes_ServiceNowTicket_Result {
  sysTargetLink?: string | Computed<string>;
}

export interface Case_Data_Attributes_ServiceNowTicket {
  result?: Case_Data_Attributes_ServiceNowTicket_Result | Computed<Case_Data_Attributes_ServiceNowTicket_Result>;
  status?: string | Computed<string>;
}

export interface Case_Data_Attributes {
  archivedAt?: string | Computed<string>;
  attributes?: Record<string, string[]> | Computed<Record<string, string[]>>;
  closedAt?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  customAttributes?: Record<string, Case_Data_Attributes_CustomAttributes> | Computed<Record<string, Case_Data_Attributes_CustomAttributes>>;
  description?: string | Computed<string>;
  jiraIssue?: Case_Data_Attributes_JiraIssue | Computed<Case_Data_Attributes_JiraIssue>;
  key?: string | Computed<string>;
  modifiedAt?: string | Computed<string>;
  priority?: string | Computed<string>;
  serviceNowTicket?: Case_Data_Attributes_ServiceNowTicket | Computed<Case_Data_Attributes_ServiceNowTicket>;
  status?: string | Computed<string>;
  statusGroup?: string | Computed<string>;
  statusName?: string | Computed<string>;
  title?: string | Computed<string>;
  type?: string | Computed<string>;
  typeId?: string | Computed<string>;
}

export interface Case_Data_Relationships_Assignee_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Case_Data_Relationships_Assignee {
  data?: Case_Data_Relationships_Assignee_Data | Computed<Case_Data_Relationships_Assignee_Data>;
}

export interface Case_Data_Relationships {
  assignee?: Case_Data_Relationships_Assignee | Computed<Case_Data_Relationships_Assignee>;
  createdBy?: Case_Data_Relationships_Assignee | Computed<Case_Data_Relationships_Assignee>;
  modifiedBy?: Case_Data_Relationships_Assignee | Computed<Case_Data_Relationships_Assignee>;
  project?: Case_Data_Relationships_Assignee | Computed<Case_Data_Relationships_Assignee>;
}

export interface Case_Data {
  attributes?: Case_Data_Attributes | Computed<Case_Data_Attributes>;
  id?: string | Computed<string>;
  relationships?: Case_Data_Relationships | Computed<Case_Data_Relationships>;
  type?: string | Computed<string>;
}

export interface Case_Meta_Page {
  /** Current page number */
  current?: number | Computed<number>;
  /** Number of cases in current page */
  size?: number | Computed<number>;
  /** Total number of pages */
  total?: number | Computed<number>;
}

export interface Case_Meta {
  /** Pagination metadata */
  page?: Case_Meta_Page | Computed<Case_Meta_Page>;
}

export interface CaseConfig {
  filter?: string | Computed<string>;
}

export interface CaseAttrs {
  /** Cases response data */
  data: Case_Data[];
  filter: string;
  /** Cases response metadata */
  meta: Case_Meta;
}

export const Case: DataSourceBinding<CaseConfig, CaseAttrs> = {
  wireType: "datadog_case",
  fields: {
    filter: "filter",
  },
};
