// Code generated by `ubx sdk gen` from datadog_role_template_data_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TemplateDataList_Data_Attributes {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface TemplateDataList_Data {
  attributes?: TemplateDataList_Data_Attributes | Computed<TemplateDataList_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface TemplateDataListConfig {
}

export interface TemplateDataListAttrs {
  /** The `RoleTemplateArray` `data`. */
  data: TemplateDataList_Data[];
}

export const TemplateDataList: DataSourceBinding<TemplateDataListConfig, TemplateDataListAttrs> = {
  wireType: "datadog_role_template_data_list",
  fields: {
  },
};
