# Code generated by `ubx sdk gen` from datadog_fastly_service_data_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ServiceDataList_Data_Attributes:
    tags: Any = None

@dataclasses.dataclass
class ServiceDataList_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class ServiceDataListConfig:
    account_id: Any = None

@dataclasses.dataclass
class ServiceDataListAttrs:
    account_id: Any = None
    # The JSON:API data schema.
    data: Any = None

ServiceDataList = ubx.DataSourceBinding(
    wire_type="datadog_fastly_service_data_list",
    fields={
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
