// Code generated by `ubx sdk gen` from datadog_finding_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface List_Data_Attributes_Mute {
  description?: string | Computed<string>;
  expirationDate?: number | Computed<number>;
  muted?: boolean | Computed<boolean>;
  reason?: string | Computed<string>;
  startDate?: number | Computed<number>;
  uuid?: string | Computed<string>;
}

export interface List_Data_Attributes_Rule {
  id?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface List_Data_Attributes {
  datadogLink?: string | Computed<string>;
  description?: string | Computed<string>;
  evaluation?: string | Computed<string>;
  evaluationChangedAt?: number | Computed<number>;
  externalId?: string | Computed<string>;
  mute?: List_Data_Attributes_Mute | Computed<List_Data_Attributes_Mute>;
  resource?: string | Computed<string>;
  resourceDiscoveryDate?: number | Computed<number>;
  resourceType?: string | Computed<string>;
  rule?: List_Data_Attributes_Rule | Computed<List_Data_Attributes_Rule>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  vulnerabilityType?: string | Computed<string>;
}

export interface List_Data {
  attributes?: List_Data_Attributes | Computed<List_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface List_Meta_Page {
  /** The cursor used to paginate requests. */
  cursor?: string | Computed<string>;
  /** The total count of findings after the filter has been applied. */
  totalFilteredCount?: number | Computed<number>;
}

export interface List_Meta {
  /** Pagination and findings count information. */
  page?: List_Meta_Page | Computed<List_Meta_Page>;
  /** The point in time corresponding to the listed findings. */
  snapshotTimestamp?: number | Computed<number>;
}

export interface ListConfig {
  detailedFindings?: boolean | Computed<boolean>;
  snapshotTimestamp?: number | Computed<number>;
}

export interface ListAttrs {
  /** Array of findings. */
  data: List_Data[];
  detailedFindings: boolean;
  /** Metadata for pagination. */
  meta: List_Meta;
  snapshotTimestamp: number;
}

export const List: DataSourceBinding<ListConfig, ListAttrs> = {
  wireType: "datadog_finding_list",
  fields: {
    detailedFindings: "detailed_findings",
    snapshotTimestamp: "snapshot_timestamp",
  },
};
