# Code generated by `ubx sdk gen` from datadog_ownership_inference_list_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class InferenceListResponse_Data_Attributes_Items:
    checksum: Any = None
    confidence: Any = None
    created_at: Any = None
    evidence_versions: Any = None
    explanation: Any = None
    id: Any = None
    owner_type: Any = None
    primary_contact_ref: Any = None
    sources: Any = None
    status: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class InferenceListResponse_Data_Attributes:
    # The list of inferences for a resource, with one inference per owner type.
    items: Any = None

@dataclasses.dataclass
class InferenceListResponse_Data:
    # The attributes of the ownership inferences collection response.
    attributes: Any = None
    # The resource identifier associated with the returned inferences.
    id: Any = None
    # The type of the ownership inferences collection resource. The value should always be `ownership_inferences`.
    type: Any = None

@dataclasses.dataclass
class InferenceListResponseConfig:
    resource_id: Any = None

@dataclasses.dataclass
class InferenceListResponseAttrs:
    # The data wrapper for the ownership inferences collection response.
    data: Any = None
    resource_id: Any = None

InferenceListResponse = ubx.DataSourceBinding(
    wire_type="datadog_ownership_inference_list_response",
    fields={
        "resource_id": ubx.FieldSpec(wire_name="resource_id"),
    },
)
