# Code generated by `ubx sdk gen` from datadog_deployment_rule_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class RuleResponse_Data_Attributes_CreatedBy:
    # The handle of the user who created the deployment rule.
    handle: Any = None
    # The ID of the user who created the deployment rule.
    id: Any = None
    # The name of the user who created the deployment rule.
    name: Any = None

@dataclasses.dataclass
class RuleResponse_Data_Attributes_Options:
    allowed_resources: Any = None
    duration: Any = None
    excluded_resources: Any = None
    query: Any = None

@dataclasses.dataclass
class RuleResponse_Data_Attributes:
    # The timestamp when the deployment rule was created.
    created_at: Any = None
    # Information about the user who created the deployment rule.
    created_by: Any = None
    # Whether this rule is run in dry-run mode.
    dry_run: Any = None
    # The ID of the deployment gate.
    gate_id: Any = None
    # The name of the deployment rule.
    name: Any = None
    # Options for deployment rule response representing either faulty deployment detection or monitor options.
    options: Any = None
    # The type of the deployment rule (faulty_deployment_detection or monitor).
    type: Any = None
    # The timestamp when the deployment rule was last updated.
    updated_at: Any = None
    # Information about the user who updated the deployment rule.
    updated_by: Any = None

@dataclasses.dataclass
class RuleResponse_Data:
    # Parameters for creating a deployment rule.
    attributes: Any = None
    # Unique identifier of the deployment rule.
    id: Any = None
    # Deployment rule resource type.
    type: Any = None

_RuleResponse_Data_Attributes_CreatedByFields = {
    "handle": ubx.FieldSpec(wire_name="handle"),
    "id": ubx.FieldSpec(wire_name="id"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_RuleResponse_Data_Attributes_OptionsFields = {
    "allowed_resources": ubx.FieldSpec(wire_name="allowed_resources"),
    "duration": ubx.FieldSpec(wire_name="duration"),
    "excluded_resources": ubx.FieldSpec(wire_name="excluded_resources"),
    "query": ubx.FieldSpec(wire_name="query"),
}

_RuleResponse_Data_AttributesFields = {
    "created_at": ubx.FieldSpec(wire_name="created_at"),
    "created_by": ubx.FieldSpec(
        wire_name="created_by",
        kind="object",
        fields=_RuleResponse_Data_Attributes_CreatedByFields,
    ),
    "dry_run": ubx.FieldSpec(wire_name="dry_run"),
    "gate_id": ubx.FieldSpec(wire_name="gate_id"),
    "name": ubx.FieldSpec(wire_name="name"),
    "options": ubx.FieldSpec(
        wire_name="options",
        kind="object",
        fields=_RuleResponse_Data_Attributes_OptionsFields,
    ),
    "type": ubx.FieldSpec(wire_name="type"),
    "updated_at": ubx.FieldSpec(wire_name="updated_at"),
    "updated_by": ubx.FieldSpec(
        wire_name="updated_by",
        kind="object",
        fields=_RuleResponse_Data_Attributes_CreatedByFields,
    ),
}

_RuleResponse_DataFields = {
    "attributes": ubx.FieldSpec(
        wire_name="attributes",
        kind="object",
        fields=_RuleResponse_Data_AttributesFields,
    ),
    "id": ubx.FieldSpec(wire_name="id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class RuleResponseConfig:
    # Parameters for creating a deployment rule.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    gate_id: Any = None
    # path parameter, not part of the API's own resource representation
    id: Any = None

@dataclasses.dataclass
class RuleResponseAttrs:
    # Parameters for creating a deployment rule.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    gate_id: Any = None
    # path parameter, not part of the API's own resource representation
    id: Any = None

RuleResponse = ubx.ResourceBinding(
    wire_type="datadog_deployment_rule_response",
    fields={
        "data": ubx.FieldSpec(
            wire_name="data",
            kind="object",
            fields=_RuleResponse_DataFields,
        ),
        "gate_id": ubx.FieldSpec(wire_name="gate_id"),
        "id": ubx.FieldSpec(wire_name="id"),
    },
)
