// Code generated by `ubx sdk gen` from datadog_attachment_array. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Array_Data_Attributes_Attachment {
  documentUrl?: string | Computed<string>;
  title?: string | Computed<string>;
}

export interface Array_Data_Attributes {
  attachment?: Array_Data_Attributes_Attachment | Computed<Array_Data_Attributes_Attachment>;
  attachmentType?: string | Computed<string>;
  modified?: string | Computed<string>;
}

export interface Array_Data_Relationships_Incident_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Array_Data_Relationships_Incident {
  data?: Array_Data_Relationships_Incident_Data | Computed<Array_Data_Relationships_Incident_Data>;
}

export interface Array_Data_Relationships {
  incident?: Array_Data_Relationships_Incident | Computed<Array_Data_Relationships_Incident>;
  lastModifiedByUser?: Array_Data_Relationships_Incident | Computed<Array_Data_Relationships_Incident>;
}

export interface Array_Data {
  attributes?: Array_Data_Attributes | Computed<Array_Data_Attributes>;
  id?: string | Computed<string>;
  relationships?: Array_Data_Relationships | Computed<Array_Data_Relationships>;
  type?: string | Computed<string>;
}

export interface Array_Included_Attributes {
  email?: string | Computed<string>;
  handle?: string | Computed<string>;
  icon?: string | Computed<string>;
  name?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface Array_Included {
  attributes?: Array_Included_Attributes | Computed<Array_Included_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ArrayConfig {
  incidentId: string | Computed<string>;
  include?: string | Computed<string>;
}

export interface ArrayAttrs {
  /** An array of attachment data objects. */
  data: Array_Data[];
  incidentId: string;
  include: string;
  /** A list of related objects included in the response. */
  included: Array_Included[];
}

export const Array: DataSourceBinding<ArrayConfig, ArrayAttrs> = {
  wireType: "datadog_attachment_array",
  fields: {
    incidentId: "incident_id",
    include: "include",
  },
};
