# Code generated by `ubx sdk gen` from datadog_projected_cost_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CostResponse_Data_Attributes_Charges:
    charge_type: Any = None
    cost: Any = None
    product_name: Any = None

@dataclasses.dataclass
class CostResponse_Data_Attributes:
    account_name: Any = None
    account_public_id: Any = None
    charges: Any = None
    date: Any = None
    org_name: Any = None
    projected_total_cost: Any = None
    public_id: Any = None
    region: Any = None

@dataclasses.dataclass
class CostResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class CostResponseConfig:
    include_connected_accounts: Any = None
    view: Any = None

@dataclasses.dataclass
class CostResponseAttrs:
    # Response containing Projected Cost.
    data: Any = None
    include_connected_accounts: Any = None
    view: Any = None

CostResponse = ubx.DataSourceBinding(
    wire_type="datadog_projected_cost_response",
    fields={
        "include_connected_accounts": ubx.FieldSpec(wire_name="include_connected_accounts"),
        "view": ubx.FieldSpec(wire_name="view"),
    },
)
