// Code generated by `ubx sdk gen` from datadog_list_investigations_response_data. DO NOT EDIT.
package list

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type InvestigationsResponseData_Data_Attributes struct {
	Status any
	Title any
}

type InvestigationsResponseData_Data struct {
	Attributes any
	Id any
	Type any
}

type InvestigationsResponseData_Links struct {
	// Link to the first page.
	First any
	// Link to the last page.
	Last any
	// Link to the next page.
	Next any
	// Link to the previous page.
	Prev any
	// Link to the current page.
	Self any
}

type InvestigationsResponseData_Meta_Page struct {
	// Maximum number of results per page.
	Limit any
	// Offset of the current page.
	Offset any
	// Total number of investigations.
	Total any
}

type InvestigationsResponseData_Meta struct {
	// Pagination metadata.
	Page any
}

type InvestigationsResponseDataConfig struct {
}

type InvestigationsResponseDataAttrs struct {
	// List of investigations.
	Data any
	// Pagination links for the list investigations response.
	Links any
	// Metadata for the list investigations response.
	Meta any
}

var InvestigationsResponseData = ubx.DataSourceBinding{
	WireType: "datadog_list_investigations_response_data",
	Fields: ubx.FieldMap{
	},
}
