// Code generated by `ubx sdk gen` from datadog_list_pipelines_response. DO NOT EDIT.
package list

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PipelinesResponse_Data_Attributes_Config_Destinations_Auth struct {
	PasswordKey any
	Strategy any
	UsernameKey any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_Batch struct {
	MaxEvents any
	TimeoutSecs any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_BatchEncoding struct {
	AllowNullableFields any
	Codec any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_BatchSettings struct {
	BatchSize any
	TimeoutSecs any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_Buffer struct {
	MaxEvents any
	MaxSize any
	Type any
	WhenFull any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_Compression struct {
	Algorithm any
	Level any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_DataStream struct {
	AutoRouting any
	Dataset any
	Dtype any
	Namespace any
	SyncFields any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_Framing struct {
	Delimiter any
	Method any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_HeaderCustomFields struct {
	Name any
	Value any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_Routes struct {
	ApiKeyKey any
	Include any
	RouteId any
	Site any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_Sasl struct {
	Mechanism any
	PasswordKey any
	UsernameKey any
}

type PipelinesResponse_Data_Attributes_Config_Destinations_Tls struct {
	CaFile any
	CrtFile any
	KeyFile any
	KeyPassKey any
}

type PipelinesResponse_Data_Attributes_Config_Destinations struct {
	AccountIdKey any
	Acl any
	AddressKey any
	ApiVersion any
	Auth any
	AuthStrategy any
	AutoExtractTimestamp any
	Batch any
	BatchEncoding any
	BatchSettings any
	BlobPrefix any
	BootstrapServersKey any
	Bucket any
	Buffer any
	BulkIndex any
	ClientId any
	ClientSecretKey any
	Compression any
	ConnectionStringKey any
	ContainerName any
	CustomKey any
	CustomSourceName any
	CustomerId any
	DataStream any
	Database any
	DateTimeBestEffort any
	DceUriKey any
	DcrImmutableId any
	DefaultNamespace any
	Encoding any
	EndpointTarget any
	EndpointUrlKey any
	Format any
	Framing any
	HeaderCustomFields any
	HeaderHostName any
	HeaderSourceCategory any
	HeaderSourceName any
	HeadersKey any
	Id any
	IdKey any
	Index any
	IndexedFields any
	IngestionEndpointKey any
	Inputs any
	Keepalive any
	KeyField any
	KeyPrefix any
	LibrdkafkaOptions any
	LicenseKeyKey any
	LogType any
	MessageTimeoutMs any
	Metadata any
	Mode any
	PasswordKey any
	Pipeline any
	Project any
	RateLimitDurationSecs any
	RateLimitNum any
	Region any
	RequestRetryPartial any
	Routes any
	Sasl any
	ServerSideEncryption any
	SkipUnknownFields any
	SocketTimeoutMs any
	Source any
	Sourcetype any
	SsekmsKeyId any
	StorageClass any
	Table any
	TableName any
	TenantId any
	Tls any
	TokenKey any
	TokenStrategy any
	Topic any
	Type any
	UnityCatalogEndpointKey any
	UriKey any
	UsernameKey any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Arrays struct {
	Field any
	Include any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Cache struct {
	NumEvents any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_File_Encoding struct {
	Delimiter any
	IncludesHeaders any
	Type any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_File_Key struct {
	Column any
	Comparison any
	Field any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_File_Schema struct {
	Column any
	Type any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_File struct {
	Encoding any
	Key any
	Path any
	Schema any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Geoip struct {
	KeyField any
	Locale any
	Path any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Limit struct {
	Enforce any
	Limit any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Mappings struct {
	Include any
	Mapping any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_MergeStrategies struct {
	Path any
	Strategy any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Metrics_Value struct {
	Field any
	Strategy any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Metrics struct {
	GroupBy any
	Include any
	MetricType any
	Name any
	Value any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Overrides struct {
	Fields any
	Limit any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_PerMetricLimits_PerTagLimits struct {
	OverrideType any
	TagKey any
	ValueLimit any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_PerMetricLimits struct {
	LimitExceededAction any
	MetricName any
	OverrideType any
	PerTagLimits any
	ValueLimit any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_ReferenceTable struct {
	AppKeyKey any
	Columns any
	KeyField any
	TableId any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Remaps struct {
	DropOnError any
	Enabled any
	Include any
	Name any
	Source any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Rules_MatchRules struct {
	Name any
	Rule any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Rules struct {
	Include any
	MatchRules any
	Source any
	SupportRules any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_TrackingMode struct {
	Mode any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors_Variables struct {
	Field any
	Name any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups_Processors struct {
	Action any
	AlwaysUseTextKey any
	Arrays any
	AttrPrefix any
	Cache any
	DisableLibraryRules any
	DisplayName any
	DropEvents any
	Enabled any
	Field any
	Fields any
	File any
	Geoip any
	GroupBy any
	Id any
	IgnoreWhenMissingPartitions any
	Include any
	IncludeAttr any
	IntervalSecs any
	KeepUnmatched any
	Keys any
	Limit any
	LimitExceededAction any
	Mappings any
	MergeStrategies any
	Metrics any
	Mode any
	Name any
	OverflowAction any
	Overrides any
	ParseBool any
	ParseNull any
	ParseNumber any
	PartitionFields any
	PerMetricLimits any
	Percentage any
	ReferenceTable any
	Remaps any
	Rules any
	Tags any
	Target any
	TextKey any
	Threshold any
	TooManyBucketsAction any
	TrackingMode any
	Type any
	ValueLimit any
	Variables any
	Window any
}

type PipelinesResponse_Data_Attributes_Config_ProcessorGroups struct {
	DisplayName any
	Enabled any
	Id any
	Include any
	Inputs any
	Processors any
}

type PipelinesResponse_Data_Attributes_Config_Sources_Auth struct {
	AssumeRole any
	ExternalId any
	SessionName any
}

type PipelinesResponse_Data_Attributes_Config_Sources_ValidTokens_FieldToAdd struct {
	Key any
	Value any
}

type PipelinesResponse_Data_Attributes_Config_Sources_ValidTokens struct {
	Enabled any
	FieldToAdd any
	PathToToken any
	TokenKey any
}

type PipelinesResponse_Data_Attributes_Config_Sources struct {
	AddressKey any
	Auth any
	AuthStrategy any
	BootstrapServersKey any
	Compression any
	CustomKey any
	Decoding any
	EndpointUrlKey any
	Framing any
	GroupId any
	GrpcAddressKey any
	HttpAddressKey any
	Id any
	LibrdkafkaOptions any
	Mode any
	PasswordKey any
	Project any
	Region any
	Sasl any
	ScrapeIntervalSecs any
	ScrapeTimeoutSecs any
	StoreHecToken any
	Subscription any
	Tls any
	TokenKey any
	Topics any
	Type any
	UriKey any
	UrlKey any
	UsernameKey any
	ValidTokens any
}

type PipelinesResponse_Data_Attributes_Config struct {
	Destinations any
	PipelineType any
	ProcessorGroups any
	Processors any
	Sources any
	UseLegacySearchSyntax any
}

type PipelinesResponse_Data_Attributes struct {
	Config any
	Name any
}

type PipelinesResponse_Data struct {
	Attributes any
	Id any
	Type any
}

type PipelinesResponse_Meta struct {
	// The total number of pipelines.
	TotalCount any
}

type PipelinesResponseConfig struct {
}

type PipelinesResponseAttrs struct {
	// The `schema` `data`.
	Data any
	// Metadata about the response.
	Meta any
}

var PipelinesResponse = ubx.DataSourceBinding{
	WireType: "datadog_list_pipelines_response",
	Fields: ubx.FieldMap{
	},
}
