// Code generated by `ubx sdk gen` from datadog_list_sourcemaps_response. DO NOT EDIT.
package list

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SourcemapsResponse_Data_Attributes struct {
	AbsolutePath any
	BlobStorageSourcemapPath any
	BuildId any
	CreatedAt any
	Domain any
	FileName any
	Mapkind any
	Service any
	Size any
	Variant any
	Version any
	VersionCode any
}

type SourcemapsResponse_Data struct {
	Attributes any
	Id any
	Type any
}

type SourcemapsResponse_Meta_Page struct {
	// Whether there are more results available beyond the current page.
	HasMoreResults any
	// Total number of source maps matching the filter criteria.
	TotalFilteredCount any
}

type SourcemapsResponse_Meta struct {
	// Page information for the source maps list response.
	Page any
}

type SourcemapsResponseConfig struct {
	// The type of source map.
	Mapkind any
}

type SourcemapsResponseAttrs struct {
	// List of source map data objects.
	Data any
	// The type of source map.
	Mapkind any
	// Pagination metadata for the source maps list response.
	Meta any
}

var SourcemapsResponse = ubx.DataSourceBinding{
	WireType: "datadog_list_sourcemaps_response",
	Fields: ubx.FieldMap{
		"Mapkind": ubx.FieldSpec{WireName: "mapkind"},
	},
}
