# Code generated by `ubx sdk gen` from datadog_page_annotations_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AnnotationsResponse_Data_Attributes_Annotations:
    author_id: Any = None
    color: Any = None
    created_at: Any = None
    description: Any = None
    end_time: Any = None
    id: Any = None
    modified_at: Any = None
    page_id: Any = None
    start_time: Any = None
    type: Any = None
    widget_ids: Any = None

@dataclasses.dataclass
class AnnotationsResponse_Data_Attributes:
    # Map of annotation UUID to annotation object, keyed by annotation ID.
    annotations: Any = None
    # List of annotation IDs that apply to the entire page rather than a specific widget.
    global_annotations: Any = None
    # Map from widget ID to the list of annotation IDs displayed on that widget.
    widget_mapping: Any = None

@dataclasses.dataclass
class AnnotationsResponse_Data:
    # Attributes of the annotations on a page.
    attributes: Any = None
    # ID of the page, prefixed with the page type and joined by a colon (for example, `dashboard:abc-def-xyz` or `notebook:1234567890`).
    id: Any = None
    # Page annotations resource type.
    type: Any = None

@dataclasses.dataclass
class AnnotationsResponseConfig:
    end_time: Any = None
    page_id: Any = None
    start_time: Any = None

@dataclasses.dataclass
class AnnotationsResponseAttrs:
    # Annotations grouped by widget for a single page.
    data: Any = None
    end_time: Any = None
    page_id: Any = None
    start_time: Any = None

AnnotationsResponse = ubx.DataSourceBinding(
    wire_type="datadog_page_annotations_response",
    fields={
        "end_time": ubx.FieldSpec(wire_name="end_time"),
        "page_id": ubx.FieldSpec(wire_name="page_id"),
        "start_time": ubx.FieldSpec(wire_name="start_time"),
    },
)
