# Code generated by `ubx sdk gen` from datadog_usage_civisibility_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CivisibilityResponse_Usage:
    ci_pipeline_indexed_spans: Any = None
    ci_test_indexed_spans: Any = None
    ci_visibility_itr_committers: Any = None
    ci_visibility_pipeline_committers: Any = None
    ci_visibility_test_committers: Any = None
    org_name: Any = None
    public_id: Any = None

@dataclasses.dataclass
class CivisibilityResponseConfig:
    end_hr: Any = None
    start_hr: Any = None

@dataclasses.dataclass
class CivisibilityResponseAttrs:
    end_hr: Any = None
    start_hr: Any = None
    # Response containing CI visibility usage.
    usage: Any = None

CivisibilityResponse = ubx.DataSourceBinding(
    wire_type="datadog_usage_civisibility_response",
    fields={
        "end_hr": ubx.FieldSpec(wire_name="end_hr"),
        "start_hr": ubx.FieldSpec(wire_name="start_hr"),
    },
)
