# Code generated by `ubx sdk gen` from datadog_usage_incident_management_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class IncidentManagementResponse_Usage:
    hour: Any = None
    monthly_active_users: Any = None
    org_name: Any = None
    public_id: Any = None

@dataclasses.dataclass
class IncidentManagementResponseConfig:
    end_hr: Any = None
    start_hr: Any = None

@dataclasses.dataclass
class IncidentManagementResponseAttrs:
    end_hr: Any = None
    start_hr: Any = None
    # Get hourly usage for incident management.
    usage: Any = None

IncidentManagementResponse = ubx.DataSourceBinding(
    wire_type="datadog_usage_incident_management_response",
    fields={
        "end_hr": ubx.FieldSpec(wire_name="end_hr"),
        "start_hr": ubx.FieldSpec(wire_name="start_hr"),
    },
)
