# Code generated by `ubx sdk gen` from datadog_usage_logs_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LogsResponse_Usage:
    billable_ingested_bytes: Any = None
    hour: Any = None
    indexed_events_count: Any = None
    ingested_events_bytes: Any = None
    logs_forwarding_events_bytes: Any = None
    logs_live_indexed_count: Any = None
    logs_live_ingested_bytes: Any = None
    logs_rehydrated_indexed_count: Any = None
    logs_rehydrated_ingested_bytes: Any = None
    org_name: Any = None
    public_id: Any = None

@dataclasses.dataclass
class LogsResponseConfig:
    end_hr: Any = None
    start_hr: Any = None

@dataclasses.dataclass
class LogsResponseAttrs:
    end_hr: Any = None
    start_hr: Any = None
    # An array of objects regarding hourly usage of logs.
    usage: Any = None

LogsResponse = ubx.DataSourceBinding(
    wire_type="datadog_usage_logs_response",
    fields={
        "end_hr": ubx.FieldSpec(wire_name="end_hr"),
        "start_hr": ubx.FieldSpec(wire_name="start_hr"),
    },
)
