// Code generated by `ubx sdk gen` from datadog_forms_response. DO NOT EDIT.
package forms

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Response_Data_Attributes_DatastoreConfig struct {
	DatastoreId any
	PrimaryColumnName any
	PrimaryKeyGenerationStrategy any
}

type Response_Data_Attributes_Publication struct {
	CreatedAt any
	FormId any
	FormVersion any
	Id any
	ModifiedAt any
	OrgId any
	PublishSeq any
	UserId any
	UserUuid any
}

type Response_Data_Attributes_Version_DataDefinition struct {
	Description any
	Properties any
	Required any
	Title any
	Type any
}

type Response_Data_Attributes_Version_UiDefinition struct {
}

type Response_Data_Attributes_Version struct {
	CreatedAt any
	DataDefinition any
	DefinitionSignature any
	Etag any
	Id any
	ModifiedAt any
	State any
	UiDefinition any
	UserId any
	UserUuid any
	Version any
}

type Response_Data_Attributes struct {
	Active any
	Anonymous any
	CreatedAt any
	DatastoreConfig any
	Description any
	EndDate any
	HasSubmitted any
	IdpSurvey any
	ModifiedAt any
	Name any
	OrgId any
	Publication any
	SelfService any
	SingleResponse any
	UserId any
	UserUuid any
	Version any
}

type Response_Data struct {
	Attributes any
	Id any
	Type any
}

type ResponseConfig struct {
}

type ResponseAttrs struct {
	// A list of form resource objects.
	Data any
}

var Response = ubx.DataSourceBinding{
	WireType: "datadog_forms_response",
	Fields: ubx.FieldMap{
	},
}
