// Code generated by `ubx sdk gen` from datadog_table_row_resource_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RowResourceData_Data_Attributes {
  values?: unknown | Computed<unknown>;
}

export interface RowResourceData_Data {
  attributes?: RowResourceData_Data_Attributes | Computed<RowResourceData_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RowResourceDataConfig {
  id: string | Computed<string>;
  rowId: string[] | Computed<string[]>;
}

export interface RowResourceDataAttrs {
  /** The rows. */
  data: RowResourceData_Data[];
  id: string;
  rowId: string[];
}

export const RowResourceData: DataSourceBinding<RowResourceDataConfig, RowResourceDataAttrs> = {
  wireType: "datadog_table_row_resource_data",
  fields: {
    id: "id",
    rowId: "row_id",
  },
};
