// Code generated by `ubx sdk gen` from datadog_llmobs_projects_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ProjectsResponse_Data_Attributes {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface ProjectsResponse_Data {
  attributes?: ProjectsResponse_Data_Attributes | Computed<ProjectsResponse_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ProjectsResponse_Meta {
  /** Cursor for the next page of results. */
  after?: string | Computed<string>;
}

export interface ProjectsResponseConfig {
}

export interface ProjectsResponseAttrs {
  /** List of projects. */
  data: ProjectsResponse_Data[];
  /** Pagination cursor metadata. */
  meta: ProjectsResponse_Meta;
}

export const ProjectsResponse: DataSourceBinding<ProjectsResponseConfig, ProjectsResponseAttrs> = {
  wireType: "datadog_llmobs_projects_response",
  fields: {
  },
};
