// Code generated by `ubx sdk gen` from datadog_llmobs_prompt_version_list_data. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface PromptVersionListData_Data_Attributes_Datasets {
  id?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface PromptVersionListData_Data_Attributes {
  author?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  datasets?: PromptVersionListData_Data_Attributes_Datasets[] | Computed<PromptVersionListData_Data_Attributes_Datasets[]>;
  description?: string | Computed<string>;
  labels?: string[] | Computed<string[]>;
  lastSeenAt?: string | Computed<string>;
  mlApp?: string | Computed<string>;
  mlApps?: string[] | Computed<string[]>;
  promptId?: string | Computed<string>;
  promptUuid?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  userVersion?: string | Computed<string>;
  version?: number | Computed<number>;
  versionCreatedAt?: string | Computed<string>;
}

export interface PromptVersionListData_Data {
  attributes?: PromptVersionListData_Data_Attributes | Computed<PromptVersionListData_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface PromptVersionListDataConfig {
  promptId: string | Computed<string>;
}

export interface PromptVersionListDataAttrs {
  /** Prompt versions ordered from newest to oldest. */
  data: PromptVersionListData_Data[];
  promptId: string;
}

export const PromptVersionListData: DataSourceBinding<PromptVersionListDataConfig, PromptVersionListDataAttrs> = {
  wireType: "datadog_llmobs_prompt_version_list_data",
  fields: {
    promptId: "prompt_id",
  },
};
