// Code generated by `ubx sdk gen` from datadog_usage_audit_logs_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AuditLogsResponse_Usage {
  hour?: string | Computed<string>;
  linesIndexed?: number | Computed<number>;
  orgName?: string | Computed<string>;
  publicId?: string | Computed<string>;
}

export interface AuditLogsResponseConfig {
  endHr?: string | Computed<string>;
  startHr: string | Computed<string>;
}

export interface AuditLogsResponseAttrs {
  endHr: string;
  startHr: string;
  /** Get hourly usage for audit logs. */
  usage: AuditLogsResponse_Usage[];
}

export const AuditLogsResponse: DataSourceBinding<AuditLogsResponseConfig, AuditLogsResponseAttrs> = {
  wireType: "datadog_usage_audit_logs_response",
  fields: {
    endHr: "end_hr",
    startHr: "start_hr",
  },
};
