// Code generated by `ubx sdk gen` from datadog_azure_scan_options_data_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ScanOptionsDataList_Data_Attributes {
  complianceHost?: boolean | Computed<boolean>;
  function?: boolean | Computed<boolean>;
  vulnContainersOs?: boolean | Computed<boolean>;
  vulnHostOs?: boolean | Computed<boolean>;
}

export interface ScanOptionsDataList_Data {
  attributes?: ScanOptionsDataList_Data_Attributes | Computed<ScanOptionsDataList_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ScanOptionsDataListConfig {
}

export interface ScanOptionsDataListAttrs {
  /** A list of Azure scan options. */
  data: ScanOptionsDataList_Data[];
}

export const ScanOptionsDataList: DataSourceBinding<ScanOptionsDataListConfig, ScanOptionsDataListAttrs> = {
  wireType: "datadog_azure_scan_options_data_list",
  fields: {
  },
};
