// Code generated by `ubx sdk gen` from datadog_incident_type_response. DO NOT EDIT.
package incident

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TypeResponse_Data_Attributes_Configuration struct {
	// Whether incidents of this type can be deleted.
	AllowIncidentDeletion any
	// Whether automation workflows can be triggered for incidents of this type.
	AllowWorkflows any
	// An optional message shown to users when they declare an incident of this type.
	CreateMessage any
	// Whether responders can edit incident timestamps for incidents of this type.
	EditableTimestamps any
	// Whether responders can create private incidents of this type. This is an opt-in setting, distinct from `private_incidents_by_default`, which controls whether incidents are created private automatically.
	PrivateIncidents any
	// Whether incidents of this type are created as private by default.
	PrivateIncidentsByDefault any
	// When set to `servicenow`, incidents will display the ServiceNow record ID instead of the public ID. If no ServiceNow integration exists, the public ID will be displayed.
	SlugSource any
	// Whether incidents of this type are treated as test incidents.
	TestIncidents any
}

type TypeResponse_Data_Attributes struct {
	// The incident-type-scoped behavior settings. All fields are optional on update. Any field omitted from a PATCH request keeps its current value. This object is read-only on the incident type resource itself and is only mutated through the update (PATCH) endpoint.
	Configuration any
	// Timestamp when the incident type was created.
	CreatedAt any
	// A unique identifier that represents the user that created the incident type.
	CreatedBy any
	// Text that describes the incident type.
	Description any
	// If true, this incident type will be used as the default incident type if a type is not specified during the creation of incident resources.
	IsDefault any
	// A unique identifier that represents the user that last modified the incident type.
	LastModifiedBy any
	// Timestamp when the incident type was last modified.
	ModifiedAt any
	// The name of the incident type.
	Name any
	// The string that will be prepended to the incident title across the Datadog app.
	Prefix any
}

type TypeResponse_Data_Relationships_CreatedByUser_Data struct {
	// A unique identifier that represents the user.
	Id any
	// Users resource type.
	Type any
}

type TypeResponse_Data_Relationships_CreatedByUser struct {
	// Relationship to user object.
	Data any
}

type TypeResponse_Data_Relationships struct {
	// Relationship to user.
	CreatedByUser any
	// A reference to a Google Meet Configuration resource.
	GoogleMeetConfiguration any
	// Relationship to user.
	LastModifiedByUser any
	// A reference to a Microsoft Teams Configuration resource.
	MicrosoftTeamsConfiguration any
	// A reference to a Zoom configuration resource.
	ZoomConfiguration any
}

type TypeResponse_Data struct {
	// Incident type's attributes.
	Attributes any
	// The incident type's ID.
	Id any
	// The incident type's resource relationships.
	Relationships any
	// Incident type resource type.
	Type any
}

var TypeResponse_Data_Attributes_ConfigurationFields = ubx.FieldMap{
	"AllowIncidentDeletion":     ubx.FieldSpec{WireName: "allow_incident_deletion"},
	"AllowWorkflows":            ubx.FieldSpec{WireName: "allow_workflows"},
	"CreateMessage":             ubx.FieldSpec{WireName: "create_message"},
	"EditableTimestamps":        ubx.FieldSpec{WireName: "editable_timestamps"},
	"PrivateIncidents":          ubx.FieldSpec{WireName: "private_incidents"},
	"PrivateIncidentsByDefault": ubx.FieldSpec{WireName: "private_incidents_by_default"},
	"SlugSource":                ubx.FieldSpec{WireName: "slug_source"},
	"TestIncidents":             ubx.FieldSpec{WireName: "test_incidents"},
}

var TypeResponse_Data_AttributesFields = ubx.FieldMap{
	"Configuration": ubx.FieldSpec{
		WireName: "configuration",
		Kind:     "object",
		Fields:   TypeResponse_Data_Attributes_ConfigurationFields,
	},
	"CreatedAt":      ubx.FieldSpec{WireName: "created_at"},
	"CreatedBy":      ubx.FieldSpec{WireName: "created_by"},
	"Description":    ubx.FieldSpec{WireName: "description"},
	"IsDefault":      ubx.FieldSpec{WireName: "is_default"},
	"LastModifiedBy": ubx.FieldSpec{WireName: "last_modified_by"},
	"ModifiedAt":     ubx.FieldSpec{WireName: "modified_at"},
	"Name":           ubx.FieldSpec{WireName: "name"},
	"Prefix":         ubx.FieldSpec{WireName: "prefix"},
}

var TypeResponse_Data_Relationships_CreatedByUser_DataFields = ubx.FieldMap{
	"Id":   ubx.FieldSpec{WireName: "id"},
	"Type": ubx.FieldSpec{WireName: "type"},
}

var TypeResponse_Data_Relationships_CreatedByUserFields = ubx.FieldMap{
	"Data": ubx.FieldSpec{
		WireName: "data",
		Kind:     "object",
		Fields:   TypeResponse_Data_Relationships_CreatedByUser_DataFields,
	},
}

var TypeResponse_Data_RelationshipsFields = ubx.FieldMap{
	"CreatedByUser": ubx.FieldSpec{
		WireName: "created_by_user",
		Kind:     "object",
		Fields:   TypeResponse_Data_Relationships_CreatedByUserFields,
	},
	"GoogleMeetConfiguration": ubx.FieldSpec{
		WireName: "google_meet_configuration",
		Kind:     "object",
		Fields:   TypeResponse_Data_Relationships_CreatedByUserFields,
	},
	"LastModifiedByUser": ubx.FieldSpec{
		WireName: "last_modified_by_user",
		Kind:     "object",
		Fields:   TypeResponse_Data_Relationships_CreatedByUserFields,
	},
	"MicrosoftTeamsConfiguration": ubx.FieldSpec{
		WireName: "microsoft_teams_configuration",
		Kind:     "object",
		Fields:   TypeResponse_Data_Relationships_CreatedByUserFields,
	},
	"ZoomConfiguration": ubx.FieldSpec{
		WireName: "zoom_configuration",
		Kind:     "object",
		Fields:   TypeResponse_Data_Relationships_CreatedByUserFields,
	},
}

var TypeResponse_DataFields = ubx.FieldMap{
	"Attributes": ubx.FieldSpec{
		WireName: "attributes",
		Kind:     "object",
		Fields:   TypeResponse_Data_AttributesFields,
	},
	"Id": ubx.FieldSpec{WireName: "id"},
	"Relationships": ubx.FieldSpec{
		WireName: "relationships",
		Kind:     "object",
		Fields:   TypeResponse_Data_RelationshipsFields,
	},
	"Type": ubx.FieldSpec{WireName: "type"},
}

type TypeResponseConfig struct {
	// Incident type data for a create request.
	Data any
	// path parameter, not part of the API's own resource representation
	IncidentTypeId any
}

type TypeResponseAttrs struct {
	// Incident type data for a create request.
	Data any
	// path parameter, not part of the API's own resource representation
	IncidentTypeId any
}

var TypeResponse = ubx.ResourceBinding{
	WireType: "datadog_incident_type_response",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind:     "object",
			Fields:   TypeResponse_DataFields,
		},
		"IncidentTypeId": ubx.FieldSpec{WireName: "incident_type_id"},
	},
}
