// Code generated by `ubx sdk gen` from datadog_custom_ruleset_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_Arguments {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_Tests {
  annotationCount?: number | Computed<number>;
  code?: string | Computed<string>;
  filename?: string | Computed<string>;
}

export interface RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes {
  arguments?: RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_Arguments[] | Computed<RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_Arguments[]>;
  category?: string | Computed<string>;
  checksum?: string | Computed<string>;
  code?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  creationMessage?: string | Computed<string>;
  cve?: string | Computed<string>;
  cwe?: string | Computed<string>;
  description?: string | Computed<string>;
  documentationUrl?: string | Computed<string>;
  isPublished?: boolean | Computed<boolean>;
  isTesting?: boolean | Computed<boolean>;
  language?: string | Computed<string>;
  severity?: string | Computed<string>;
  shortDescription?: string | Computed<string>;
  shouldUseAiFix?: boolean | Computed<boolean>;
  tags?: string[] | Computed<string[]>;
  tests?: RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_Tests[] | Computed<RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_Tests[]>;
  treeSitterQuery?: string | Computed<string>;
}

export interface RulesetResponse_Data_Attributes_Rules_LastRevision {
  attributes?: RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes | Computed<RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface RulesetResponse_Data_Attributes_Rules {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  lastRevision?: RulesetResponse_Data_Attributes_Rules_LastRevision | Computed<RulesetResponse_Data_Attributes_Rules_LastRevision>;
  name?: string | Computed<string>;
}

export interface RulesetResponse_Data_Attributes {
  /** Base64-encoded full description */
  description?: string | Computed<string>;
  /** Ruleset name */
  name?: string | Computed<string>;
  /** Rules in the ruleset */
  rules?: RulesetResponse_Data_Attributes_Rules[] | Computed<RulesetResponse_Data_Attributes_Rules[]>;
  /** Base64-encoded short description */
  shortDescription?: string | Computed<string>;
}

export interface RulesetResponse_Data {
  /** Attributes for creating or updating a custom ruleset. */
  attributes?: RulesetResponse_Data_Attributes | Computed<RulesetResponse_Data_Attributes>;
  /** Ruleset identifier */
  id?: string | Computed<string>;
  /** Resource type */
  type?: string | Computed<string>;
}

const RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_ArgumentsFields: FieldMap = {
  description: "description",
  name: "name",
};

const RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_TestsFields: FieldMap = {
  annotationCount: "annotation_count",
  code: "code",
  filename: "filename",
};

const RulesetResponse_Data_Attributes_Rules_LastRevision_AttributesFields: FieldMap = {
  arguments: {
    wireName: "arguments",
    kind: "list",
    fields: RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_ArgumentsFields,
  },
  category: "category",
  checksum: "checksum",
  code: "code",
  createdAt: "created_at",
  createdBy: "created_by",
  creationMessage: "creation_message",
  cve: "cve",
  cwe: "cwe",
  description: "description",
  documentationUrl: "documentation_url",
  isPublished: "is_published",
  isTesting: "is_testing",
  language: "language",
  severity: "severity",
  shortDescription: "short_description",
  shouldUseAiFix: "should_use_ai_fix",
  tags: "tags",
  tests: {
    wireName: "tests",
    kind: "list",
    fields: RulesetResponse_Data_Attributes_Rules_LastRevision_Attributes_TestsFields,
  },
  treeSitterQuery: "tree_sitter_query",
};

const RulesetResponse_Data_Attributes_Rules_LastRevisionFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: RulesetResponse_Data_Attributes_Rules_LastRevision_AttributesFields,
  },
  id: "id",
  type: "type",
};

const RulesetResponse_Data_Attributes_RulesFields: FieldMap = {
  createdAt: "created_at",
  createdBy: "created_by",
  lastRevision: {
    wireName: "last_revision",
    kind: "object",
    fields: RulesetResponse_Data_Attributes_Rules_LastRevisionFields,
  },
  name: "name",
};

const RulesetResponse_Data_AttributesFields: FieldMap = {
  description: "description",
  name: "name",
  rules: {
    wireName: "rules",
    kind: "list",
    fields: RulesetResponse_Data_Attributes_RulesFields,
  },
  shortDescription: "short_description",
};

const RulesetResponse_DataFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: RulesetResponse_Data_AttributesFields,
  },
  id: "id",
  type: "type",
};

export interface RulesetResponseConfig {
  /** Data object for a custom ruleset create or update request. */
  data?: RulesetResponse_Data | Computed<RulesetResponse_Data>;
  /** path parameter, not part of the API's own resource representation */
  rulesetName: string | Computed<string>;
}

export interface RulesetResponseAttrs {
  /** Data object for a custom ruleset create or update request. */
  data: RulesetResponse_Data;
  /** path parameter, not part of the API's own resource representation */
  rulesetName: string;
}

export const RulesetResponse: ResourceBinding<RulesetResponseConfig, RulesetResponseAttrs> = {
  wireType: "datadog_custom_ruleset_response",
  fields: {
    data: {
      wireName: "data",
      kind: "object",
      fields: RulesetResponse_DataFields,
    },
    rulesetName: "ruleset_name",
  },
};
