# Code generated by `ubx sdk gen` from datadog_synthetics_mobile_test. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MobileTest_Config_Variables:
    example: Any = None
    id: Any = None
    name: Any = None
    pattern: Any = None
    secure: Any = None
    type: Any = None

@dataclasses.dataclass
class MobileTest_Config:
    # Initial application arguments for a mobile test.
    initial_application_arguments: Any = None
    # Array of variables used for the test steps.
    variables: Any = None

@dataclasses.dataclass
class MobileTest_Options_Bindings:
    principals: Any = None
    relation: Any = None

@dataclasses.dataclass
class MobileTest_Options_Ci:
    # Execution rule for a Synthetic test.
    execution_rule: Any = None

@dataclasses.dataclass
class MobileTest_Options_MobileApplication:
    # Application ID of the mobile application.
    application_id: Any = None
    # Reference ID of the mobile application.
    reference_id: Any = None
    # Reference type for the mobile application for a mobile synthetics test.
    reference_type: Any = None

@dataclasses.dataclass
class MobileTest_Options_MonitorOptions:
    # Message to include in the escalation notification.
    escalation_message: Any = None
    # The name of the preset for the notification for the monitor.
    notification_preset_name: Any = None
    # Time interval before renotifying if the test is still failing (in minutes).
    renotify_interval: Any = None
    # The number of times to renotify if the test is still failing.
    renotify_occurrences: Any = None

@dataclasses.dataclass
class MobileTest_Options_Retry:
    # Number of times a test needs to be retried before marking a location as failed. Defaults to 0.
    count: Any = None
    # Time interval between retries (in milliseconds). Defaults to 300ms.
    interval: Any = None

@dataclasses.dataclass
class MobileTest_Options_Scheduling_Timeframes:
    day: Any = None
    from_: Any = None
    to: Any = None

@dataclasses.dataclass
class MobileTest_Options_Scheduling:
    # Array containing objects describing the scheduling pattern to apply to each day.
    timeframes: Any = None
    # Timezone in which the timeframe is based.
    timezone: Any = None

@dataclasses.dataclass
class MobileTest_Options:
    # A boolean to set if an application crash would mark the test as failed.
    allow_application_crash: Any = None
    # Array of bindings used for the mobile test.
    bindings: Any = None
    # CI/CD options for a Synthetic test.
    ci: Any = None
    # The default timeout for steps in the test (in seconds).
    default_step_timeout: Any = None
    # For mobile test, array with the different device IDs used to run the test.
    device_ids: Any = None
    # A boolean to disable auto accepting alerts.
    disable_auto_accept_alert: Any = None
    # Minimum amount of time in failure required to trigger an alert.
    min_failure_duration: Any = None
    # Mobile application for mobile synthetics test.
    mobile_application: Any = None
    # The monitor name is used for the alert title as well as for all monitor dashboard widgets and SLOs.
    monitor_name: Any = None
    # Object containing the options for a Synthetic test as a monitor (for example, renotification).
    monitor_options: Any = None
    # Integer from 1 (high) to 5 (low) indicating alert severity.
    monitor_priority: Any = None
    # A boolean set to not take a screenshot for the step.
    no_screenshot: Any = None
    # A list of role identifiers that can be pulled from the Roles API, for restricting read and write access. This field is deprecated. Use the restriction policies API to manage permissions.
    restricted_roles: Any = None
    # Object describing the retry strategy to apply to a Synthetic test.
    retry: Any = None
    # Object containing timeframes and timezone used for advanced scheduling.
    scheduling: Any = None
    # The frequency at which to run the Synthetic test (in seconds).
    tick_every: Any = None
    # The level of verbosity for the mobile test. This field can not be set by a user.
    verbosity: Any = None

@dataclasses.dataclass
class MobileTest_Steps_Params_Element_RelativePosition:
    x: Any = None
    y: Any = None

@dataclasses.dataclass
class MobileTest_Steps_Params_Element_UserLocator_Values:
    type: Any = None
    value: Any = None

@dataclasses.dataclass
class MobileTest_Steps_Params_Element_UserLocator:
    fail_test_on_cannot_locate: Any = None
    values: Any = None

@dataclasses.dataclass
class MobileTest_Steps_Params_Element:
    context: Any = None
    context_type: Any = None
    element_description: Any = None
    multi_locator: Any = None
    relative_position: Any = None
    text_content: Any = None
    user_locator: Any = None
    view_name: Any = None

@dataclasses.dataclass
class MobileTest_Steps_Params_Variable:
    example: Any = None
    name: Any = None

@dataclasses.dataclass
class MobileTest_Steps_Params:
    check: Any = None
    delay: Any = None
    direction: Any = None
    element: Any = None
    enabled: Any = None
    max_scrolls: Any = None
    positions: Any = None
    subtest_public_id: Any = None
    value: Any = None
    variable: Any = None
    with_enter: Any = None
    x: Any = None
    y: Any = None

@dataclasses.dataclass
class MobileTest_Steps:
    allow_failure: Any = None
    has_new_step_element: Any = None
    is_critical: Any = None
    name: Any = None
    no_screenshot: Any = None
    params: Any = None
    public_id: Any = None
    timeout: Any = None
    type: Any = None

_MobileTest_Config_VariablesFields = {
    "example": ubx.FieldSpec(wire_name="example"),
    "id": ubx.FieldSpec(wire_name="id"),
    "name": ubx.FieldSpec(wire_name="name"),
    "pattern": ubx.FieldSpec(wire_name="pattern"),
    "secure": ubx.FieldSpec(wire_name="secure"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_MobileTest_ConfigFields = {
    "initial_application_arguments": ubx.FieldSpec(wire_name="initial_application_arguments"),
    "variables": ubx.FieldSpec(
        wire_name="variables",
        kind="list",
        fields=_MobileTest_Config_VariablesFields,
    ),
}

_MobileTest_Options_BindingsFields = {
    "principals": ubx.FieldSpec(wire_name="principals"),
    "relation": ubx.FieldSpec(wire_name="relation"),
}

_MobileTest_Options_CiFields = {
    "execution_rule": ubx.FieldSpec(wire_name="execution_rule"),
}

_MobileTest_Options_MobileApplicationFields = {
    "application_id": ubx.FieldSpec(wire_name="application_id"),
    "reference_id": ubx.FieldSpec(wire_name="reference_id"),
    "reference_type": ubx.FieldSpec(wire_name="reference_type"),
}

_MobileTest_Options_MonitorOptionsFields = {
    "escalation_message": ubx.FieldSpec(wire_name="escalation_message"),
    "notification_preset_name": ubx.FieldSpec(wire_name="notification_preset_name"),
    "renotify_interval": ubx.FieldSpec(wire_name="renotify_interval"),
    "renotify_occurrences": ubx.FieldSpec(wire_name="renotify_occurrences"),
}

_MobileTest_Options_RetryFields = {
    "count": ubx.FieldSpec(wire_name="count"),
    "interval": ubx.FieldSpec(wire_name="interval"),
}

_MobileTest_Options_Scheduling_TimeframesFields = {
    "day": ubx.FieldSpec(wire_name="day"),
    "from_": ubx.FieldSpec(wire_name="from"),
    "to": ubx.FieldSpec(wire_name="to"),
}

_MobileTest_Options_SchedulingFields = {
    "timeframes": ubx.FieldSpec(
        wire_name="timeframes",
        kind="list",
        fields=_MobileTest_Options_Scheduling_TimeframesFields,
    ),
    "timezone": ubx.FieldSpec(wire_name="timezone"),
}

_MobileTest_OptionsFields = {
    "allow_application_crash": ubx.FieldSpec(wire_name="allow_application_crash"),
    "bindings": ubx.FieldSpec(
        wire_name="bindings",
        kind="list",
        fields=_MobileTest_Options_BindingsFields,
    ),
    "ci": ubx.FieldSpec(
        wire_name="ci",
        kind="object",
        fields=_MobileTest_Options_CiFields,
    ),
    "default_step_timeout": ubx.FieldSpec(wire_name="default_step_timeout"),
    "device_ids": ubx.FieldSpec(wire_name="device_ids"),
    "disable_auto_accept_alert": ubx.FieldSpec(wire_name="disable_auto_accept_alert"),
    "min_failure_duration": ubx.FieldSpec(wire_name="min_failure_duration"),
    "mobile_application": ubx.FieldSpec(
        wire_name="mobile_application",
        kind="object",
        fields=_MobileTest_Options_MobileApplicationFields,
    ),
    "monitor_name": ubx.FieldSpec(wire_name="monitor_name"),
    "monitor_options": ubx.FieldSpec(
        wire_name="monitor_options",
        kind="object",
        fields=_MobileTest_Options_MonitorOptionsFields,
    ),
    "monitor_priority": ubx.FieldSpec(wire_name="monitor_priority"),
    "no_screenshot": ubx.FieldSpec(wire_name="no_screenshot"),
    "restricted_roles": ubx.FieldSpec(wire_name="restricted_roles"),
    "retry": ubx.FieldSpec(
        wire_name="retry",
        kind="object",
        fields=_MobileTest_Options_RetryFields,
    ),
    "scheduling": ubx.FieldSpec(
        wire_name="scheduling",
        kind="object",
        fields=_MobileTest_Options_SchedulingFields,
    ),
    "tick_every": ubx.FieldSpec(wire_name="tick_every"),
    "verbosity": ubx.FieldSpec(wire_name="verbosity"),
}

_MobileTest_Steps_Params_Element_RelativePositionFields = {
    "x": ubx.FieldSpec(wire_name="x"),
    "y": ubx.FieldSpec(wire_name="y"),
}

_MobileTest_Steps_Params_Element_UserLocator_ValuesFields = {
    "type": ubx.FieldSpec(wire_name="type"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_MobileTest_Steps_Params_Element_UserLocatorFields = {
    "fail_test_on_cannot_locate": ubx.FieldSpec(wire_name="fail_test_on_cannot_locate"),
    "values": ubx.FieldSpec(
        wire_name="values",
        kind="list",
        fields=_MobileTest_Steps_Params_Element_UserLocator_ValuesFields,
    ),
}

_MobileTest_Steps_Params_ElementFields = {
    "context": ubx.FieldSpec(wire_name="context"),
    "context_type": ubx.FieldSpec(wire_name="context_type"),
    "element_description": ubx.FieldSpec(wire_name="element_description"),
    "multi_locator": ubx.FieldSpec(wire_name="multi_locator"),
    "relative_position": ubx.FieldSpec(
        wire_name="relative_position",
        kind="object",
        fields=_MobileTest_Steps_Params_Element_RelativePositionFields,
    ),
    "text_content": ubx.FieldSpec(wire_name="text_content"),
    "user_locator": ubx.FieldSpec(
        wire_name="user_locator",
        kind="object",
        fields=_MobileTest_Steps_Params_Element_UserLocatorFields,
    ),
    "view_name": ubx.FieldSpec(wire_name="view_name"),
}

_MobileTest_Steps_Params_VariableFields = {
    "example": ubx.FieldSpec(wire_name="example"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_MobileTest_Steps_ParamsFields = {
    "check": ubx.FieldSpec(wire_name="check"),
    "delay": ubx.FieldSpec(wire_name="delay"),
    "direction": ubx.FieldSpec(wire_name="direction"),
    "element": ubx.FieldSpec(
        wire_name="element",
        kind="object",
        fields=_MobileTest_Steps_Params_ElementFields,
    ),
    "enabled": ubx.FieldSpec(wire_name="enabled"),
    "max_scrolls": ubx.FieldSpec(wire_name="max_scrolls"),
    "positions": ubx.FieldSpec(
        wire_name="positions",
        kind="list",
        fields=_MobileTest_Steps_Params_Element_RelativePositionFields,
    ),
    "subtest_public_id": ubx.FieldSpec(wire_name="subtest_public_id"),
    "value": ubx.FieldSpec(wire_name="value"),
    "variable": ubx.FieldSpec(
        wire_name="variable",
        kind="object",
        fields=_MobileTest_Steps_Params_VariableFields,
    ),
    "with_enter": ubx.FieldSpec(wire_name="with_enter"),
    "x": ubx.FieldSpec(wire_name="x"),
    "y": ubx.FieldSpec(wire_name="y"),
}

_MobileTest_StepsFields = {
    "allow_failure": ubx.FieldSpec(wire_name="allow_failure"),
    "has_new_step_element": ubx.FieldSpec(wire_name="has_new_step_element"),
    "is_critical": ubx.FieldSpec(wire_name="is_critical"),
    "name": ubx.FieldSpec(wire_name="name"),
    "no_screenshot": ubx.FieldSpec(wire_name="no_screenshot"),
    "params": ubx.FieldSpec(
        wire_name="params",
        kind="object",
        fields=_MobileTest_Steps_ParamsFields,
    ),
    "public_id": ubx.FieldSpec(wire_name="public_id"),
    "timeout": ubx.FieldSpec(wire_name="timeout"),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class MobileTestConfig:
    # Configuration object for a Synthetic mobile test.
    config: Any = None
    # Array with the different device IDs used to run the test.
    device_ids: Any = None
    # Notification message associated with the test.
    message: Any = None
    # Name of the test.
    name: Any = None
    # Object describing the extra options for a Synthetic test.
    options: Any = None
    # Define whether you want to start (`live`) or pause (`paused`) a Synthetic test.
    status: Any = None
    # Array of steps for the test.
    steps: Any = None
    # Array of tags attached to the test.
    tags: Any = None
    # Type of the Synthetic test, `mobile`.
    type: Any = None

@dataclasses.dataclass
class MobileTestAttrs:
    # Configuration object for a Synthetic mobile test.
    config: Any = None
    # Array with the different device IDs used to run the test.
    device_ids: Any = None
    # Notification message associated with the test.
    message: Any = None
    # The associated monitor ID.
    monitor_id: Any = None
    # Name of the test.
    name: Any = None
    # Object describing the extra options for a Synthetic test.
    options: Any = None
    # The public ID of the test.
    public_id: Any = None
    # Define whether you want to start (`live`) or pause (`paused`) a Synthetic test.
    status: Any = None
    # Array of steps for the test.
    steps: Any = None
    # Array of tags attached to the test.
    tags: Any = None
    # Type of the Synthetic test, `mobile`.
    type: Any = None

MobileTest = ubx.ResourceBinding(
    wire_type="datadog_synthetics_mobile_test",
    fields={
        "config": ubx.FieldSpec(
            wire_name="config",
            kind="object",
            fields=_MobileTest_ConfigFields,
        ),
        "device_ids": ubx.FieldSpec(wire_name="device_ids"),
        "message": ubx.FieldSpec(wire_name="message"),
        "name": ubx.FieldSpec(wire_name="name"),
        "options": ubx.FieldSpec(
            wire_name="options",
            kind="object",
            fields=_MobileTest_OptionsFields,
        ),
        "status": ubx.FieldSpec(wire_name="status"),
        "steps": ubx.FieldSpec(
            wire_name="steps",
            kind="list",
            fields=_MobileTest_StepsFields,
        ),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "type": ubx.FieldSpec(wire_name="type"),
    },
)
