# Code generated by `ubx sdk gen` from datadog_llmobs_annotated_interactions_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AnnotatedInteractionsResponse_Data_Attributes_AnnotatedInteractions_Annotations:
    created_at: Any = None
    created_by: Any = None
    id: Any = None
    interaction_id: Any = None
    label_values: Any = None
    modified_at: Any = None
    modified_by: Any = None

@dataclasses.dataclass
class AnnotatedInteractionsResponse_Data_Attributes_AnnotatedInteractions_DisplayBlock_TimeFrame:
    end: Any = None
    start: Any = None

@dataclasses.dataclass
class AnnotatedInteractionsResponse_Data_Attributes_AnnotatedInteractions_DisplayBlock:
    alt: Any = None
    content: Any = None
    height: Any = None
    interaction_type: Any = None
    label: Any = None
    level: Any = None
    tile_def: Any = None
    time_frame: Any = None
    trace_id: Any = None
    type: Any = None
    url: Any = None

@dataclasses.dataclass
class AnnotatedInteractionsResponse_Data_Attributes_AnnotatedInteractions:
    annotations: Any = None
    content_id: Any = None
    created_at: Any = None
    display_block: Any = None
    id: Any = None
    modified_at: Any = None
    type: Any = None

@dataclasses.dataclass
class AnnotatedInteractionsResponse_Data_Attributes:
    # List of interactions with their annotations.
    annotated_interactions: Any = None

@dataclasses.dataclass
class AnnotatedInteractionsResponse_Data:
    # Attributes containing the list of annotated interactions.
    attributes: Any = None
    # The annotation queue ID.
    id: Any = None
    # Resource type for annotated interactions.
    type: Any = None

@dataclasses.dataclass
class AnnotatedInteractionsResponseConfig:
    queue_id: Any = None

@dataclasses.dataclass
class AnnotatedInteractionsResponseAttrs:
    # Data object for annotated interactions.
    data: Any = None
    queue_id: Any = None

AnnotatedInteractionsResponse = ubx.DataSourceBinding(
    wire_type="datadog_llmobs_annotated_interactions_response",
    fields={
        "queue_id": ubx.FieldSpec(wire_name="queue_id"),
    },
)
