# Code generated by `ubx sdk gen` from datadog_llmobs_patterns_topics_with_clustered_points_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PatternsTopicsWithClusteredPointsResponse_Data_Attributes_ConfigSnapshot:
    # Integration account ID used for a bring-your-own-model run.
    account_id: Any = None
    # Query that selected the spans for the run.
    evp_query: Any = None
    # Depth of the topic hierarchy generated.
    hierarchy_depth: Any = None
    # Integration provider used for a bring-your-own-model run.
    integration_provider: Any = None
    # Model name used for a bring-your-own-model run.
    model_name: Any = None
    # Maximum number of records processed for the run.
    num_records: Any = None
    # Fraction of matching spans sampled for the run.
    sampling_ratio: Any = None

@dataclasses.dataclass
class PatternsTopicsWithClusteredPointsResponse_Data_Attributes_Topics_ClusterPoints:
    duration: Any = None
    estimated_total_cost: Any = None
    evaluation: Any = None
    input_tokens: Any = None
    output_tokens: Any = None
    span_id: Any = None
    status: Any = None
    total_tokens: Any = None

@dataclasses.dataclass
class PatternsTopicsWithClusteredPointsResponse_Data_Attributes_Topics:
    cluster_points: Any = None
    created_at: Any = None
    description: Any = None
    first_seen_at: Any = None
    hierarchy_level: Any = None
    id: Any = None
    is_validated: Any = None
    name: Any = None
    parent_topic_id: Any = None
    point_count: Any = None
    run_id: Any = None

@dataclasses.dataclass
class PatternsTopicsWithClusteredPointsResponse_Data_Attributes:
    # Timestamp when the run completed. Null if the run has not completed.
    completed_at: Any = None
    # Identifier of the configuration that produced the run.
    config_id: Any = None
    # Snapshot of the configuration used for a patterns run.
    config_snapshot: Any = None
    # Timestamp when the run was created.
    created_at: Any = None
    # Identifier of the run that completed immediately before this one. Empty if none.
    previous_run_id: Any = None
    # Identifier of the run that produced the topics.
    run_id: Any = None
    # List of discovered topics with their clustered points.
    topics: Any = None

@dataclasses.dataclass
class PatternsTopicsWithClusteredPointsResponse_Data:
    # Attributes of an Agent Observability patterns topics-with-clustered-points response.
    attributes: Any = None
    # Identifier of the run the topics belong to.
    id: Any = None
    # Resource type of an Agent Observability patterns topics-with-clustered-points response.
    type: Any = None

@dataclasses.dataclass
class PatternsTopicsWithClusteredPointsResponseConfig:
    config_id: Any = None
    include_metrics: Any = None
    run_id: Any = None

@dataclasses.dataclass
class PatternsTopicsWithClusteredPointsResponseAttrs:
    config_id: Any = None
    # Data object of an Agent Observability patterns topics-with-clustered-points response.
    data: Any = None
    include_metrics: Any = None
    run_id: Any = None

PatternsTopicsWithClusteredPointsResponse = ubx.DataSourceBinding(
    wire_type="datadog_llmobs_patterns_topics_with_clustered_points_response",
    fields={
        "config_id": ubx.FieldSpec(wire_name="config_id"),
        "include_metrics": ubx.FieldSpec(wire_name="include_metrics"),
        "run_id": ubx.FieldSpec(wire_name="run_id"),
    },
)
