// Code generated by `ubx sdk gen` from datadog_projects_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Response_Data_Attributes_ColumnsConfig_Columns_Sort {
  ascending?: boolean | Computed<boolean>;
  priority?: number | Computed<number>;
}

export interface Response_Data_Attributes_ColumnsConfig_Columns {
  sort?: Response_Data_Attributes_ColumnsConfig_Columns_Sort | Computed<Response_Data_Attributes_ColumnsConfig_Columns_Sort>;
  sortField?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Response_Data_Attributes_ColumnsConfig {
  columns?: Response_Data_Attributes_ColumnsConfig_Columns[] | Computed<Response_Data_Attributes_ColumnsConfig_Columns[]>;
}

export interface Response_Data_Attributes_Settings_AutoCloseInactiveCases {
  enabled?: boolean | Computed<boolean>;
  maxInactiveTimeInSecs?: number | Computed<number>;
}

export interface Response_Data_Attributes_Settings_AutoTransitionAssignedCases {
  autoTransitionAssignedCasesOnSelfAssigned?: boolean | Computed<boolean>;
}

export interface Response_Data_Attributes_Settings_IntegrationIncident_FieldMappings {
  caseField?: string | Computed<string>;
  incidentUserDefinedFieldId?: string | Computed<string>;
}

export interface Response_Data_Attributes_Settings_IntegrationIncident_SeverityConfig {
  priorityMapping?: Record<string, string> | Computed<Record<string, string>>;
}

export interface Response_Data_Attributes_Settings_IntegrationIncident {
  autoEscalationQuery?: string | Computed<string>;
  defaultIncidentCommander?: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  fieldMappings?: Response_Data_Attributes_Settings_IntegrationIncident_FieldMappings[] | Computed<Response_Data_Attributes_Settings_IntegrationIncident_FieldMappings[]>;
  incidentType?: string | Computed<string>;
  severityConfig?: Response_Data_Attributes_Settings_IntegrationIncident_SeverityConfig | Computed<Response_Data_Attributes_Settings_IntegrationIncident_SeverityConfig>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira_AutoCreation {
  enabled?: boolean | Computed<boolean>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira_Metadata {
  accountId?: string | Computed<string>;
  issueTypeId?: string | Computed<string>;
  projectId?: string | Computed<string>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee {
  syncType?: string | Computed<string>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_CustomFields {
  syncType?: string | Computed<string>;
  value?: unknown | Computed<unknown>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_DueDate {
  jiraFieldId?: string | Computed<string>;
  syncType?: string | Computed<string>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Priority {
  mapping?: Record<string, string> | Computed<Record<string, string>>;
  nameMapping?: Record<string, string> | Computed<Record<string, string>>;
  syncType?: string | Computed<string>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties {
  assignee?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee>;
  comments?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee>;
  customFields?: Record<string, Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_CustomFields> | Computed<Record<string, Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_CustomFields>>;
  description?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee>;
  dueDate?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_DueDate | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_DueDate>;
  priority?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Priority | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Priority>;
  status?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Priority | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Priority>;
  title?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira_Sync {
  enabled?: boolean | Computed<boolean>;
  properties?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties>;
}

export interface Response_Data_Attributes_Settings_IntegrationJira {
  autoCreation?: Response_Data_Attributes_Settings_IntegrationJira_AutoCreation | Computed<Response_Data_Attributes_Settings_IntegrationJira_AutoCreation>;
  enabled?: boolean | Computed<boolean>;
  metadata?: Response_Data_Attributes_Settings_IntegrationJira_Metadata | Computed<Response_Data_Attributes_Settings_IntegrationJira_Metadata>;
  sync?: Response_Data_Attributes_Settings_IntegrationJira_Sync | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync>;
}

export interface Response_Data_Attributes_Settings_IntegrationMonitor {
  autoResolveEnabled?: boolean | Computed<boolean>;
  caseTypeId?: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  handle?: string | Computed<string>;
}

export interface Response_Data_Attributes_Settings_IntegrationOnCall_EscalationQueries_Target {
  dynamicTeamPaging?: boolean | Computed<boolean>;
  teamId?: string | Computed<string>;
  userId?: string | Computed<string>;
}

export interface Response_Data_Attributes_Settings_IntegrationOnCall_EscalationQueries {
  enabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  query?: string | Computed<string>;
  target?: Response_Data_Attributes_Settings_IntegrationOnCall_EscalationQueries_Target | Computed<Response_Data_Attributes_Settings_IntegrationOnCall_EscalationQueries_Target>;
}

export interface Response_Data_Attributes_Settings_IntegrationOnCall {
  autoAssignOnCall?: boolean | Computed<boolean>;
  enabled?: boolean | Computed<boolean>;
  escalationQueries?: Response_Data_Attributes_Settings_IntegrationOnCall_EscalationQueries[] | Computed<Response_Data_Attributes_Settings_IntegrationOnCall_EscalationQueries[]>;
}

export interface Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig_Properties_Priority {
  impactMapping?: Record<string, string> | Computed<Record<string, string>>;
  syncType?: string | Computed<string>;
  urgencyMapping?: Record<string, string> | Computed<Record<string, string>>;
}

export interface Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig_Properties {
  comments?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Assignee>;
  priority?: Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig_Properties_Priority | Computed<Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig_Properties_Priority>;
  status?: Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Priority | Computed<Response_Data_Attributes_Settings_IntegrationJira_Sync_Properties_Priority>;
}

export interface Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig {
  enabled?: boolean | Computed<boolean>;
  properties?: Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig_Properties | Computed<Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig_Properties>;
}

export interface Response_Data_Attributes_Settings_IntegrationServiceNow {
  assignmentGroup?: string | Computed<string>;
  autoCreation?: Response_Data_Attributes_Settings_IntegrationJira_AutoCreation | Computed<Response_Data_Attributes_Settings_IntegrationJira_AutoCreation>;
  enabled?: boolean | Computed<boolean>;
  instanceName?: string | Computed<string>;
  syncConfig?: Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig | Computed<Response_Data_Attributes_Settings_IntegrationServiceNow_SyncConfig>;
}

export interface Response_Data_Attributes_Settings_Notification {
  destinations?: number[] | Computed<number[]>;
  enabled?: boolean | Computed<boolean>;
  notifyOnCaseAssignment?: boolean | Computed<boolean>;
  notifyOnCaseClosed?: boolean | Computed<boolean>;
  notifyOnCaseComment?: boolean | Computed<boolean>;
  notifyOnCaseCommentMention?: boolean | Computed<boolean>;
  notifyOnCasePriorityChange?: boolean | Computed<boolean>;
  notifyOnCaseStatusChange?: boolean | Computed<boolean>;
  notifyOnCaseUnassignment?: boolean | Computed<boolean>;
}

export interface Response_Data_Attributes_Settings {
  autoCloseInactiveCases?: Response_Data_Attributes_Settings_AutoCloseInactiveCases | Computed<Response_Data_Attributes_Settings_AutoCloseInactiveCases>;
  autoTransitionAssignedCases?: Response_Data_Attributes_Settings_AutoTransitionAssignedCases | Computed<Response_Data_Attributes_Settings_AutoTransitionAssignedCases>;
  integrationIncident?: Response_Data_Attributes_Settings_IntegrationIncident | Computed<Response_Data_Attributes_Settings_IntegrationIncident>;
  integrationJira?: Response_Data_Attributes_Settings_IntegrationJira | Computed<Response_Data_Attributes_Settings_IntegrationJira>;
  integrationMonitor?: Response_Data_Attributes_Settings_IntegrationMonitor | Computed<Response_Data_Attributes_Settings_IntegrationMonitor>;
  integrationOnCall?: Response_Data_Attributes_Settings_IntegrationOnCall | Computed<Response_Data_Attributes_Settings_IntegrationOnCall>;
  integrationServiceNow?: Response_Data_Attributes_Settings_IntegrationServiceNow | Computed<Response_Data_Attributes_Settings_IntegrationServiceNow>;
  notification?: Response_Data_Attributes_Settings_Notification | Computed<Response_Data_Attributes_Settings_Notification>;
}

export interface Response_Data_Attributes {
  columnsConfig?: Response_Data_Attributes_ColumnsConfig | Computed<Response_Data_Attributes_ColumnsConfig>;
  enabledCustomCaseTypes?: string[] | Computed<string[]>;
  key?: string | Computed<string>;
  name?: string | Computed<string>;
  restricted?: boolean | Computed<boolean>;
  settings?: Response_Data_Attributes_Settings | Computed<Response_Data_Attributes_Settings>;
}

export interface Response_Data_Relationships_MemberTeam_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Response_Data_Relationships_MemberTeam_Links {
  related?: string | Computed<string>;
}

export interface Response_Data_Relationships_MemberTeam {
  data?: Response_Data_Relationships_MemberTeam_Data[] | Computed<Response_Data_Relationships_MemberTeam_Data[]>;
  links?: Response_Data_Relationships_MemberTeam_Links | Computed<Response_Data_Relationships_MemberTeam_Links>;
}

export interface Response_Data_Relationships_MemberUser {
  data?: Response_Data_Relationships_MemberTeam_Data[] | Computed<Response_Data_Relationships_MemberTeam_Data[]>;
}

export interface Response_Data_Relationships {
  memberTeam?: Response_Data_Relationships_MemberTeam | Computed<Response_Data_Relationships_MemberTeam>;
  memberUser?: Response_Data_Relationships_MemberUser | Computed<Response_Data_Relationships_MemberUser>;
}

export interface Response_Data {
  attributes?: Response_Data_Attributes | Computed<Response_Data_Attributes>;
  id?: string | Computed<string>;
  relationships?: Response_Data_Relationships | Computed<Response_Data_Relationships>;
  type?: string | Computed<string>;
}

export interface ResponseConfig {
}

export interface ResponseAttrs {
  /** Projects response data. */
  data: Response_Data[];
}

export const Response: DataSourceBinding<ResponseConfig, ResponseAttrs> = {
  wireType: "datadog_projects_response",
  fields: {
  },
};
