// Code generated by `ubx sdk gen` from datadog_org_data. DO NOT EDIT.
package org

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Data_Data_Relationships_CurrentOrg_Data struct {
	// The UUID of the organization.
	Id any
	// The resource type for organizations.
	Type any
}

type Data_Data_Relationships_CurrentOrg struct {
	// Reference to an organization resource.
	Data any
}

type Data_Data_Relationships_ManagedOrgs struct {
	// List of managed organization references.
	Data any
}

type Data_Data_Relationships struct {
	// Relationship to the current organization.
	CurrentOrg any
	// Relationship to the managed organizations.
	ManagedOrgs any
}

type Data_Data struct {
	// The UUID of the current organization.
	Id any
	// Relationships of the managed organizations resource.
	Relationships any
	// The resource type for managed organizations.
	Type any
}

type Data_Included_Attributes struct {
	CreatedAt   any
	Description any
	Disabled    any
	ModifiedAt  any
	Name        any
	PublicId    any
	Sharing     any
	Url         any
}

type Data_Included struct {
	Attributes any
	Id         any
	Type       any
}

type DataConfig struct {
}

type DataAttrs struct {
	// The managed organizations resource.
	Data any
	// Included organization resources.
	Included any
}

var Data = ubx.DataSourceBinding{
	WireType: "datadog_org_data",
	Fields:   ubx.FieldMap{},
}
