// Code generated by `ubx sdk gen` from datadog_playlist_data. DO NOT EDIT.
package playlist

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Data_Data_Attributes_CreatedBy struct {
	Handle any
	Icon any
	Id any
	Name any
	Uuid any
}

type Data_Data_Attributes struct {
	CreatedAt any
	CreatedBy any
	Description any
	Name any
	SessionCount any
	UpdatedAt any
}

type Data_Data struct {
	Attributes any
	Id any
	Type any
}

type DataConfig struct {
}

type DataAttrs struct {
	// Array of playlist data objects.
	Data any
}

var Data = ubx.DataSourceBinding{
	WireType: "datadog_playlist_data",
	Fields: ubx.FieldMap{
	},
}
