# Code generated by `ubx sdk gen` from datadog_ai_custom_ruleset_response_data. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CustomRulesetResponseData_Data_Attributes_Rules_LastRevision:
    category: Any = None
    checksum: Any = None
    content: Any = None
    created_at: Any = None
    created_by: Any = None
    cwe: Any = None
    description: Any = None
    directories: Any = None
    execution_mode: Any = None
    globs: Any = None
    is_default: Any = None
    is_published: Any = None
    is_testing: Any = None
    severity: Any = None
    short_description: Any = None
    version_id: Any = None

@dataclasses.dataclass
class CustomRulesetResponseData_Data_Attributes_Rules:
    created_at: Any = None
    created_by: Any = None
    last_revision: Any = None
    name: Any = None

@dataclasses.dataclass
class CustomRulesetResponseData_Data_Attributes:
    created_at: Any = None
    created_by: Any = None
    description: Any = None
    name: Any = None
    rules: Any = None
    short_description: Any = None

@dataclasses.dataclass
class CustomRulesetResponseData_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class CustomRulesetResponseDataConfig:
    pass

@dataclasses.dataclass
class CustomRulesetResponseDataAttrs:
    # The list of AI custom rulesets.
    data: Any = None

CustomRulesetResponseData = ubx.DataSourceBinding(
    wire_type="datadog_ai_custom_ruleset_response_data",
    fields={
    },
)
