# Code generated by `ubx sdk gen` from datadog_synthetics_batch_details. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class BatchDetails_Data_Metadata_Ci_Pipeline:
    # URL of the pipeline.
    url: Any = None

@dataclasses.dataclass
class BatchDetails_Data_Metadata_Ci_Provider:
    # Name of the CI provider.
    name: Any = None

@dataclasses.dataclass
class BatchDetails_Data_Metadata_Ci:
    # Description of the CI pipeline.
    pipeline: Any = None
    # Description of the CI provider.
    provider: Any = None

@dataclasses.dataclass
class BatchDetails_Data_Metadata_Git:
    # Branch name.
    branch: Any = None
    # The commit SHA.
    commit_sha: Any = None

@dataclasses.dataclass
class BatchDetails_Data_Metadata:
    # Description of the CI provider.
    ci: Any = None
    # Git information.
    git: Any = None

@dataclasses.dataclass
class BatchDetails_Data_Results:
    device: Any = None
    duration: Any = None
    execution_rule: Any = None
    location: Any = None
    result_id: Any = None
    retries: Any = None
    status: Any = None
    test_name: Any = None
    test_public_id: Any = None
    test_type: Any = None

@dataclasses.dataclass
class BatchDetails_Data:
    # Metadata for the Synthetic tests run.
    metadata: Any = None
    # List of results for the batch.
    results: Any = None
    # Determines whether the batch has passed, failed, or is in progress.
    status: Any = None

@dataclasses.dataclass
class BatchDetailsConfig:
    batch_id: Any = None

@dataclasses.dataclass
class BatchDetailsAttrs:
    batch_id: Any = None
    # Wrapper object that contains the details of a batch.
    data: Any = None

BatchDetails = ubx.DataSourceBinding(
    wire_type="datadog_synthetics_batch_details",
    fields={
        "batch_id": ubx.FieldSpec(wire_name="batch_id"),
    },
)
