// Code generated by `ubx sdk gen` from datadog_host_list_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ListResponse_HostList_Meta_InstallMethod {
  installerVersion?: string | Computed<string>;
  tool?: string | Computed<string>;
  toolVersion?: string | Computed<string>;
}

export interface ListResponse_HostList_Meta {
  agentChecks?: unknown[][] | Computed<unknown[][]>;
  agentVersion?: string | Computed<string>;
  cpuCores?: number | Computed<number>;
  fbsdV?: unknown[] | Computed<unknown[]>;
  gohai?: string | Computed<string>;
  installMethod?: ListResponse_HostList_Meta_InstallMethod | Computed<ListResponse_HostList_Meta_InstallMethod>;
  macV?: unknown[] | Computed<unknown[]>;
  machine?: string | Computed<string>;
  nixV?: unknown[] | Computed<unknown[]>;
  platform?: string | Computed<string>;
  processor?: string | Computed<string>;
  pythonV?: string | Computed<string>;
  socketFqdn?: string | Computed<string>;
  socketHostname?: string | Computed<string>;
  winV?: unknown[] | Computed<unknown[]>;
}

export interface ListResponse_HostList_Metrics {
  cpu?: number | Computed<number>;
  iowait?: number | Computed<number>;
  load?: number | Computed<number>;
}

export interface ListResponse_HostList {
  aliases?: string[] | Computed<string[]>;
  apps?: string[] | Computed<string[]>;
  awsName?: string | Computed<string>;
  hostName?: string | Computed<string>;
  id?: number | Computed<number>;
  isMuted?: boolean | Computed<boolean>;
  lastReportedTime?: number | Computed<number>;
  meta?: ListResponse_HostList_Meta | Computed<ListResponse_HostList_Meta>;
  metrics?: ListResponse_HostList_Metrics | Computed<ListResponse_HostList_Metrics>;
  muteTimeout?: number | Computed<number>;
  name?: string | Computed<string>;
  sources?: string[] | Computed<string[]>;
  tagsBySource?: Record<string, string[]> | Computed<Record<string, string[]>>;
  up?: boolean | Computed<boolean>;
}

export interface ListResponseConfig {
  count?: number | Computed<number>;
  filter?: string | Computed<string>;
  from?: number | Computed<number>;
  includeHostsMetadata?: boolean | Computed<boolean>;
  includeMutedHostsData?: boolean | Computed<boolean>;
  sortDir?: string | Computed<string>;
  sortField?: string | Computed<string>;
  start?: number | Computed<number>;
}

export interface ListResponseAttrs {
  count: number;
  filter: string;
  from: number;
  /** Array of hosts. */
  hostList: ListResponse_HostList[];
  includeHostsMetadata: boolean;
  includeMutedHostsData: boolean;
  sortDir: string;
  sortField: string;
  start: number;
  /** Number of host matching the query. */
  totalMatching: number;
  /** Number of host returned. */
  totalReturned: number;
}

export const ListResponse: DataSourceBinding<ListResponseConfig, ListResponseAttrs> = {
  wireType: "datadog_host_list_response",
  fields: {
    count: "count",
    filter: "filter",
    from: "from",
    includeHostsMetadata: "include_hosts_metadata",
    includeMutedHostsData: "include_muted_hosts_data",
    sortDir: "sort_dir",
    sortField: "sort_field",
    start: "start",
  },
};
