// Code generated by `ubx sdk gen` from datadog_elastic_cloud_integration_account_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudIntegrationAccountResponse_Data_Attributes_Authentication {
  authType?: string | Computed<string>;
  password?: string | Computed<string>;
  username?: string | Computed<string>;
}

export interface CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats_Status {
  /** Collection health of a single dataflow. */
  health?: string | Computed<string>;
  /** Human-readable detail, populated when the dataflow is not healthy. */
  message?: string | Computed<string>;
  /** Time the status was last computed. */
  updatedAt?: string | Computed<string>;
}

export interface CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats {
  /** Whether the Elastic Cloud dataflow is enabled. */
  enabled?: boolean | Computed<boolean>;
  /** Read-only collection status of a dataflow. */
  status?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats_Status | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats_Status>;
}

export interface CloudIntegrationAccountResponse_Data_Attributes_Dataflows {
  /** The Elastic Cloud detailed index stats dataflow. */
  elasticCloudDetailedIndexStats?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats>;
  /** The Elastic Cloud index stats dataflow. */
  elasticCloudIndexStats?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats>;
  /** The Elastic Cloud metrics dataflow. */
  elasticCloudMetrics?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats>;
  /** The Elastic Cloud pending task stats dataflow. */
  elasticCloudPendingTaskStats?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats>;
  /** The Elastic Cloud primary shard graceful timeout dataflow. */
  elasticCloudPrimaryShardGracefulTimeout?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats>;
  /** The Elastic Cloud primary shard stats dataflow. */
  elasticCloudPrimaryShardStats?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats>;
  /** The Elastic Cloud shard allocation stats dataflow. */
  elasticCloudShardAllocationStats?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats>;
  /** The Elastic Cloud snapshot lifecycle management stats dataflow. */
  elasticCloudSlmStats?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats>;
}

export interface CloudIntegrationAccountResponse_Data_Attributes_Settings {
  /** Comma-separated list of custom tags for this Elastic Cloud deployment. */
  tags?: string | Computed<string>;
  /** Elastic Cloud deployment URL. */
  url: string | Computed<string>;
}

export interface CloudIntegrationAccountResponse_Data_Attributes {
  /** Authentication for creating the Elastic Cloud integration account. Exactly one method is set. */
  authentication: CloudIntegrationAccountResponse_Data_Attributes_Authentication | Computed<CloudIntegrationAccountResponse_Data_Attributes_Authentication>;
  /** Dataflows to configure on the Elastic Cloud integration account, keyed by dataflow id. */
  dataflows?: CloudIntegrationAccountResponse_Data_Attributes_Dataflows | Computed<CloudIntegrationAccountResponse_Data_Attributes_Dataflows>;
  /** Human-readable name of the Elastic Cloud integration account. */
  name: string | Computed<string>;
  /** Settings for creating the Elastic Cloud integration account. */
  settings: CloudIntegrationAccountResponse_Data_Attributes_Settings | Computed<CloudIntegrationAccountResponse_Data_Attributes_Settings>;
}

export interface CloudIntegrationAccountResponse_Data {
  /** Writable attributes used to create an Elastic Cloud integration account. */
  attributes: CloudIntegrationAccountResponse_Data_Attributes | Computed<CloudIntegrationAccountResponse_Data_Attributes>;
  /** Server-generated unique identifier of the Elastic Cloud integration account. */
  id?: string | Computed<string>;
  /** The type of the integration account resource. Always `integration-account`. */
  type: string | Computed<string>;
}

const CloudIntegrationAccountResponse_Data_Attributes_AuthenticationFields: FieldMap = {
  authType: "auth_type",
  password: "password",
  username: "username",
};

const CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats_StatusFields: FieldMap = {
  health: "health",
  message: "message",
  updatedAt: "updated_at",
};

const CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields: FieldMap = {
  enabled: "enabled",
  status: {
    wireName: "status",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats_StatusFields,
  },
};

const CloudIntegrationAccountResponse_Data_Attributes_DataflowsFields: FieldMap = {
  elasticCloudDetailedIndexStats: {
    wireName: "elastic_cloud_detailed_index_stats",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields,
  },
  elasticCloudIndexStats: {
    wireName: "elastic_cloud_index_stats",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields,
  },
  elasticCloudMetrics: {
    wireName: "elastic_cloud_metrics",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields,
  },
  elasticCloudPendingTaskStats: {
    wireName: "elastic_cloud_pending_task_stats",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields,
  },
  elasticCloudPrimaryShardGracefulTimeout: {
    wireName: "elastic_cloud_primary_shard_graceful_timeout",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields,
  },
  elasticCloudPrimaryShardStats: {
    wireName: "elastic_cloud_primary_shard_stats",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields,
  },
  elasticCloudShardAllocationStats: {
    wireName: "elastic_cloud_shard_allocation_stats",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields,
  },
  elasticCloudSlmStats: {
    wireName: "elastic_cloud_slm_stats",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStatsFields,
  },
};

const CloudIntegrationAccountResponse_Data_Attributes_SettingsFields: FieldMap = {
  tags: "tags",
  url: "url",
};

const CloudIntegrationAccountResponse_Data_AttributesFields: FieldMap = {
  authentication: {
    wireName: "authentication",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_AuthenticationFields,
  },
  dataflows: {
    wireName: "dataflows",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_DataflowsFields,
  },
  name: "name",
  settings: {
    wireName: "settings",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_Attributes_SettingsFields,
  },
};

const CloudIntegrationAccountResponse_DataFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: CloudIntegrationAccountResponse_Data_AttributesFields,
  },
  id: "id",
  type: "type",
};

export interface CloudIntegrationAccountResponseConfig {
  /** Data envelope for creating an Elastic Cloud integration account. */
  data: CloudIntegrationAccountResponse_Data | Computed<CloudIntegrationAccountResponse_Data>;
  /** path parameter, not part of the API's own resource representation */
  accountId: string | Computed<string>;
}

export interface CloudIntegrationAccountResponseAttrs {
  /** Data envelope for creating an Elastic Cloud integration account. */
  data: CloudIntegrationAccountResponse_Data;
  /** path parameter, not part of the API's own resource representation */
  accountId: string;
}

export const CloudIntegrationAccountResponse: ResourceBinding<CloudIntegrationAccountResponseConfig, CloudIntegrationAccountResponseAttrs> = {
  wireType: "datadog_elastic_cloud_integration_account_response",
  fields: {
    data: {
      wireName: "data",
      kind: "object",
      fields: CloudIntegrationAccountResponse_DataFields,
    },
    accountId: "account_id",
  },
};
