# Code generated by `ubx sdk gen` from datadog_salesforce_incidents_organizations_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class IncidentsOrganizationsResponse_Data_Attributes:
    instance_url: Any = None
    name: Any = None
    sfdc_org_id: Any = None
    sfdc_org_type: Any = None

@dataclasses.dataclass
class IncidentsOrganizationsResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class IncidentsOrganizationsResponseConfig:
    pass

@dataclasses.dataclass
class IncidentsOrganizationsResponseAttrs:
    # An array of Salesforce organizations.
    data: Any = None

IncidentsOrganizationsResponse = ubx.DataSourceBinding(
    wire_type="datadog_salesforce_incidents_organizations_response",
    fields={
    },
)
