# Code generated by `ubx sdk gen` from datadog_confluent_account_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AccountResponse_Data_Attributes_Resources:
    enable_custom_metrics: Any = None
    id: Any = None
    resource_type: Any = None
    tags: Any = None

@dataclasses.dataclass
class AccountResponse_Data_Attributes:
    # The API key associated with your Confluent account.
    api_key: Any = None
    # The API secret associated with your Confluent account.
    api_secret: Any = None
    # A list of Confluent resources associated with the Confluent account.
    resources: Any = None
    # A list of strings representing tags. Can be a single key, or key-value pairs separated by a colon.
    tags: Any = None

@dataclasses.dataclass
class AccountResponse_Data:
    # Attributes associated with the account creation request.
    attributes: Any = None
    # A randomly generated ID associated with a Confluent account.
    id: Any = None
    # The JSON:API type for this API. Should always be `confluent-cloud-accounts`.
    type: Any = None

_AccountResponse_Data_Attributes_ResourcesFields = {
    "enable_custom_metrics": ubx.FieldSpec(wire_name="enable_custom_metrics"),
    "id": ubx.FieldSpec(wire_name="id"),
    "resource_type": ubx.FieldSpec(wire_name="resource_type"),
    "tags": ubx.FieldSpec(wire_name="tags"),
}

_AccountResponse_Data_AttributesFields = {
    "api_key": ubx.FieldSpec(wire_name="api_key"),
    "api_secret": ubx.FieldSpec(wire_name="api_secret"),
    "resources": ubx.FieldSpec(
        wire_name="resources",
        kind="list",
        fields=_AccountResponse_Data_Attributes_ResourcesFields,
    ),
    "tags": ubx.FieldSpec(wire_name="tags"),
}

_AccountResponse_DataFields = {
    "attributes": ubx.FieldSpec(
        wire_name="attributes",
        kind="object",
        fields=_AccountResponse_Data_AttributesFields,
    ),
    "id": ubx.FieldSpec(wire_name="id"),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class AccountResponseConfig:
    # The data body for adding a Confluent account.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None

@dataclasses.dataclass
class AccountResponseAttrs:
    # The data body for adding a Confluent account.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    account_id: Any = None

AccountResponse = ubx.ResourceBinding(
    wire_type="datadog_confluent_account_response",
    fields={
        "data": ubx.FieldSpec(
            wire_name="data",
            kind="object",
            fields=_AccountResponse_DataFields,
        ),
        "account_id": ubx.FieldSpec(wire_name="account_id"),
    },
)
