# Code generated by `ubx sdk gen` from datadog_metric_metadata. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MetadataConfig:
    # Metric description.
    description: Any = None
    # Name of the integration that sent the metric if applicable.
    integration: Any = None
    # Per unit of the metric such as `second` in `bytes per second`.
    per_unit: Any = None
    # A more human-readable and abbreviated version of the metric name.
    short_name: Any = None
    # StatsD flush interval of the metric in seconds if applicable.
    statsd_interval: Any = None
    # Metric type such as `gauge` or `rate`.
    type: Any = None
    # Primary unit of the metric such as `byte` or `operation`.
    unit: Any = None
    # path parameter, not part of the API's own resource representation
    metric_name: Any = None

@dataclasses.dataclass
class MetadataAttrs:
    # Metric description.
    description: Any = None
    # Name of the integration that sent the metric if applicable.
    integration: Any = None
    # Per unit of the metric such as `second` in `bytes per second`.
    per_unit: Any = None
    # A more human-readable and abbreviated version of the metric name.
    short_name: Any = None
    # StatsD flush interval of the metric in seconds if applicable.
    statsd_interval: Any = None
    # Metric type such as `gauge` or `rate`.
    type: Any = None
    # Primary unit of the metric such as `byte` or `operation`.
    unit: Any = None
    # path parameter, not part of the API's own resource representation
    metric_name: Any = None

Metadata = ubx.ResourceBinding(
    wire_type="datadog_metric_metadata",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "integration": ubx.FieldSpec(wire_name="integration"),
        "per_unit": ubx.FieldSpec(wire_name="per_unit"),
        "short_name": ubx.FieldSpec(wire_name="short_name"),
        "statsd_interval": ubx.FieldSpec(wire_name="statsd_interval"),
        "type": ubx.FieldSpec(wire_name="type"),
        "unit": ubx.FieldSpec(wire_name="unit"),
        "metric_name": ubx.FieldSpec(wire_name="metric_name"),
    },
)
