// Code generated by `ubx sdk gen` from datadog_incident_notification_template_array. DO NOT EDIT.
package incident

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type NotificationTemplateArray_Data_Attributes struct {
	Category any
	Content  any
	Created  any
	Modified any
	Name     any
	Subject  any
}

type NotificationTemplateArray_Data_Relationships_CreatedByUser_Data struct {
	Id   any
	Type any
}

type NotificationTemplateArray_Data_Relationships_CreatedByUser struct {
	Data any
}

type NotificationTemplateArray_Data_Relationships struct {
	CreatedByUser      any
	IncidentType       any
	LastModifiedByUser any
}

type NotificationTemplateArray_Data struct {
	Attributes    any
	Id            any
	Relationships any
	Type          any
}

type NotificationTemplateArray_Included_Attributes struct {
	CreatedAt      any
	Disabled       any
	Email          any
	Handle         any
	Icon           any
	LastLoginTime  any
	MfaEnabled     any
	ModifiedAt     any
	Name           any
	ServiceAccount any
	Status         any
	Title          any
	Uuid           any
	Verified       any
}

type NotificationTemplateArray_Included_Relationships_OtherOrgs struct {
	Data any
}

type NotificationTemplateArray_Included_Relationships struct {
	Org        any
	OtherOrgs  any
	OtherUsers any
	Roles      any
}

type NotificationTemplateArray_Included struct {
	Attributes    any
	Id            any
	Relationships any
	Type          any
}

type NotificationTemplateArray_Meta_Page struct {
	// Total number of notification templates.
	TotalCount any
	// Total number of notification templates matching the filter.
	TotalFilteredCount any
}

type NotificationTemplateArray_Meta struct {
	// Pagination metadata.
	Page any
}

type NotificationTemplateArrayConfig struct {
	Include any
}

type NotificationTemplateArrayAttrs struct {
	// The `NotificationTemplateArray` `data`.
	Data    any
	Include any
	// Related objects that are included in the response.
	Included any
	// Response metadata.
	Meta any
}

var NotificationTemplateArray = ubx.DataSourceBinding{
	WireType: "datadog_incident_notification_template_array",
	Fields: ubx.FieldMap{
		"Include": ubx.FieldSpec{WireName: "include"},
	},
}
