// Code generated by `ubx sdk gen` from datadog_statuspage_url_settings_response. DO NOT EDIT.
package statuspage

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type UrlSettingsResponse_Data_Attributes struct {
	CustomTags any
	Url any
}

type UrlSettingsResponse_Data struct {
	Attributes any
	Id any
	Type any
}

type UrlSettingsResponseConfig struct {
}

type UrlSettingsResponseAttrs struct {
	// An array of Statuspage URL settings.
	Data any
}

var UrlSettingsResponse = ubx.DataSourceBinding{
	WireType: "datadog_statuspage_url_settings_response",
	Fields: ubx.FieldMap{
	},
}
