// Code generated by `ubx sdk gen` from datadog_google_chat_organization_handle_response_data_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ChatOrganizationHandleResponseDataList_Data_Attributes {
  name?: string | Computed<string>;
  spaceDisplayName?: string | Computed<string>;
  spaceResourceName?: string | Computed<string>;
}

export interface ChatOrganizationHandleResponseDataList_Data {
  attributes?: ChatOrganizationHandleResponseDataList_Data_Attributes | Computed<ChatOrganizationHandleResponseDataList_Data_Attributes>;
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ChatOrganizationHandleResponseDataListConfig {
  organizationBindingId: string | Computed<string>;
}

export interface ChatOrganizationHandleResponseDataListAttrs {
  /** An array of organization handles. */
  data: ChatOrganizationHandleResponseDataList_Data[];
  organizationBindingId: string;
}

export const ChatOrganizationHandleResponseDataList: DataSourceBinding<ChatOrganizationHandleResponseDataListConfig, ChatOrganizationHandleResponseDataListAttrs> = {
  wireType: "datadog_google_chat_organization_handle_response_data_list",
  fields: {
    organizationBindingId: "organization_binding_id",
  },
};
