// Code generated by `ubx sdk gen` from datadog_fleet_schedule_v2_response. DO NOT EDIT.
package fleet

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ScheduleV2Response_Data_Attributes_NotificationRule struct {
	// Notification handles (for example, Slack channels or PagerDuty integrations).
	Handles any
	// Tags associated with the notification rule.
	Tags any
}

type ScheduleV2Response_Data_Attributes_Rule struct {
	// Days of the week when the schedule triggers. Valid values are "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun".
	DaysOfWeek any
	// Interval between schedule runs in weeks. 1 means the schedule runs every week on the specified days. Higher values repeat every N weeks.
	Interval any
	// Duration of the maintenance window in minutes.
	MaintenanceWindowDuration any
	// Start time of the maintenance window in 24-hour clock format (HHMM). Deployments are triggered at this time on the specified days.
	StartMaintenanceWindow any
	// Timezone in IANA Time Zone Database format.
	Timezone any
}

type ScheduleV2Response_Data_Attributes struct {
	// RFC3339 timestamp when the schedule was created.
	CreatedAt any
	// User handle of the person who created the schedule.
	CreatedBy any
	// Whether this is the default schedule for the organization.
	IsDefault any
	// Human-readable name for the schedule.
	Name any
	// RFC3339 timestamp of the next scheduled maintenance window start time. Absent when the next run time cannot be computed.
	NextRun any
	// Notification configuration attached to a schedule. Included when available. If the notification rule cannot be retrieved, this field is omitted and the schedule is still returned. If the notification rule is retrieved but its handles cannot be resolved, it is still included with an empty `handles` array.
	NotificationRule any
	// Query used to filter and select target hosts for scheduled deployments.
	Query any
	// Defines the recurrence pattern for the schedule.
	Rule any
	// The status of the schedule. - `active`: The schedule is active and will create deployments according to its recurrence rule. - `inactive`: The schedule is inactive and will not create any deployments.
	Status any
	// RFC3339 timestamp when the schedule was last updated.
	UpdatedAt any
	// User handle of the person who last updated the schedule.
	UpdatedBy any
	// Number of major versions behind the latest to target for upgrades. - 0: Always upgrade to the latest version. - 1: Upgrade to latest minus 1 major version. - 2: Upgrade to latest minus 2 major versions.
	VersionToLatest any
}

type ScheduleV2Response_Data struct {
	// Attributes of a fleet schedule in the v2 API response.
	Attributes any
	// Unique identifier for the schedule.
	Id any
	// The type of schedule resource.
	Type any
}

type ScheduleV2ResponseConfig struct {
	Id any
}

type ScheduleV2ResponseAttrs struct {
	// A fleet upgrade schedule resource in the v2 API response.
	Data any
	Id   any
}

var ScheduleV2Response = ubx.DataSourceBinding{
	WireType: "datadog_fleet_schedule_v2_response",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
	},
}
