// Code generated by `ubx sdk gen` from datadog_deployment_gate_response. DO NOT EDIT.
package deployment

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GateResponse_Data_Attributes struct {
	// Whether this gate is run in dry-run mode.
	DryRun any
	// The environment of the deployment gate.
	Env any
	// The identifier of the deployment gate.
	Identifier any
	// The service of the deployment gate.
	Service any
}

type GateResponse_Data struct {
	// Parameters for creating a deployment gate.
	Attributes any
	// Deployment gate resource type.
	Type any
}

var GateResponse_Data_AttributesFields = ubx.FieldMap{
		"DryRun": ubx.FieldSpec{WireName: "dry_run"},
		"Env": ubx.FieldSpec{WireName: "env"},
		"Identifier": ubx.FieldSpec{WireName: "identifier"},
		"Service": ubx.FieldSpec{WireName: "service"},
	}

var GateResponse_DataFields = ubx.FieldMap{
		"Attributes": ubx.FieldSpec{
			WireName: "attributes",
			Kind: "object",
			Fields: GateResponse_Data_AttributesFields,
		},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

type GateResponseConfig struct {
	// Parameters for creating a deployment gate.
	Data any
	// path parameter, not part of the API's own resource representation
	Id any
}

type GateResponseAttrs struct {
	// Parameters for creating a deployment gate.
	Data any
	// path parameter, not part of the API's own resource representation
	Id any
}

var GateResponse = ubx.ResourceBinding{
	WireType: "datadog_deployment_gate_response",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind: "object",
			Fields: GateResponse_DataFields,
		},
		"Id": ubx.FieldSpec{WireName: "id"},
	},
}
