// Code generated by `ubx sdk gen` from datadog_get_investigation_response. DO NOT EDIT.
package get

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type InvestigationResponse_Data_Attributes_Conclusions struct {
	Description any
	Summary     any
	Title       any
}

type InvestigationResponse_Data_Attributes_Trigger_MonitorAlertTrigger struct {
	// The event ID associated with the monitor alert.
	EventId any
	// The timestamp of the event in Unix milliseconds.
	EventTs any
	// The monitor ID that triggered the alert.
	MonitorId any
}

type InvestigationResponse_Data_Attributes_Trigger struct {
	// Attributes for a monitor alert trigger.
	MonitorAlertTrigger any
	// The type of trigger for the investigation.
	Type any
}

type InvestigationResponse_Data_Attributes struct {
	// The conclusions drawn from the investigation.
	Conclusions any
	// The current status of the investigation.
	Status any
	// The title of the investigation.
	Title any
	// The trigger definition for starting an investigation.
	Trigger any
}

type InvestigationResponse_Data struct {
	// Attributes for the trigger investigation request.
	Attributes any
	// The unique identifier of the investigation.
	Id any
	// The resource type for trigger investigation requests.
	Type any
}

type InvestigationResponse_Links struct {
	// The URL to the investigation in the Datadog app.
	Self any
}

var InvestigationResponse_Data_Attributes_ConclusionsFields = ubx.FieldMap{
	"Description": ubx.FieldSpec{WireName: "description"},
	"Summary":     ubx.FieldSpec{WireName: "summary"},
	"Title":       ubx.FieldSpec{WireName: "title"},
}

var InvestigationResponse_Data_Attributes_Trigger_MonitorAlertTriggerFields = ubx.FieldMap{
	"EventId":   ubx.FieldSpec{WireName: "event_id"},
	"EventTs":   ubx.FieldSpec{WireName: "event_ts"},
	"MonitorId": ubx.FieldSpec{WireName: "monitor_id"},
}

var InvestigationResponse_Data_Attributes_TriggerFields = ubx.FieldMap{
	"MonitorAlertTrigger": ubx.FieldSpec{
		WireName: "monitor_alert_trigger",
		Kind:     "object",
		Fields:   InvestigationResponse_Data_Attributes_Trigger_MonitorAlertTriggerFields,
	},
	"Type": ubx.FieldSpec{WireName: "type"},
}

var InvestigationResponse_Data_AttributesFields = ubx.FieldMap{
	"Conclusions": ubx.FieldSpec{
		WireName: "conclusions",
		Kind:     "list",
		Fields:   InvestigationResponse_Data_Attributes_ConclusionsFields,
	},
	"Status": ubx.FieldSpec{WireName: "status"},
	"Title":  ubx.FieldSpec{WireName: "title"},
	"Trigger": ubx.FieldSpec{
		WireName: "trigger",
		Kind:     "object",
		Fields:   InvestigationResponse_Data_Attributes_TriggerFields,
	},
}

var InvestigationResponse_DataFields = ubx.FieldMap{
	"Attributes": ubx.FieldSpec{
		WireName: "attributes",
		Kind:     "object",
		Fields:   InvestigationResponse_Data_AttributesFields,
	},
	"Id":   ubx.FieldSpec{WireName: "id"},
	"Type": ubx.FieldSpec{WireName: "type"},
}

type InvestigationResponseConfig struct {
	// Data for the trigger investigation request.
	Data any
	// path parameter, not part of the API's own resource representation
	Id any
}

type InvestigationResponseAttrs struct {
	// Data for the trigger investigation request.
	Data any
	// Links related to the investigation.
	Links any
	// path parameter, not part of the API's own resource representation
	Id any
}

var InvestigationResponse = ubx.ResourceBinding{
	WireType: "datadog_get_investigation_response",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind:     "object",
			Fields:   InvestigationResponse_DataFields,
		},
		"Id": ubx.FieldSpec{WireName: "id"},
	},
}
