# Code generated by `ubx sdk gen` from datadog_dashboard_list_item_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ListItemList_Dashboards_Author:
    email: Any = None
    handle: Any = None
    name: Any = None

@dataclasses.dataclass
class ListItemList_Dashboards:
    author: Any = None
    created: Any = None
    icon: Any = None
    id: Any = None
    integration_id: Any = None
    is_favorite: Any = None
    is_read_only: Any = None
    is_shared: Any = None
    modified: Any = None
    popularity: Any = None
    tags: Any = None
    title: Any = None
    type: Any = None
    url: Any = None

@dataclasses.dataclass
class ListItemListConfig:
    dashboard_list_id: Any = None

@dataclasses.dataclass
class ListItemListAttrs:
    dashboard_list_id: Any = None
    # List of dashboards in the dashboard list.
    dashboards: Any = None
    # Number of dashboards in the dashboard list.
    total: Any = None

ListItemList = ubx.DataSourceBinding(
    wire_type="datadog_dashboard_list_item_list",
    fields={
        "dashboard_list_id": ubx.FieldSpec(wire_name="dashboard_list_id"),
    },
)
