// Code generated by `ubx sdk gen` from datadog_app_key_registration_data_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface KeyRegistrationDataList_Data {
  id?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface KeyRegistrationDataList_Meta {
  /** The total number of app key registrations. */
  total?: number | Computed<number>;
  /** The total number of app key registrations that match the specified filters. */
  totalFiltered?: number | Computed<number>;
}

export interface KeyRegistrationDataListConfig {
}

export interface KeyRegistrationDataListAttrs {
  /** An array of app key registrations. */
  data: KeyRegistrationDataList_Data[];
  /** The definition of `ListAppKeyRegistrationsResponseMeta` object. */
  meta: KeyRegistrationDataList_Meta;
}

export const KeyRegistrationDataList: DataSourceBinding<KeyRegistrationDataListConfig, KeyRegistrationDataListAttrs> = {
  wireType: "datadog_app_key_registration_data_list",
  fields: {
  },
};
