# Code generated by `ubx sdk gen` from datadog_list_apis_response_data_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApisResponseDataList_Data_Attributes:
    name: Any = None

@dataclasses.dataclass
class ApisResponseDataList_Data:
    attributes: Any = None
    id: Any = None

@dataclasses.dataclass
class ApisResponseDataList_Meta_Pagination:
    # Number of items in the current page.
    limit: Any = None
    # Offset for pagination.
    offset: Any = None
    # Total number of items.
    total_count: Any = None

@dataclasses.dataclass
class ApisResponseDataList_Meta:
    # Pagination metadata information for `ListAPIsResponse`.
    pagination: Any = None

@dataclasses.dataclass
class ApisResponseDataListConfig:
    query: Any = None

@dataclasses.dataclass
class ApisResponseDataListAttrs:
    # List of API items.
    data: Any = None
    # Metadata for `ListAPIsResponse`.
    meta: Any = None
    query: Any = None

ApisResponseDataList = ubx.DataSourceBinding(
    wire_type="datadog_list_apis_response_data_list",
    fields={
        "query": ubx.FieldSpec(wire_name="query"),
    },
)
