# Code generated by `ubx sdk gen` from datadog_list_blueprints_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class BlueprintsResponse_Data_Attributes:
    created_at: Any = None
    description: Any = None
    name: Any = None
    slug: Any = None
    tags: Any = None
    tile_background: Any = None
    tile_icon_action_fqn: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class BlueprintsResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class BlueprintsResponseConfig:
    limit: Any = None
    page: Any = None

@dataclasses.dataclass
class BlueprintsResponseAttrs:
    # An array of blueprint metadata.
    data: Any = None
    limit: Any = None
    page: Any = None

BlueprintsResponse = ubx.DataSourceBinding(
    wire_type="datadog_list_blueprints_response",
    fields={
        "limit": ubx.FieldSpec(wire_name="limit"),
        "page": ubx.FieldSpec(wire_name="page"),
    },
)
