# Code generated by `ubx sdk gen` from datadog_list_dashboards_usage_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DashboardsUsageResponse_Data_Attributes_Author:
    handle: Any = None
    id: Any = None
    is_disabled: Any = None
    name: Any = None

@dataclasses.dataclass
class DashboardsUsageResponse_Data_Attributes:
    author: Any = None
    created_at: Any = None
    dashboard_quality_score: Any = None
    edited_at: Any = None
    org_id: Any = None
    teams: Any = None
    title: Any = None
    total_views: Any = None
    total_views_by_type: Any = None
    viewed_at: Any = None
    viewer: Any = None
    widget_count: Any = None
    widget_count_by_type: Any = None

@dataclasses.dataclass
class DashboardsUsageResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class DashboardsUsageResponse_Links:
    # Link to the first page.
    first: Any = None
    # Link to the last page, or `null` if the total is unknown.
    last: Any = None
    # Link to the next page. Absent when there is no next page.
    next: Any = None
    # Link to the previous page. Absent when there is no previous page.
    prev: Any = None
    # Link to the current page.
    self: Any = None

@dataclasses.dataclass
class DashboardsUsageResponse_Meta_Page:
    # Integer representing the offset to fetch the first page of results.
    first_offset: Any = None
    # Integer representing the offset to fetch the last page of results.
    last_offset: Any = None
    # Integer representing the number of elements to be returned in the results.
    limit: Any = None
    # Integer representing the index of the first element in the next page of results. Equal to page size added to the current offset.
    next_offset: Any = None
    # Integer representing the index of the first element in the results.
    offset: Any = None
    # Integer representing the index of the first element in the previous page of results.
    prev_offset: Any = None
    # Integer representing the total number of elements available.
    total: Any = None
    # The pagination type used for offset-based pagination.
    type: Any = None

@dataclasses.dataclass
class DashboardsUsageResponse_Meta:
    # Offset-based pagination schema.
    page: Any = None

@dataclasses.dataclass
class DashboardsUsageResponseConfig:
    pass

@dataclasses.dataclass
class DashboardsUsageResponseAttrs:
    # Dashboard usage records, one per dashboard in the caller's organization.
    data: Any = None
    # Pagination links for a list of dashboard usage records.
    links: Any = None
    # Pagination metadata for a list of dashboard usage records.
    meta: Any = None

DashboardsUsageResponse = ubx.DataSourceBinding(
    wire_type="datadog_list_dashboards_usage_response",
    fields={
    },
)
