// Code generated by `ubx sdk gen` from datadog_container_item_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ItemList_Data_Attributes {
  containerId?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  host?: string | Computed<string>;
  imageDigest?: string | Computed<string>;
  imageName?: string | Computed<string>;
  imageTags?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  startedAt?: string | Computed<string>;
  state?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
}

export interface ItemList_Data_Relationships_Containers_Links {
  related?: string | Computed<string>;
}

export interface ItemList_Data_Relationships_Containers {
  data?: string[] | Computed<string[]>;
  links?: ItemList_Data_Relationships_Containers_Links | Computed<ItemList_Data_Relationships_Containers_Links>;
}

export interface ItemList_Data_Relationships {
  containers?: ItemList_Data_Relationships_Containers | Computed<ItemList_Data_Relationships_Containers>;
}

export interface ItemList_Data {
  attributes?: ItemList_Data_Attributes | Computed<ItemList_Data_Attributes>;
  id?: string | Computed<string>;
  relationships?: ItemList_Data_Relationships | Computed<ItemList_Data_Relationships>;
  type?: string | Computed<string>;
}

export interface ItemList_Links {
  /** Link to the first page. */
  first?: string | Computed<string>;
  /** Link to the last page. */
  last?: string | Computed<string>;
  /** Link to the next page. */
  next?: string | Computed<string>;
  /** Link to previous page. */
  prev?: string | Computed<string>;
  /** Link to current page. */
  self?: string | Computed<string>;
}

export interface ItemList_Meta_Pagination {
  /** The cursor used to get the current results, if any. */
  cursor?: string | Computed<string>;
  /** Number of results returned */
  limit?: number | Computed<number>;
  /** The cursor used to get the next results, if any. */
  nextCursor?: string | Computed<string>;
  /** The cursor used to get the previous results, if any. */
  prevCursor?: string | Computed<string>;
  /** Total number of records that match the query. */
  total?: number | Computed<number>;
  /** Type of Container pagination. */
  type?: string | Computed<string>;
}

export interface ItemList_Meta {
  /** Paging attributes. */
  pagination?: ItemList_Meta_Pagination | Computed<ItemList_Meta_Pagination>;
}

export interface ItemListConfig {
  groupBy?: string | Computed<string>;
  sort?: string | Computed<string>;
}

export interface ItemListAttrs {
  /** Array of Container objects. */
  data: ItemList_Data[];
  groupBy: string;
  /** Pagination links. */
  links: ItemList_Links;
  /** Response metadata object. */
  meta: ItemList_Meta;
  sort: string;
}

export const ItemList: DataSourceBinding<ItemListConfig, ItemListAttrs> = {
  wireType: "datadog_container_item_list",
  fields: {
    groupBy: "group_by",
    sort: "sort",
  },
};
