// Code generated by `ubx sdk gen` from datadog_degradation_template. DO NOT EDIT.
package degradation

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Template_Data_Attributes_ComponentsAffected struct {
	Id any
	Name any
	Status any
}

type Template_Data_Attributes_Updates struct {
	Message any
	Status any
}

type Template_Data_Attributes struct {
	// The components affected by a degradation created from this template.
	ComponentsAffected any
	// The title used for a degradation created from this template.
	DegradationTitle any
	// The name of the degradation template.
	Name any
	// The pre-filled updates for a degradation created from this template.
	Updates any
}

type Template_Data struct {
	// The attributes for creating a degradation template.
	Attributes any
	// Degradation templates resource type.
	Type any
}

type Template_Included_Attributes struct {
	Email any
	Handle any
	Icon any
	Name any
	Uuid any
}

type Template_Included_Relationships_CreatedByUser_Data struct {
	Id any
	Type any
}

type Template_Included_Relationships_CreatedByUser struct {
	Data any
}

type Template_Included_Relationships struct {
	CreatedByUser any
	LastModifiedByUser any
}

type Template_Included struct {
	Attributes any
	Id any
	Relationships any
	Type any
}

var Template_Data_Attributes_ComponentsAffectedFields = ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Status": ubx.FieldSpec{WireName: "status"},
	}

var Template_Data_Attributes_UpdatesFields = ubx.FieldMap{
		"Message": ubx.FieldSpec{WireName: "message"},
		"Status": ubx.FieldSpec{WireName: "status"},
	}

var Template_Data_AttributesFields = ubx.FieldMap{
		"ComponentsAffected": ubx.FieldSpec{
			WireName: "components_affected",
			Kind: "list",
			Fields: Template_Data_Attributes_ComponentsAffectedFields,
		},
		"DegradationTitle": ubx.FieldSpec{WireName: "degradation_title"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Updates": ubx.FieldSpec{
			WireName: "updates",
			Kind: "list",
			Fields: Template_Data_Attributes_UpdatesFields,
		},
	}

var Template_DataFields = ubx.FieldMap{
		"Attributes": ubx.FieldSpec{
			WireName: "attributes",
			Kind: "object",
			Fields: Template_Data_AttributesFields,
		},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

type TemplateConfig struct {
	// The data object for creating a degradation template.
	Data any
	// path parameter, not part of the API's own resource representation
	PageId any
	// path parameter, not part of the API's own resource representation
	TemplateId any
}

type TemplateAttrs struct {
	// The data object for creating a degradation template.
	Data any
	// The included related resources of a degradation template. Client must explicitly request these resources by name in the `include` query parameter.
	Included any
	// path parameter, not part of the API's own resource representation
	PageId any
	// path parameter, not part of the API's own resource representation
	TemplateId any
}

var Template = ubx.ResourceBinding{
	WireType: "datadog_degradation_template",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind: "object",
			Fields: Template_DataFields,
		},
		"PageId": ubx.FieldSpec{WireName: "page_id"},
		"TemplateId": ubx.FieldSpec{WireName: "template_id"},
	},
}
