# Code generated by `ubx sdk gen` from datadog_service_now_user_data_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class NowUserDataList_Data_Attributes:
    email: Any = None
    full_name: Any = None
    instance_id: Any = None
    user_name: Any = None
    user_sys_id: Any = None

@dataclasses.dataclass
class NowUserDataList_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class NowUserDataListConfig:
    instance_id: Any = None

@dataclasses.dataclass
class NowUserDataListAttrs:
    # Array of ServiceNow user data objects
    data: Any = None
    instance_id: Any = None

NowUserDataList = ubx.DataSourceBinding(
    wire_type="datadog_service_now_user_data_list",
    fields={
        "instance_id": ubx.FieldSpec(wire_name="instance_id"),
    },
)
