# Code generated by `ubx sdk gen` from datadog_ciapp_git_hub_accounts_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GitHubAccountsResponse_Data_Attributes_Repositories:
    enabled: Any = None
    name: Any = None

@dataclasses.dataclass
class GitHubAccountsResponse_Data_Attributes:
    account: Any = None
    enabled: Any = None
    host: Any = None
    repo_count: Any = None
    repositories: Any = None

@dataclasses.dataclass
class GitHubAccountsResponse_Data:
    attributes: Any = None
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class GitHubAccountsResponseConfig:
    pass

@dataclasses.dataclass
class GitHubAccountsResponseAttrs:
    data: Any = None

GitHubAccountsResponse = ubx.DataSourceBinding(
    wire_type="datadog_ciapp_git_hub_accounts_response",
    fields={
    },
)
