# Code generated by `ubx sdk gen` from datadog_google_chat_organizations_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ChatOrganizationsResponse_Data_Attributes:
    domain_id: Any = None
    domain_name: Any = None

@dataclasses.dataclass
class ChatOrganizationsResponse_Data_Relationships_DelegatedUser_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class ChatOrganizationsResponse_Data_Relationships_DelegatedUser:
    data: Any = None

@dataclasses.dataclass
class ChatOrganizationsResponse_Data_Relationships:
    delegated_user: Any = None

@dataclasses.dataclass
class ChatOrganizationsResponse_Data:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class ChatOrganizationsResponseConfig:
    pass

@dataclasses.dataclass
class ChatOrganizationsResponseAttrs:
    # An array of Google Chat organization bindings.
    data: Any = None

ChatOrganizationsResponse = ubx.DataSourceBinding(
    wire_type="datadog_google_chat_organizations_response",
    fields={
    },
)
