// Code generated by `ubx sdk gen` from datadog_sample_log_generation_subscription_data_list. DO NOT EDIT.
package sample

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type LogGenerationSubscriptionDataList_Data_Attributes struct {
	ContentPackId any
	CreatedAt any
	ExpiresAt any
	IsActive any
	Status any
}

type LogGenerationSubscriptionDataList_Data struct {
	Attributes any
	Id any
	Type any
}

type LogGenerationSubscriptionDataList_Meta struct {
	// The total number of subscriptions matching the request, irrespective of pagination.
	TotalSubscriptions any
}

type LogGenerationSubscriptionDataListConfig struct {
	EndTimestamp any
	StartTimestamp any
	// Filter that controls whether to return only active subscriptions or every subscription on record.
	Status any
}

type LogGenerationSubscriptionDataListAttrs struct {
	// The list of sample log generation subscriptions.
	Data any
	EndTimestamp any
	// Metadata returned alongside a list of sample log generation subscriptions.
	Meta any
	StartTimestamp any
	// Filter that controls whether to return only active subscriptions or every subscription on record.
	Status any
}

var LogGenerationSubscriptionDataList = ubx.DataSourceBinding{
	WireType: "datadog_sample_log_generation_subscription_data_list",
	Fields: ubx.FieldMap{
		"EndTimestamp": ubx.FieldSpec{WireName: "end_timestamp"},
		"StartTimestamp": ubx.FieldSpec{WireName: "start_timestamp"},
		"Status": ubx.FieldSpec{WireName: "status"},
	},
}
