// Code generated by `ubx sdk gen` from datadog_elastic_cloud_integration_account_response_data_list. DO NOT EDIT.
package elastic

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudIntegrationAccountResponseDataList_Data_Attributes_Authentication struct {
	AuthType any
	Username any
}

type CloudIntegrationAccountResponseDataList_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats_Status struct {
	Health    any
	Message   any
	UpdatedAt any
}

type CloudIntegrationAccountResponseDataList_Data_Attributes_Dataflows_ElasticCloudDetailedIndexStats struct {
	Enabled any
	Status  any
}

type CloudIntegrationAccountResponseDataList_Data_Attributes_Dataflows struct {
	ElasticCloudDetailedIndexStats          any
	ElasticCloudIndexStats                  any
	ElasticCloudMetrics                     any
	ElasticCloudPendingTaskStats            any
	ElasticCloudPrimaryShardGracefulTimeout any
	ElasticCloudPrimaryShardStats           any
	ElasticCloudShardAllocationStats        any
	ElasticCloudSlmStats                    any
}

type CloudIntegrationAccountResponseDataList_Data_Attributes_Settings struct {
	Tags any
	Url  any
}

type CloudIntegrationAccountResponseDataList_Data_Attributes struct {
	Authentication any
	Dataflows      any
	Name           any
	Settings       any
}

type CloudIntegrationAccountResponseDataList_Data struct {
	Attributes any
	Id         any
	Type       any
}

type CloudIntegrationAccountResponseDataListConfig struct {
}

type CloudIntegrationAccountResponseDataListAttrs struct {
	// List of Elastic Cloud integration accounts.
	Data any
}

var CloudIntegrationAccountResponseDataList = ubx.DataSourceBinding{
	WireType: "datadog_elastic_cloud_integration_account_response_data_list",
	Fields:   ubx.FieldMap{},
}
