// Code generated by `ubx sdk gen` from datadog_security_entity_risk_score. DO NOT EDIT.
package security

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type EntityRiskScore_Data_Attributes_ConfigRisks struct {
	HasIdentityRisk      any
	HasMisconfiguration  any
	HasPrivilegedRole    any
	IsPrivileged         any
	IsProduction         any
	IsPubliclyAccessible any
}

type EntityRiskScore_Data_Attributes_EntityMetadata struct {
	AccountId       any
	Environments    any
	MitreTactics    any
	MitreTechniques any
	ProjectId       any
	Services        any
	Sources         any
	SubscriptionId  any
}

type EntityRiskScore_Data_Attributes struct {
	AccountIds         any
	ConfigRisks        any
	EntityMetadata     any
	EntityName         any
	EntityProviders    any
	EntityRoles        any
	EntitySubTypes     any
	EntityType         any
	EntityTypes        any
	FirstDetected      any
	LastActivityTitle  any
	LastDetected       any
	RiskScore          any
	RiskScoreEvolution any
	Severity           any
	SignalsDetected    any
}

type EntityRiskScore_Data struct {
	Attributes any
	Id         any
	Type       any
}

type EntityRiskScore_Meta struct {
	// Current page number (1-indexed)
	PageNumber any
	// Number of items per page
	PageSize any
	// Query ID for pagination consistency
	QueryId any
	// Total number of entities matching the query
	TotalRowCount any
}

type EntityRiskScoreConfig struct {
	EntityType any
	From       any
	To         any
}

type EntityRiskScoreAttrs struct {
	// Array of entity risk score objects.
	Data       any
	EntityType any
	From       any
	// Metadata for pagination
	Meta any
	To   any
}

var EntityRiskScore = ubx.DataSourceBinding{
	WireType: "datadog_security_entity_risk_score",
	Fields: ubx.FieldMap{
		"EntityType": ubx.FieldSpec{WireName: "entity_type"},
		"From":       ubx.FieldSpec{WireName: "from"},
		"To":         ubx.FieldSpec{WireName: "to"},
	},
}
