// Code generated by `ubx sdk gen` from datadog_security_filter. DO NOT EDIT.
package security

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Filter_Data_Attributes_ExclusionFilters struct {
	Name  any
	Query any
}

type Filter_Data_Attributes struct {
	ExclusionFilters any
	FilteredDataType any
	IsBuiltin        any
	IsEnabled        any
	Name             any
	Query            any
	Version          any
}

type Filter_Data struct {
	Attributes any
	Id         any
	Type       any
}

type Filter_Meta struct {
	// A warning message.
	Warning any
}

type FilterConfig struct {
}

type FilterAttrs struct {
	// A list of security filters objects.
	Data any
	// Optional metadata associated to the response.
	Meta any
}

var Filter = ubx.DataSourceBinding{
	WireType: "datadog_security_filter",
	Fields:   ubx.FieldMap{},
}
