// Code generated by `ubx sdk gen` from datadog_security_monitoring_integration_config_data. DO NOT EDIT.
package security

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MonitoringIntegrationConfigData_Data_Attributes struct {
	CreatedAt any
	Domain any
	Enabled any
	IntegrationType any
	ModifiedAt any
	Name any
	Settings any
	State any
}

type MonitoringIntegrationConfigData_Data struct {
	Attributes any
	Id any
	Type any
}

type MonitoringIntegrationConfigDataConfig struct {
}

type MonitoringIntegrationConfigDataAttrs struct {
	// The list of integration configurations.
	Data any
}

var MonitoringIntegrationConfigData = ubx.DataSourceBinding{
	WireType: "datadog_security_monitoring_integration_config_data",
	Fields: ubx.FieldMap{
	},
}
