// Code generated by `ubx sdk gen` from datadog_synthetics_api_multistep_parent_test_data_list. DO NOT EDIT.
package synthetics

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ApiMultistepParentTestDataList_Data_Attributes struct {
	ChildName            any
	ChildPublicId        any
	MonitorId            any
	Name                 any
	OverallState         any
	OverallStateModified any
	PublicId             any
}

type ApiMultistepParentTestDataList_Data struct {
	Attributes any
	Id         any
	Type       any
}

type ApiMultistepParentTestDataListConfig struct {
	PublicId any
}

type ApiMultistepParentTestDataListAttrs struct {
	// List of parent tests that include this subtest.
	Data     any
	PublicId any
}

var ApiMultistepParentTestDataList = ubx.DataSourceBinding{
	WireType: "datadog_synthetics_api_multistep_parent_test_data_list",
	Fields: ubx.FieldMap{
		"PublicId": ubx.FieldSpec{WireName: "public_id"},
	},
}
