// Code generated by `ubx sdk gen` from datadog_synthetics_list_global_variables_response. DO NOT EDIT.
package synthetics

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ListGlobalVariablesResponse_Variables_Attributes struct {
	RestrictedRoles any
}

type ListGlobalVariablesResponse_Variables_ParseTestOptions_Parser struct {
	Type any
	Value any
}

type ListGlobalVariablesResponse_Variables_ParseTestOptions struct {
	Field any
	LocalVariableName any
	Parser any
	Type any
}

type ListGlobalVariablesResponse_Variables_Value_Options_TotpParameters struct {
	Digits any
	RefreshInterval any
}

type ListGlobalVariablesResponse_Variables_Value_Options struct {
	TotpParameters any
}

type ListGlobalVariablesResponse_Variables_Value struct {
	Options any
	Secure any
	Value any
}

type ListGlobalVariablesResponse_Variables struct {
	Attributes any
	Description any
	Id any
	IsFido any
	IsTotp any
	Name any
	ParseTestOptions any
	ParseTestPublicId any
	Tags any
	Value any
}

type ListGlobalVariablesResponseConfig struct {
}

type ListGlobalVariablesResponseAttrs struct {
	// Array of Synthetic global variables.
	Variables any
}

var ListGlobalVariablesResponse = ubx.DataSourceBinding{
	WireType: "datadog_synthetics_list_global_variables_response",
	Fields: ubx.FieldMap{
	},
}
