// Code generated by `ubx sdk gen` from datadog_synthetics_list_tests_response. DO NOT EDIT.
package synthetics

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ListTestsResponse_Tests_Config_Assertions struct {
	Code any
	Operator any
	Property any
	Target any
	TimingsScope any
	Type any
}

type ListTestsResponse_Tests_Config_ConfigVariables struct {
	Example any
	Id any
	Name any
	Pattern any
	Secure any
	Type any
}

type ListTestsResponse_Tests_Config_Request_BasicAuth_AddClaims struct {
	Exp any
	Iat any
}

type ListTestsResponse_Tests_Config_Request_BasicAuth struct {
	AccessKey any
	AccessTokenUrl any
	AddClaims any
	Algorithm any
	Audience any
	ClientId any
	ClientSecret any
	Domain any
	ExpiresIn any
	Header any
	Password any
	Payload any
	Region any
	Resource any
	Scope any
	Secret any
	SecretKey any
	ServiceName any
	SessionToken any
	TokenApiAuthentication any
	TokenPrefix any
	Type any
	Username any
	Workstation any
}

type ListTestsResponse_Tests_Config_Request_Certificate_Cert struct {
	Content any
	Filename any
	UpdatedAt any
}

type ListTestsResponse_Tests_Config_Request_Certificate struct {
	Cert any
	Key any
}

type ListTestsResponse_Tests_Config_Request_Files struct {
	BucketKey any
	Content any
	Encoding any
	Name any
	OriginalFileName any
	Size any
	Type any
}

type ListTestsResponse_Tests_Config_Request_Proxy struct {
	Headers any
	Url any
}

type ListTestsResponse_Tests_Config_Request struct {
	AllowInsecure any
	BasicAuth any
	Body any
	BodyType any
	CallType any
	Certificate any
	CertificateDomains any
	CheckCertificateRevocation any
	CompressedJsonDescriptor any
	CompressedProtoFile any
	DisableAiaIntermediateFetching any
	DnsServer any
	DnsServerPort any
	Files any
	FollowRedirects any
	Form any
	Headers any
	Host any
	HttpVersion any
	IgnoreCertificateValidation any
	IsMessageBase64Encoded any
	McpProtocolVersion any
	Message any
	Metadata any
	Method any
	NoSavingResponseBody any
	NumberOfPackets any
	PersistCookies any
	Port any
	Proxy any
	Query any
	Servername any
	Service any
	ShouldTrackHops any
	Timeout any
	ToolArgs any
	ToolName any
	Url any
}

type ListTestsResponse_Tests_Config struct {
	Assertions any
	ConfigVariables any
	Request any
	Variables any
}

type ListTestsResponse_Tests_Creator struct {
	Email any
	Handle any
	Name any
}

type ListTestsResponse_Tests_Options_Ci struct {
	ExecutionRule any
}

type ListTestsResponse_Tests_Options_MonitorOptions struct {
	EscalationMessage any
	NotificationPresetName any
	RenotifyInterval any
	RenotifyOccurrences any
}

type ListTestsResponse_Tests_Options_Retry struct {
	Count any
	Interval any
}

type ListTestsResponse_Tests_Options_RumSettings struct {
	ApplicationId any
	ClientTokenId any
	IsEnabled any
}

type ListTestsResponse_Tests_Options_Scheduling_Timeframes struct {
	Day any
	From any
	To any
}

type ListTestsResponse_Tests_Options_Scheduling struct {
	Timeframes any
	Timezone any
}

type ListTestsResponse_Tests_Options struct {
	AcceptSelfSigned any
	AllowInsecure any
	BlockedRequestPatterns any
	CaptureNetworkPayloads any
	CheckCertificateRevocation any
	Ci any
	DeviceIds any
	DisableAiaIntermediateFetching any
	DisableCors any
	DisableCsp any
	EnableProfiling any
	EnableSecurityTesting any
	FollowRedirects any
	HttpVersion any
	IgnoreCertificateValidation any
	IgnoreServerCertificateError any
	InitialNavigationTimeout any
	MinFailureDuration any
	MinLocationFailed any
	MonitorName any
	MonitorOptions any
	MonitorPriority any
	NoScreenshot any
	RestrictedRoles any
	Retry any
	RumSettings any
	Scheduling any
	TickEvery any
}

type ListTestsResponse_Tests struct {
	Config any
	Creator any
	Locations any
	Message any
	MonitorId any
	Name any
	Options any
	PublicId any
	Status any
	Subtype any
	Tags any
	Type any
}

type ListTestsResponseConfig struct {
	PageNumber any
	PageSize any
}

type ListTestsResponseAttrs struct {
	PageNumber any
	PageSize any
	// Array of Synthetic tests configuration.
	Tests any
}

var ListTestsResponse = ubx.DataSourceBinding{
	WireType: "datadog_synthetics_list_tests_response",
	Fields: ubx.FieldMap{
		"PageNumber": ubx.FieldSpec{WireName: "page_number"},
		"PageSize": ubx.FieldSpec{WireName: "page_size"},
	},
}
