# Code generated by `ubx sdk gen` from datadog_apikey_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Response_Data_Attributes:
    # The APIKeyCreateAttributes category.
    category: Any = None
    # Name of the API key.
    name: Any = None
    # The APIKeyCreateAttributes remote_config_read_enabled.
    remote_config_read_enabled: Any = None

@dataclasses.dataclass
class Response_Data:
    # Attributes used to create an API Key.
    attributes: Any = None
    # API Keys resource type.
    type: Any = None

@dataclasses.dataclass
class Response_Included_Attributes:
    created_at: Any = None
    disabled: Any = None
    email: Any = None
    handle: Any = None
    icon: Any = None
    last_login_time: Any = None
    mfa_enabled: Any = None
    modified_at: Any = None
    name: Any = None
    service_account: Any = None
    status: Any = None
    title: Any = None
    uuid: Any = None
    verified: Any = None

@dataclasses.dataclass
class Response_Included_Relationships_Org_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class Response_Included_Relationships_Org:
    data: Any = None

@dataclasses.dataclass
class Response_Included_Relationships_OtherOrgs:
    data: Any = None

@dataclasses.dataclass
class Response_Included_Relationships:
    org: Any = None
    other_orgs: Any = None
    other_users: Any = None
    roles: Any = None

@dataclasses.dataclass
class Response_Included:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

_Response_Data_AttributesFields = {
    "category": ubx.FieldSpec(wire_name="category"),
    "name": ubx.FieldSpec(wire_name="name"),
    "remote_config_read_enabled": ubx.FieldSpec(wire_name="remote_config_read_enabled"),
}

_Response_DataFields = {
    "attributes": ubx.FieldSpec(
        wire_name="attributes",
        kind="object",
        fields=_Response_Data_AttributesFields,
    ),
    "type": ubx.FieldSpec(wire_name="type"),
}

@dataclasses.dataclass
class ResponseConfig:
    # Object used to create an API key.
    data: Any = None
    # path parameter, not part of the API's own resource representation
    api_key_id: Any = None

@dataclasses.dataclass
class ResponseAttrs:
    # Object used to create an API key.
    data: Any = None
    # Array of objects related to the API key.
    included: Any = None
    # path parameter, not part of the API's own resource representation
    api_key_id: Any = None

Response = ubx.ResourceBinding(
    wire_type="datadog_apikey_response",
    fields={
        "data": ubx.FieldSpec(
            wire_name="data",
            kind="object",
            fields=_Response_DataFields,
        ),
        "api_key_id": ubx.FieldSpec(wire_name="api_key_id"),
    },
)
