// Code generated by `ubx sdk gen` from datadog_asset. DO NOT EDIT.
package asset

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Asset_Data_Attributes_OperatingSystem struct {
	Description any
	Name any
	Version any
}

type Asset_Data_Attributes_Risks struct {
	HasAccessToSensitiveData any
	HasPrivilegedAccess any
	InProduction any
	IsPubliclyAccessible any
	UnderAttack any
}

type Asset_Data_Attributes_Version struct {
	First any
	Last any
}

type Asset_Data_Attributes struct {
	Arch any
	Environments any
	Name any
	OperatingSystem any
	Risks any
	Teams any
	Type any
	Version any
}

type Asset_Data struct {
	Attributes any
	Id any
	Type any
}

type Asset_Links struct {
	// First page link.
	First any
	// Last page link.
	Last any
	// Next page link.
	Next any
	// Previous page link.
	Previous any
	// Request link.
	Self any
}

type Asset_Meta struct {
	// Number of entities included in the response.
	Count any
	// The token that identifies the request.
	Token any
	// Total number of entities across all pages.
	Total any
}

type AssetConfig struct {
}

type AssetAttrs struct {
	// List of vulnerable assets.
	Data any
	// The JSON:API links related to pagination.
	Links any
	// The metadata related to this request.
	Meta any
}

var Asset = ubx.DataSourceBinding{
	WireType: "datadog_asset",
	Fields: ubx.FieldMap{
	},
}
