// Code generated by `ubx sdk gen` from datadog_dashboard_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface List_DashboardLists_Author {
  email?: string | Computed<string>;
  handle?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface List_DashboardLists {
  author?: List_DashboardLists_Author | Computed<List_DashboardLists_Author>;
  created?: string | Computed<string>;
  dashboardCount?: number | Computed<number>;
  id?: number | Computed<number>;
  isFavorite?: boolean | Computed<boolean>;
  modified?: string | Computed<string>;
  name?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ListConfig {
}

export interface ListAttrs {
  /** List of all your dashboard lists. */
  dashboardLists: List_DashboardLists[];
}

export const List: DataSourceBinding<ListConfig, ListAttrs> = {
  wireType: "datadog_dashboard_list",
  fields: {
  },
};
