# Code generated by `ubx sdk gen` from datadog_automation_rule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Rule_Data_Attributes_Action_Data:
    agent_type: Any = None
    assigned_agent_id: Any = None
    handle: Any = None

@dataclasses.dataclass
class Rule_Data_Attributes_Action:
    data: Any = None
    type: Any = None

@dataclasses.dataclass
class Rule_Data_Attributes_Trigger_Data:
    approval_type: Any = None
    change_type: Any = None
    field: Any = None
    from_status_name: Any = None
    to_status_name: Any = None

@dataclasses.dataclass
class Rule_Data_Attributes_Trigger:
    data: Any = None
    type: Any = None

@dataclasses.dataclass
class Rule_Data_Attributes:
    action: Any = None
    created_at: Any = None
    modified_at: Any = None
    name: Any = None
    state: Any = None
    trigger: Any = None

@dataclasses.dataclass
class Rule_Data_Relationships_CreatedBy_Data:
    id: Any = None
    type: Any = None

@dataclasses.dataclass
class Rule_Data_Relationships_CreatedBy:
    data: Any = None

@dataclasses.dataclass
class Rule_Data_Relationships:
    created_by: Any = None
    modified_by: Any = None

@dataclasses.dataclass
class Rule_Data:
    attributes: Any = None
    id: Any = None
    relationships: Any = None
    type: Any = None

@dataclasses.dataclass
class RuleConfig:
    project_id: Any = None

@dataclasses.dataclass
class RuleAttrs:
    # List of automation rules.
    data: Any = None
    project_id: Any = None

Rule = ubx.DataSourceBinding(
    wire_type="datadog_automation_rule",
    fields={
        "project_id": ubx.FieldSpec(wire_name="project_id"),
    },
)
