// Code generated by `ubx sdk gen` from datadog_role_list. DO NOT EDIT.
package role

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type List_Data_Attributes struct {
	CreatedAt               any
	ModifiedAt              any
	Name                    any
	ReceivesPermissionsFrom any
	UserCount               any
}

type List_Data_Relationships_Permissions_Data struct {
	Id   any
	Type any
}

type List_Data_Relationships_Permissions struct {
	Data any
}

type List_Data_Relationships struct {
	Permissions any
}

type List_Data struct {
	Attributes    any
	Id            any
	Relationships any
	Type          any
}

type List_Meta_Page struct {
	// Total count.
	TotalCount any
	// Total count of elements matched by the filter.
	TotalFilteredCount any
}

type List_Meta struct {
	// Pagination object.
	Page any
}

type ListConfig struct {
	ArchiveId any
}

type ListAttrs struct {
	ArchiveId any
	// Array of returned roles.
	Data any
	// Object describing meta attributes of response.
	Meta any
}

var List = ubx.DataSourceBinding{
	WireType: "datadog_role_list",
	Fields: ubx.FieldMap{
		"ArchiveId": ubx.FieldSpec{WireName: "archive_id"},
	},
}
