// Code generated by `ubx sdk gen` from datadog_integration. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface IntegrationConfig {
  /** The name of a supported LLM provider integration. */
  integration: string | Computed<string>;
}

export interface IntegrationAttrs {
  /** The name of a supported LLM provider integration. */
  integration: string;
}

export const Integration: DataSourceBinding<IntegrationConfig, IntegrationAttrs> = {
  wireType: "datadog_integration",
  fields: {
    integration: "integration",
  },
};
