// Code generated by `ubx sdk gen` from datadog_llmobs_prompt_sdkresponse. DO NOT EDIT.
package llmobs

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PromptSdkresponse_Data_Attributes struct {
	// Optional description of the prompt.
	Description any
	// Optional feature-flag environment UUIDs the service attempts to enable and configure to use the first version as their default after creation.
	EnvIds any
	// Optional labels to attach to the first version. Do not use this attribute for new integrations.
	Labels any
	// Customer-provided identifier for the new prompt.
	PromptId any
	// A text template or a list of chat messages.
	Template any
	// Optional title of the prompt.
	Title any
	// Optional user-supplied version identifier for the first version.
	UserVersion any
}

type PromptSdkresponse_Data struct {
	// Attributes for creating an Agent Observability prompt and its first version. `prompt_id` and `template` are required; all other attributes are optional.
	Attributes any
	// Resource type of an Agent Observability prompt.
	Type any
}

var PromptSdkresponse_Data_AttributesFields = ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"EnvIds": ubx.FieldSpec{WireName: "env_ids"},
		"Labels": ubx.FieldSpec{WireName: "labels"},
		"PromptId": ubx.FieldSpec{WireName: "prompt_id"},
		"Template": ubx.FieldSpec{WireName: "template"},
		"Title": ubx.FieldSpec{WireName: "title"},
		"UserVersion": ubx.FieldSpec{WireName: "user_version"},
	}

var PromptSdkresponse_DataFields = ubx.FieldMap{
		"Attributes": ubx.FieldSpec{
			WireName: "attributes",
			Kind: "object",
			Fields: PromptSdkresponse_Data_AttributesFields,
		},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

type PromptSdkresponseConfig struct {
	// Data object for creating an Agent Observability prompt.
	Data any
	// path parameter, not part of the API's own resource representation
	PromptId any
}

type PromptSdkresponseAttrs struct {
	// Data object for creating an Agent Observability prompt.
	Data any
	// path parameter, not part of the API's own resource representation
	PromptId any
}

var PromptSdkresponse = ubx.ResourceBinding{
	WireType: "datadog_llmobs_prompt_sdkresponse",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind: "object",
			Fields: PromptSdkresponse_DataFields,
		},
		"PromptId": ubx.FieldSpec{WireName: "prompt_id"},
	},
}
