// Code generated by `ubx sdk gen` from datadog_fastly_service_response. DO NOT EDIT.
package fastly

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ServiceResponse_Data_Attributes struct {
	// A list of tags for the Fastly service.
	Tags any
}

type ServiceResponse_Data struct {
	// Attributes object for Fastly service requests.
	Attributes any
	// The ID of the Fastly service.
	Id any
	// The JSON:API type for this API. Should always be `fastly-services`.
	Type any
}

var ServiceResponse_Data_AttributesFields = ubx.FieldMap{
	"Tags": ubx.FieldSpec{WireName: "tags"},
}

var ServiceResponse_DataFields = ubx.FieldMap{
	"Attributes": ubx.FieldSpec{
		WireName: "attributes",
		Kind:     "object",
		Fields:   ServiceResponse_Data_AttributesFields,
	},
	"Id":   ubx.FieldSpec{WireName: "id"},
	"Type": ubx.FieldSpec{WireName: "type"},
}

type ServiceResponseConfig struct {
	// Data object for Fastly service requests.
	Data any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	ServiceId any
}

type ServiceResponseAttrs struct {
	// Data object for Fastly service requests.
	Data any
	// path parameter, not part of the API's own resource representation
	AccountId any
	// path parameter, not part of the API's own resource representation
	ServiceId any
}

var ServiceResponse = ubx.ResourceBinding{
	WireType: "datadog_fastly_service_response",
	Fields: ubx.FieldMap{
		"Data": ubx.FieldSpec{
			WireName: "data",
			Kind:     "object",
			Fields:   ServiceResponse_DataFields,
		},
		"AccountId": ubx.FieldSpec{WireName: "account_id"},
		"ServiceId": ubx.FieldSpec{WireName: "service_id"},
	},
}
