// Code generated by `ubx sdk gen` from datadog_degradation. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Degradation_Data_Attributes_ComponentsAffected {
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface Degradation_Data_Attributes {
  /** The components affected by the degradation. */
  componentsAffected: Degradation_Data_Attributes_ComponentsAffected[] | Computed<Degradation_Data_Attributes_ComponentsAffected[]>;
  /** The description of the degradation. */
  description?: string | Computed<string>;
  /** The status of the degradation. */
  status: string | Computed<string>;
  /** The title of the degradation. */
  title: string | Computed<string>;
}

export interface Degradation_Data_Relationships_Template_Data {
  /** The ID of the degradation template. */
  id: string | Computed<string>;
  /** Degradation templates resource type. */
  type: string | Computed<string>;
}

export interface Degradation_Data_Relationships_Template {
  /** The data object identifying the template used to create the degradation. */
  data: Degradation_Data_Relationships_Template_Data | Computed<Degradation_Data_Relationships_Template_Data>;
}

export interface Degradation_Data_Relationships {
  /** The template used to create the degradation. */
  template?: Degradation_Data_Relationships_Template | Computed<Degradation_Data_Relationships_Template>;
}

export interface Degradation_Data {
  /** The supported attributes for creating a degradation. */
  attributes: Degradation_Data_Attributes | Computed<Degradation_Data_Attributes>;
  /** The supported relationships for creating a degradation. */
  relationships?: Degradation_Data_Relationships | Computed<Degradation_Data_Relationships>;
  /** Degradations resource type. */
  type: string | Computed<string>;
}

export interface Degradation_Included_Attributes {
  email?: string | Computed<string>;
  handle?: string | Computed<string>;
  icon?: string | Computed<string>;
  name?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface Degradation_Included_Relationships {
  createdByUser?: Degradation_Data_Relationships_Template | Computed<Degradation_Data_Relationships_Template>;
  lastModifiedByUser?: Degradation_Data_Relationships_Template | Computed<Degradation_Data_Relationships_Template>;
}

export interface Degradation_Included {
  attributes?: Degradation_Included_Attributes | Computed<Degradation_Included_Attributes>;
  id?: string | Computed<string>;
  relationships?: Degradation_Included_Relationships | Computed<Degradation_Included_Relationships>;
  type?: string | Computed<string>;
}

export interface Degradation_Meta {
  /** A unique key used to ensure idempotent requests. */
  idempotencyKey?: string | Computed<string>;
}

const Degradation_Data_Attributes_ComponentsAffectedFields: FieldMap = {
  id: "id",
  name: "name",
  status: "status",
};

const Degradation_Data_AttributesFields: FieldMap = {
  componentsAffected: {
    wireName: "components_affected",
    kind: "list",
    fields: Degradation_Data_Attributes_ComponentsAffectedFields,
  },
  description: "description",
  status: "status",
  title: "title",
};

const Degradation_Data_Relationships_Template_DataFields: FieldMap = {
  id: "id",
  type: "type",
};

const Degradation_Data_Relationships_TemplateFields: FieldMap = {
  data: {
    wireName: "data",
    kind: "object",
    fields: Degradation_Data_Relationships_Template_DataFields,
  },
};

const Degradation_Data_RelationshipsFields: FieldMap = {
  template: {
    wireName: "template",
    kind: "object",
    fields: Degradation_Data_Relationships_TemplateFields,
  },
};

const Degradation_DataFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "object",
    fields: Degradation_Data_AttributesFields,
  },
  relationships: {
    wireName: "relationships",
    kind: "object",
    fields: Degradation_Data_RelationshipsFields,
  },
  type: "type",
};

const Degradation_MetaFields: FieldMap = {
  idempotencyKey: "idempotency_key",
};

export interface DegradationConfig {
  /** The data object for creating a degradation. */
  data?: Degradation_Data | Computed<Degradation_Data>;
  /** The supported metadata for a degradation request. */
  meta?: Degradation_Meta | Computed<Degradation_Meta>;
  /** path parameter, not part of the API's own resource representation */
  pageId: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  degradationId: string | Computed<string>;
}

export interface DegradationAttrs {
  /** The data object for creating a degradation. */
  data: Degradation_Data;
  /** The included related resources of a degradation. Client must explicitly request these resources by name in the `include` query parameter. */
  included: Degradation_Included[];
  /** The supported metadata for a degradation request. */
  meta: Degradation_Meta;
  /** path parameter, not part of the API's own resource representation */
  pageId: string;
  /** path parameter, not part of the API's own resource representation */
  degradationId: string;
}

export const Degradation: ResourceBinding<DegradationConfig, DegradationAttrs> = {
  wireType: "datadog_degradation",
  fields: {
    data: {
      wireName: "data",
      kind: "object",
      fields: Degradation_DataFields,
    },
    meta: {
      wireName: "meta",
      kind: "object",
      fields: Degradation_MetaFields,
    },
    pageId: "page_id",
    degradationId: "degradation_id",
  },
};
